/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fourgenius.www.public_access.registration.student;

import com.fourgenius.www.private_access.admin.login._jp_admin_login_email;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import public_access.MC_JavaDataBaseConnection;

/**
 *
 * @author Shadow®
 */
public class Jp_student_payment extends javax.swing.JPanel {

    Border border=BorderFactory.createLineBorder(Color.white, 1);
    /**
     * Creates new form Jp_student_payment
     */
    public Jp_student_payment() {
        initComponents();
         Date d=Calendar.getInstance().getTime();
         SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
         _lb_date.setText(sdf.format(d));
       addToTable(); 
    }

    public Jp_student_payment(String id) {
        try {
            _tf_student_payment_paymentDatails_studentId.setText(id);
        Connection connection = MC_JavaDataBaseConnection.myConnection();
            Statement statement = connection.createStatement();
            ResultSet rs= statement.executeQuery("select b.stu_info_name_first_name,b.stu_info_name_last_name,b.stu_info_name_sirName from stu_info_personal a left join stu_info_name b on a.stu_user_info_id=b.stu_user_info_id where  a.stu_info_personal_nic='"+id+"' ");
            if (rs.next()) {
                _tf_student_payment_paymentDatails_studentName.setText(rs.getString("stu_info_name_first_name")+" "+rs.getString("stu_info_name_last_name")+" "+rs.getString("stu_info_name_sirName"));
            }
            _tf_student_payment_paymentDatails_course.grabFocus();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _pl_registration_lecture_personalInformation_contactDetails = new javax.swing.JPanel();
        _lb_registration_lecture_personalInformation_contactDetails_mobileNumber = new javax.swing.JLabel();
        _tf_student_payment_paymentDatails_studentId = new javax.swing.JTextField();
        _lb_registration_lecture_personalInformation_contactDetails_landNumber = new javax.swing.JLabel();
        _tf_student_payment_paymentDatails_studentName = new javax.swing.JTextField();
        _lb_registration_lecture_personalInformation_contactDetails_eMail = new javax.swing.JLabel();
        _tf_student_payment_paymentDatails_course = new javax.swing.JTextField();
        _lb_registration_lecture_personalInformation_address_1stLine = new javax.swing.JLabel();
        _tf_student_payment_paymentDatails_courseFee = new javax.swing.JTextField();
        _lb_registration_lecture_personalInformation_address_2ndLine = new javax.swing.JLabel();
        _tf_student_payment_paymentDatails_payement = new javax.swing.JTextField();
        _lb_registration_lecture_personalInformation_address_city = new javax.swing.JLabel();
        _tf_registration_lecture_personalInformations_contactDetails_duePayment = new javax.swing.JTextField();
        _lb_registration_lecture_personalInformation_contactDetails_mobileNumber1 = new javax.swing.JLabel();
        _bt_student_payment_submit = new javax.swing.JButton();
        _lb_date = new javax.swing.JLabel();
        _lb_registration_lecture_personalInformation_address_1stLine1 = new javax.swing.JLabel();
        _tf_student_payment_paymentDatails_batch = new javax.swing.JTextField();
        _lb_registration_lecture_personalInformation_address_1stLine2 = new javax.swing.JLabel();
        _tf_student_payment_paymentDatails_year = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(66, 66, 66));

        _pl_registration_lecture_personalInformation_contactDetails.setBackground(new java.awt.Color(2, 119, 189));
        _pl_registration_lecture_personalInformation_contactDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        _lb_registration_lecture_personalInformation_contactDetails_mobileNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_personalInformation_contactDetails_mobileNumber.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_personalInformation_contactDetails_mobileNumber.setText("Student NIC");

        _tf_student_payment_paymentDatails_studentId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_student_payment_paymentDatails_studentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_student_payment_paymentDatails_studentIdActionPerformed(evt);
            }
        });

        _lb_registration_lecture_personalInformation_contactDetails_landNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_personalInformation_contactDetails_landNumber.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_personalInformation_contactDetails_landNumber.setText("Student Name");

        _tf_student_payment_paymentDatails_studentName.setEditable(false);
        _tf_student_payment_paymentDatails_studentName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_student_payment_paymentDatails_studentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_student_payment_paymentDatails_studentNameActionPerformed(evt);
            }
        });

        _lb_registration_lecture_personalInformation_contactDetails_eMail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_personalInformation_contactDetails_eMail.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_personalInformation_contactDetails_eMail.setText("Course");

        _tf_student_payment_paymentDatails_course.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_student_payment_paymentDatails_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_student_payment_paymentDatails_courseActionPerformed(evt);
            }
        });

        _lb_registration_lecture_personalInformation_address_1stLine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_personalInformation_address_1stLine.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_personalInformation_address_1stLine.setText("Course Fee");

        _tf_student_payment_paymentDatails_courseFee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_student_payment_paymentDatails_courseFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_student_payment_paymentDatails_courseFeeActionPerformed(evt);
            }
        });
        _tf_student_payment_paymentDatails_courseFee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _tf_student_payment_paymentDatails_courseFeeKeyReleased(evt);
            }
        });

        _lb_registration_lecture_personalInformation_address_2ndLine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_personalInformation_address_2ndLine.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_personalInformation_address_2ndLine.setText("Payment");

        _tf_student_payment_paymentDatails_payement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_student_payment_paymentDatails_payement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_student_payment_paymentDatails_payementActionPerformed(evt);
            }
        });
        _tf_student_payment_paymentDatails_payement.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _tf_student_payment_paymentDatails_payementKeyReleased(evt);
            }
        });

        _lb_registration_lecture_personalInformation_address_city.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_personalInformation_address_city.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_personalInformation_address_city.setText("Due Payment");

        _tf_registration_lecture_personalInformations_contactDetails_duePayment.setEditable(false);
        _tf_registration_lecture_personalInformations_contactDetails_duePayment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_personalInformations_contactDetails_duePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_personalInformations_contactDetails_duePaymentActionPerformed(evt);
            }
        });
        _tf_registration_lecture_personalInformations_contactDetails_duePayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _tf_registration_lecture_personalInformations_contactDetails_duePaymentKeyReleased(evt);
            }
        });

        _lb_registration_lecture_personalInformation_contactDetails_mobileNumber1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_personalInformation_contactDetails_mobileNumber1.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_personalInformation_contactDetails_mobileNumber1.setText("Date");

        _bt_student_payment_submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _bt_student_payment_submit.setForeground(new java.awt.Color(255, 255, 255));
        _bt_student_payment_submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/buton_blue_200x50.png"))); // NOI18N
        _bt_student_payment_submit.setText("Submit");
        _bt_student_payment_submit.setFocusPainted(false);
        _bt_student_payment_submit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _bt_student_payment_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _bt_student_payment_submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _bt_student_payment_submitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _bt_student_payment_submitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                _bt_student_payment_submitMouseReleased(evt);
            }
        });
        _bt_student_payment_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _bt_student_payment_submitActionPerformed(evt);
            }
        });

        _lb_date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_date.setForeground(new java.awt.Color(255, 255, 255));

        _lb_registration_lecture_personalInformation_address_1stLine1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_personalInformation_address_1stLine1.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_personalInformation_address_1stLine1.setText("Batch");

        _tf_student_payment_paymentDatails_batch.setEditable(false);
        _tf_student_payment_paymentDatails_batch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_student_payment_paymentDatails_batch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_student_payment_paymentDatails_batchActionPerformed(evt);
            }
        });
        _tf_student_payment_paymentDatails_batch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _tf_student_payment_paymentDatails_batchKeyReleased(evt);
            }
        });

        _lb_registration_lecture_personalInformation_address_1stLine2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_personalInformation_address_1stLine2.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_personalInformation_address_1stLine2.setText("Year");

        _tf_student_payment_paymentDatails_year.setEditable(false);
        _tf_student_payment_paymentDatails_year.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_student_payment_paymentDatails_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_student_payment_paymentDatails_yearActionPerformed(evt);
            }
        });
        _tf_student_payment_paymentDatails_year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _tf_student_payment_paymentDatails_yearKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout _pl_registration_lecture_personalInformation_contactDetailsLayout = new javax.swing.GroupLayout(_pl_registration_lecture_personalInformation_contactDetails);
        _pl_registration_lecture_personalInformation_contactDetails.setLayout(_pl_registration_lecture_personalInformation_contactDetailsLayout);
        _pl_registration_lecture_personalInformation_contactDetailsLayout.setHorizontalGroup(
            _pl_registration_lecture_personalInformation_contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pl_registration_lecture_personalInformation_contactDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_pl_registration_lecture_personalInformation_contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_tf_registration_lecture_personalInformations_contactDetails_duePayment)
                    .addComponent(_tf_student_payment_paymentDatails_batch)
                    .addGroup(_pl_registration_lecture_personalInformation_contactDetailsLayout.createSequentialGroup()
                        .addGroup(_pl_registration_lecture_personalInformation_contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(_pl_registration_lecture_personalInformation_contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(_lb_registration_lecture_personalInformation_contactDetails_mobileNumber1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                .addGroup(_pl_registration_lecture_personalInformation_contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(_bt_student_payment_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(_pl_registration_lecture_personalInformation_contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(_lb_registration_lecture_personalInformation_contactDetails_mobileNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                        .addComponent(_tf_student_payment_paymentDatails_studentId)
                                        .addComponent(_lb_registration_lecture_personalInformation_contactDetails_landNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(_tf_student_payment_paymentDatails_studentName)
                                        .addComponent(_lb_registration_lecture_personalInformation_contactDetails_eMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(_tf_student_payment_paymentDatails_course)))
                                .addComponent(_lb_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(_lb_registration_lecture_personalInformation_address_1stLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_lb_registration_lecture_personalInformation_address_1stLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(_pl_registration_lecture_personalInformation_contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(_lb_registration_lecture_personalInformation_address_1stLine, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _pl_registration_lecture_personalInformation_contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_lb_registration_lecture_personalInformation_address_2ndLine, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(_lb_registration_lecture_personalInformation_address_city, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(_tf_student_payment_paymentDatails_courseFee)
                    .addComponent(_tf_student_payment_paymentDatails_payement)
                    .addComponent(_tf_student_payment_paymentDatails_year, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        _pl_registration_lecture_personalInformation_contactDetailsLayout.setVerticalGroup(
            _pl_registration_lecture_personalInformation_contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pl_registration_lecture_personalInformation_contactDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_lb_registration_lecture_personalInformation_contactDetails_mobileNumber1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_personalInformation_contactDetails_mobileNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_student_payment_paymentDatails_studentId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_personalInformation_contactDetails_landNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_student_payment_paymentDatails_studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_personalInformation_contactDetails_eMail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_student_payment_paymentDatails_course, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_personalInformation_address_1stLine1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_student_payment_paymentDatails_batch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_personalInformation_address_1stLine2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_tf_student_payment_paymentDatails_year, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_personalInformation_address_1stLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_student_payment_paymentDatails_courseFee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_personalInformation_address_2ndLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_student_payment_paymentDatails_payement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_personalInformation_address_city)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_registration_lecture_personalInformations_contactDetails_duePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_bt_student_payment_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Course Name", "Course Fee", "Payment", "Due Payment", "Payment Date", "Complete Payemnt"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_pl_registration_lecture_personalInformation_contactDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_pl_registration_lecture_personalInformation_contactDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
Double due_payment=0.0;
    private void _tf_student_payment_paymentDatails_studentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_student_payment_paymentDatails_studentIdActionPerformed
        try {
            Connection connection = MC_JavaDataBaseConnection.myConnection();
            Statement statement = connection.createStatement();
            ResultSet rs= statement.executeQuery("select b.stu_info_name_first_name,b.stu_info_name_last_name,b.stu_info_name_sirName from stu_info_personal a left join stu_info_name b on a.stu_user_info_id=b.stu_user_info_id where  a.stu_info_personal_nic='"+_tf_student_payment_paymentDatails_studentId.getText()+"' ");
            if (rs.next()) {
                _tf_student_payment_paymentDatails_studentName.setText(rs.getString("stu_info_name_first_name")+" "+rs.getString("stu_info_name_last_name")+" "+rs.getString("stu_info_name_sirName"));
              _tf_student_payment_paymentDatails_course.grabFocus();
           rs.close();
              ResultSet rs1=statement.executeQuery("select * from student_payment where student_id='"+_tf_student_payment_paymentDatails_studentId.getText()+"'");
                System.out.println("drhzrtze");
            if (rs1.next()) {
               due_payment=rs1.getDouble("due_payment");
                System.out.println(due_payment); 
               _tf_student_payment_paymentDatails_course.setText(rs1.getString("course"));
                System.out.println(rs1.getString("course"));
                _tf_student_payment_paymentDatails_courseFee.setText(rs1.getDouble("course_fee")+"");
                System.out.println(rs1.getDouble("course_fee"));
                _tf_student_payment_paymentDatails_batch.setText(rs1.getString("batch"));
                _tf_student_payment_paymentDatails_year.setText(rs1.getString("year"));
            _tf_student_payment_paymentDatails_payement.grabFocus();
            }
            }
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event__tf_student_payment_paymentDatails_studentIdActionPerformed

    private void _tf_student_payment_paymentDatails_studentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_student_payment_paymentDatails_studentNameActionPerformed
       
    }//GEN-LAST:event__tf_student_payment_paymentDatails_studentNameActionPerformed

    private void _tf_student_payment_paymentDatails_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_student_payment_paymentDatails_courseActionPerformed
        _tf_student_payment_paymentDatails_courseFee.grabFocus();
    }//GEN-LAST:event__tf_student_payment_paymentDatails_courseActionPerformed

    private void _tf_student_payment_paymentDatails_courseFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_student_payment_paymentDatails_courseFeeActionPerformed
        _tf_student_payment_paymentDatails_payement.grabFocus();
        
    }//GEN-LAST:event__tf_student_payment_paymentDatails_courseFeeActionPerformed

    private void _tf_student_payment_paymentDatails_payementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_student_payment_paymentDatails_payementActionPerformed
        if (!(due_payment==0.0)) {
            System.out.println("akkopk");
            Double new_due=due_payment-Double.parseDouble(_tf_student_payment_paymentDatails_payement.getText());
            _tf_registration_lecture_personalInformations_contactDetails_duePayment.setText(new_due+"0");
        }
        else{
        
         Double due= Double.parseDouble(_tf_student_payment_paymentDatails_courseFee.getText())-Double.parseDouble(_tf_student_payment_paymentDatails_payement.getText());
      _tf_registration_lecture_personalInformations_contactDetails_duePayment.setText(due+"0");
        }
    }//GEN-LAST:event__tf_student_payment_paymentDatails_payementActionPerformed

    private void _tf_registration_lecture_personalInformations_contactDetails_duePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_personalInformations_contactDetails_duePaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__tf_registration_lecture_personalInformations_contactDetails_duePaymentActionPerformed

    private void _bt_student_payment_submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_student_payment_submitMouseEntered
        _bt_student_payment_submit.setBorder(border);
    }//GEN-LAST:event__bt_student_payment_submitMouseEntered

    private void _bt_student_payment_submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_student_payment_submitMouseExited
        _bt_student_payment_submit.setBorder(null);
    }//GEN-LAST:event__bt_student_payment_submitMouseExited

    private void _bt_student_payment_submitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_student_payment_submitMousePressed
        _bt_student_payment_submit.setBorder(null);
    }//GEN-LAST:event__bt_student_payment_submitMousePressed

    private void _bt_student_payment_submitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_student_payment_submitMouseReleased
        _bt_student_payment_submit.setBorder(border);
    }//GEN-LAST:event__bt_student_payment_submitMouseReleased

    private void _bt_student_payment_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__bt_student_payment_submitActionPerformed
        
        try {
            Connection connection = MC_JavaDataBaseConnection.myConnection();
            Statement statement = connection.createStatement();
            ResultSet rs=statement.executeQuery("select * from student_payment where student_id='"+_tf_student_payment_paymentDatails_studentId.getText()+"'");
            if (rs.next()) {
               statement.executeUpdate("update student_payment set date='"+_lb_date.getText()+"',student_id='"+_tf_student_payment_paymentDatails_studentId.getText()+"',student_name='"+_tf_student_payment_paymentDatails_studentName.getText()+"',course='"+_tf_student_payment_paymentDatails_course.getText()+"',course_fee='"+_tf_student_payment_paymentDatails_courseFee.getText()+"',payment='"+_tf_student_payment_paymentDatails_payement.getText()+"',due_payment='"+_tf_registration_lecture_personalInformations_contactDetails_duePayment.getText()+"'");
           addToTable();
            }else{
            statement.executeUpdate("insert into student_payment(date,student_id,student_name,course,course_fee,payment,due_payment) values ('"+_lb_date.getText()+"','" + _tf_student_payment_paymentDatails_studentId.getText() + "','" +_tf_student_payment_paymentDatails_studentName.getText()+ "','"+_tf_student_payment_paymentDatails_course.getText()+"','"+_tf_student_payment_paymentDatails_courseFee.getText()+"','"+_tf_student_payment_paymentDatails_payement.getText()+"','"+_tf_registration_lecture_personalInformations_contactDetails_duePayment.getText()+"')");
            addToTable();
            }
            
            _tf_registration_lecture_personalInformations_contactDetails_duePayment.setText(null);
            _tf_student_payment_paymentDatails_course.setText(null);
            _tf_student_payment_paymentDatails_courseFee.setText(null);
            _tf_student_payment_paymentDatails_payement.setText(null);
            _tf_student_payment_paymentDatails_studentId.setText(null);
            _tf_student_payment_paymentDatails_studentName.setText(null);
            _tf_student_payment_paymentDatails_batch.setText(null);
            _tf_student_payment_paymentDatails_year.setText(null);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event__bt_student_payment_submitActionPerformed

    private void _tf_student_payment_paymentDatails_courseFeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_student_payment_paymentDatails_courseFeeKeyReleased
        
        char c=evt.getKeyChar();
        if (Character.isLetter(c)) {
            
            evt.consume();
            
        }
        
    }//GEN-LAST:event__tf_student_payment_paymentDatails_courseFeeKeyReleased

    private void _tf_student_payment_paymentDatails_payementKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_student_payment_paymentDatails_payementKeyReleased
        
         char c=evt.getKeyChar();
        if (Character.isLetter(c)) {
            
            evt.consume();
            
        }
        
    }//GEN-LAST:event__tf_student_payment_paymentDatails_payementKeyReleased

    private void _tf_registration_lecture_personalInformations_contactDetails_duePaymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_registration_lecture_personalInformations_contactDetails_duePaymentKeyReleased
       
         char c=evt.getKeyChar();
        if (Character.isLetter(c)) {
            
            evt.consume();
            
        }
        
    }//GEN-LAST:event__tf_registration_lecture_personalInformations_contactDetails_duePaymentKeyReleased

    private void _tf_student_payment_paymentDatails_batchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_student_payment_paymentDatails_batchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__tf_student_payment_paymentDatails_batchActionPerformed

    private void _tf_student_payment_paymentDatails_batchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_student_payment_paymentDatails_batchKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event__tf_student_payment_paymentDatails_batchKeyReleased

    private void _tf_student_payment_paymentDatails_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_student_payment_paymentDatails_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__tf_student_payment_paymentDatails_yearActionPerformed

    private void _tf_student_payment_paymentDatails_yearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_student_payment_paymentDatails_yearKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event__tf_student_payment_paymentDatails_yearKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _bt_student_payment_submit;
    private javax.swing.JLabel _lb_date;
    private javax.swing.JLabel _lb_registration_lecture_personalInformation_address_1stLine;
    private javax.swing.JLabel _lb_registration_lecture_personalInformation_address_1stLine1;
    private javax.swing.JLabel _lb_registration_lecture_personalInformation_address_1stLine2;
    private javax.swing.JLabel _lb_registration_lecture_personalInformation_address_2ndLine;
    private javax.swing.JLabel _lb_registration_lecture_personalInformation_address_city;
    private javax.swing.JLabel _lb_registration_lecture_personalInformation_contactDetails_eMail;
    private javax.swing.JLabel _lb_registration_lecture_personalInformation_contactDetails_landNumber;
    private javax.swing.JLabel _lb_registration_lecture_personalInformation_contactDetails_mobileNumber;
    private javax.swing.JLabel _lb_registration_lecture_personalInformation_contactDetails_mobileNumber1;
    private javax.swing.JPanel _pl_registration_lecture_personalInformation_contactDetails;
    private javax.swing.JTextField _tf_registration_lecture_personalInformations_contactDetails_duePayment;
    public static javax.swing.JTextField _tf_student_payment_paymentDatails_batch;
    public static javax.swing.JTextField _tf_student_payment_paymentDatails_course;
    public static javax.swing.JTextField _tf_student_payment_paymentDatails_courseFee;
    private javax.swing.JTextField _tf_student_payment_paymentDatails_payement;
    public static javax.swing.JTextField _tf_student_payment_paymentDatails_studentId;
    public static javax.swing.JTextField _tf_student_payment_paymentDatails_studentName;
    public static javax.swing.JTextField _tf_student_payment_paymentDatails_year;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void addToTable() {
        try {
              Connection connection = MC_JavaDataBaseConnection.myConnection();
            Statement statement = connection.createStatement();
            ResultSet rs=statement.executeQuery("select * from student_payment");
            DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
            Vector v=new Vector();
           
            while (rs.next()) {                
                v.add(rs.getString("student_id"));
                v.add(rs.getString("student_name"));
                v.add(rs.getString("course"));
                v.add(rs.getString("course_fee"));
                v.add(rs.getString("payment"));
                v.add(rs.getString("due_payment"));
                v.add(rs.getString("date"));
             if (rs.getString("due_payment").equals("0")) {
                v.add("Completed");
            }else{
             v.add("Not completed");
             }
            }
           
            dtm.addRow(v);
        } catch (Exception e) {
            e.printStackTrace();
        }
            
    }
}
