/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fourgenius.www.admin_BackEnd;

import com.fourgenius.www.public_access.user.login.Jf_user_login;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.border.Border;

/**
 *
 * @author deepalsuranga
 */
public class Jf_admin_backend extends javax.swing.JFrame {

    /*
     * Creates new form _jf_admin_backend
     */
    public Jf_admin_backend() {
        initComponents();
        //showTime();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
        
        md_setvisible_false(bt_admin_bE_home);
        md_setvisible_false(bt_admin_bE_students);
        md_setvisible_false(bt_admin_bE_users);
        md_setvisible_false(bt_admin_bE_employees);
        md_setvisible_false(bt_admin_bE_exams);
        md_setvisible_false(bt_admin_bE_payments);
        md_setvisible_false(bt_admin_bE_practicals);
        md_setvisible_false(bt_admin_bE_administrator);
        Jp_admin_mainManu_in manu = new Jp_admin_mainManu_in();
//        Jp_admin_in_menu manu=new Jp_admin_mainManu_in();
//
        if (manu == null) {
            manu = new Jp_admin_mainManu_in();
            admin_mainPanel.removeAll();
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
            admin_mainPanel.add(manu);
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
        } else {
            admin_mainPanel.removeAll();
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
            admin_mainPanel.add(manu);
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jp_admin_in_menu_M = new javax.swing.JPanel();
        workArea = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        background_card = new javax.swing.JPanel();
        back = new javax.swing.JPanel();
        admin_mainPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        bt_admin_bE_users = new javax.swing.JButton();
        bt_admin_bE_students = new javax.swing.JButton();
        bt_admin_bE_employees = new javax.swing.JButton();
        bt_admin_bE_exams = new javax.swing.JButton();
        bt_admin_bE_payments = new javax.swing.JButton();
        bt_admin_bE_practicals = new javax.swing.JButton();
        bt_admin_bE_administrator = new javax.swing.JButton();
        bt_admin_bE_home = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bt_admin_bE_logout = new javax.swing.JButton();

        Jp_admin_in_menu_M.setBackground(new java.awt.Color(66, 66, 66));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/private_access/admin_menu/src/admin_menu_student.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/private_access/admin_menu/src/admin_menu_lecture.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/private_access/admin_menu/src/admin_menu_user.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/private_access/admin_menu/src/admin_menu_employee.png"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/private_access/admin_menu/src/admin_menu_exam.png"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/private_access/admin_menu/src/admin_menu_payments.png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/private_access/admin_menu/src/admin_menu_adminstration.png"))); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/private_access/admin_menu/src/admin_menu_Practical.png"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout Jp_admin_in_menu_MLayout = new javax.swing.GroupLayout(Jp_admin_in_menu_M);
        Jp_admin_in_menu_M.setLayout(Jp_admin_in_menu_MLayout);
        Jp_admin_in_menu_MLayout.setHorizontalGroup(
            Jp_admin_in_menu_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jp_admin_in_menu_MLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(Jp_admin_in_menu_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(Jp_admin_in_menu_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(Jp_admin_in_menu_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Jp_admin_in_menu_MLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Jp_admin_in_menu_MLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(workArea, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Jp_admin_in_menu_MLayout.setVerticalGroup(
            Jp_admin_in_menu_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jp_admin_in_menu_MLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(workArea, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Jp_admin_in_menu_MLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(Jp_admin_in_menu_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Jp_admin_in_menu_MLayout.createSequentialGroup()
                        .addGroup(Jp_admin_in_menu_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Jp_admin_in_menu_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Jp_admin_in_menu_MLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Jp_admin_in_menu_MLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);

        background_card.setPreferredSize(new java.awt.Dimension(1366, 768));
        background_card.setLayout(new java.awt.CardLayout());

        back.setBackground(new java.awt.Color(21, 21, 21));

        admin_mainPanel.setBackground(new java.awt.Color(117, 117, 117));
        admin_mainPanel.setFocusTraversalPolicyProvider(true);
        admin_mainPanel.setMinimumSize(new java.awt.Dimension(1360, 668));
        admin_mainPanel.setPreferredSize(new java.awt.Dimension(1360, 668));
        admin_mainPanel.setLayout(new java.awt.CardLayout());

        menuPanel.setBackground(new java.awt.Color(33, 33, 33));

        bt_admin_bE_users.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_admin_bE_users.setText("Users");
        bt_admin_bE_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_admin_bE_usersActionPerformed(evt);
            }
        });

        bt_admin_bE_students.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_admin_bE_students.setText("Students");
        bt_admin_bE_students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_admin_bE_studentsActionPerformed(evt);
            }
        });

        bt_admin_bE_employees.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_admin_bE_employees.setText("Employees");
        bt_admin_bE_employees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_admin_bE_employeesActionPerformed(evt);
            }
        });

        bt_admin_bE_exams.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_admin_bE_exams.setText("Exams");
        bt_admin_bE_exams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_admin_bE_examsActionPerformed(evt);
            }
        });

        bt_admin_bE_payments.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_admin_bE_payments.setText("Payments");
        bt_admin_bE_payments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_admin_bE_paymentsActionPerformed(evt);
            }
        });

        bt_admin_bE_practicals.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_admin_bE_practicals.setText("Practicals");
        bt_admin_bE_practicals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_admin_bE_practicalsActionPerformed(evt);
            }
        });

        bt_admin_bE_administrator.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_admin_bE_administrator.setText("Administrator");
        bt_admin_bE_administrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_admin_bE_administratorActionPerformed(evt);
            }
        });

        bt_admin_bE_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/private_access/admin_menu/src/home.png"))); // NOI18N
        bt_admin_bE_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_admin_bE_homeActionPerformed(evt);
            }
        });

        bt_admin_bE_logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_admin_bE_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/private_access/admin_menu/src/logout_normal.png"))); // NOI18N
        bt_admin_bE_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_admin_bE_logout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/private_access/admin_menu/src/logout_select.png"))); // NOI18N
        bt_admin_bE_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_admin_bE_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_admin_bE_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_admin_bE_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_admin_bE_home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_admin_bE_students, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_admin_bE_users, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_admin_bE_employees, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_admin_bE_exams, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_admin_bE_payments, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_admin_bE_practicals, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_admin_bE_administrator, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bt_admin_bE_payments, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_admin_bE_practicals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_admin_bE_students, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_admin_bE_home, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_admin_bE_users, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_admin_bE_employees, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_admin_bE_exams, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_admin_bE_administrator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(admin_mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(admin_mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE))
        );

        background_card.add(back, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    Jp_admin_exam examPanel = new Jp_admin_exam();

    Border borderE = BorderFactory.createLineBorder(new Color(244, 67, 54), 1);
    Border borderC = BorderFactory.createLineBorder(new Color(255, 255, 255), 1);

    private void bt_admin_bE_examsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_admin_bE_examsActionPerformed

        if (!(examPanel == null)) {

            admin_mainPanel.removeAll();
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
            admin_mainPanel.add(examPanel);
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();

        } else if (examPanel == null) {

            examPanel = new Jp_admin_exam();
            admin_mainPanel.removeAll();
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
            admin_mainPanel.add(examPanel);
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();

        }


    }//GEN-LAST:event_bt_admin_bE_examsActionPerformed
    Jp_admin_employee_ac employeePanel = new Jp_admin_employee_ac();
    jf_pro_version pro = new jf_pro_version();
    private void bt_admin_bE_employeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_admin_bE_employeesActionPerformed
 pro.setVisible(true);
//        if (!(employeePanel == null)) {
//
//            admin_mainPanel.removeAll();
//            admin_mainPanel.repaint();
//            admin_mainPanel.revalidate();
//            admin_mainPanel.add(employeePanel);
//            admin_mainPanel.repaint();
//            admin_mainPanel.revalidate();
//
//        } else if (employeePanel == null) {
//
//            employeePanel = new Jp_admin_employee_ac();
//            admin_mainPanel.removeAll();
//            admin_mainPanel.repaint();
//            admin_mainPanel.revalidate();
//            admin_mainPanel.add(employeePanel);
//            admin_mainPanel.repaint();
//            admin_mainPanel.revalidate();
//
//        }


    }//GEN-LAST:event_bt_admin_bE_employeesActionPerformed
    Jp_admin_user userPanel = new Jp_admin_user();
    private void bt_admin_bE_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_admin_bE_usersActionPerformed

        if (!(userPanel == null)) {

            admin_mainPanel.removeAll();
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
            admin_mainPanel.add(userPanel);
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();

        } else if (userPanel == null) {

            userPanel = new Jp_admin_user();
            admin_mainPanel.removeAll();
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
            admin_mainPanel.add(userPanel);
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();

        }

    }//GEN-LAST:event_bt_admin_bE_usersActionPerformed

    Jf_user_login jf_user_login = new Jf_user_login();
    private void bt_admin_bE_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_admin_bE_logoutActionPerformed
        //Jf_user_login jf_user_login=new Jf_user_login();
        if (jf_user_login == null) {
            jf_user_login = new Jf_user_login();
            jf_user_login.setVisible(true);
            this.dispose();
        } else {
            jf_user_login.setVisible(true);
            this.dispose();
        }


    }//GEN-LAST:event_bt_admin_bE_logoutActionPerformed
    Jp_admin_student studentPanel = new Jp_admin_student();
    private void bt_admin_bE_studentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_admin_bE_studentsActionPerformed

        if (!(studentPanel == null)) {
            admin_mainPanel.removeAll();
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
            admin_mainPanel.add(studentPanel);
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();

        } else if (studentPanel == null) {

            studentPanel = new Jp_admin_student();
            admin_mainPanel.removeAll();
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
            admin_mainPanel.add(studentPanel);
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();

        }

    }//GEN-LAST:event_bt_admin_bE_studentsActionPerformed
    Jp_admin_payment paymentPanel = new Jp_admin_payment();
    private void bt_admin_bE_paymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_admin_bE_paymentsActionPerformed

        if (!(paymentPanel == null)) {
            admin_mainPanel.removeAll();
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
            admin_mainPanel.add(paymentPanel);
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();

        } else if (paymentPanel == null) {

            paymentPanel = new Jp_admin_payment();
            admin_mainPanel.removeAll();
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
            admin_mainPanel.add(paymentPanel);
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();

        }


    }//GEN-LAST:event_bt_admin_bE_paymentsActionPerformed
    Jp_admin_practical practicalPanel = new Jp_admin_practical();
    private void bt_admin_bE_practicalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_admin_bE_practicalsActionPerformed

        if (!(practicalPanel == null)) {
            admin_mainPanel.removeAll();
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
            admin_mainPanel.add(practicalPanel);
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();

        } else if (practicalPanel == null) {

            studentPanel = new Jp_admin_student();
            admin_mainPanel.removeAll();
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
            admin_mainPanel.add(practicalPanel);
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();

        }

    }//GEN-LAST:event_bt_admin_bE_practicalsActionPerformed

    Jp_admin_admins jp_admin_admins = new Jp_admin_admins();
    private void bt_admin_bE_administratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_admin_bE_administratorActionPerformed

        if (!(practicalPanel == null)) {
            admin_mainPanel.removeAll();
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
            admin_mainPanel.add(jp_admin_admins);
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();

        } else if (jp_admin_admins == null) {

            studentPanel = new Jp_admin_student();
            admin_mainPanel.removeAll();
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
            admin_mainPanel.add(jp_admin_admins);
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();

        }


    }//GEN-LAST:event_bt_admin_bE_administratorActionPerformed

    private void bt_admin_bE_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_admin_bE_homeActionPerformed

        md_setvisible_false(bt_admin_bE_home);
        md_setvisible_false(bt_admin_bE_students);
        md_setvisible_false(bt_admin_bE_users);
        md_setvisible_false(bt_admin_bE_employees);
        md_setvisible_false(bt_admin_bE_exams);
        md_setvisible_false(bt_admin_bE_payments);
        md_setvisible_false(bt_admin_bE_practicals);
        md_setvisible_false(bt_admin_bE_administrator);

        Jp_admin_mainManu_in manu = new Jp_admin_mainManu_in();

        if (manu == null) {
            manu = new Jp_admin_mainManu_in();
            admin_mainPanel.removeAll();
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
            admin_mainPanel.add(manu);
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
        } else {
            admin_mainPanel.removeAll();
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
            admin_mainPanel.add(manu);
            admin_mainPanel.repaint();
            admin_mainPanel.revalidate();
        }


    }//GEN-LAST:event_bt_admin_bE_homeActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        //jLabel4.setBorder(borderC);
        admin_mainPanel.removeAll();
        revalidate();
        Jp_admin_student studentPanelM = new Jp_admin_student();
        studentPanelM.setVisible(true);
        admin_mainPanel.add(studentPanelM);
        revalidate();

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered

        jLabel4.setBorder(borderE);
        //jLabel4.setBorder(borderC);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited

        jLabel4.setBorder(borderC);

    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        //jLabel5.setBorder(borderE);
        jLabel5.setBorder(borderC);

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered

        jLabel5.setBorder(borderE);
        //jLabel5.setBorder(borderC);

    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        //jLabel6.setBorder(borderE);
        jLabel6.setBorder(borderC);

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered

        jLabel6.setBorder(borderE);
        //jLabel6.setBorder(borderC);

    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        //jLabel7.setBorder(borderE);
        jLabel7.setBorder(borderC);

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        //jLabel4.setBorder(borderE);
        jLabel8.setBorder(borderC);

    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered

        jLabel8.setBorder(borderE);
        //jLabel4.setBorder(borderC);

    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

        //jLabel9.setBorder(borderE);
        jLabel9.setBorder(borderC);

    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered

        jLabel9.setBorder(borderE);
        //jLabel4.setBorder(borderC);

    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

        //jLabel4.setBorder(borderE);
        jLabel10.setBorder(borderC);

    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered

        jLabel10.setBorder(borderE);
        //jLabel4.setBorder(borderC);

    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked

        //jLabel4.setBorder(borderE);
        jLabel11.setBorder(borderC);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered

        jLabel11.setBorder(borderE);
        //jLabel4.setBorder(borderC);

    }//GEN-LAST:event_jLabel11MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jf_admin_backend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jf_admin_backend().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jp_admin_in_menu_M;
    public static javax.swing.JPanel admin_mainPanel;
    private javax.swing.JPanel back;
    private javax.swing.JPanel background_card;
    public static javax.swing.JButton bt_admin_bE_administrator;
    public static javax.swing.JButton bt_admin_bE_employees;
    public static javax.swing.JButton bt_admin_bE_exams;
    public static javax.swing.JButton bt_admin_bE_home;
    private javax.swing.JButton bt_admin_bE_logout;
    public static javax.swing.JButton bt_admin_bE_payments;
    public static javax.swing.JButton bt_admin_bE_practicals;
    public static javax.swing.JButton bt_admin_bE_students;
    public static javax.swing.JButton bt_admin_bE_users;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel workArea;
    // End of variables declaration//GEN-END:variables

    public static void md_setvisible_false(JButton bt) {
        bt.setVisible(false);
    }

    public static void md_setvisible_true(JButton bt) {
        bt.setVisible(true);
    }
    
    void showTime(JLabel label) {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {

                Date d = new Date();
                SimpleDateFormat stim = new SimpleDateFormat("hh:mm:ss a");
                String st = stim.format(d);
                label.setText(st);

            }
        }).start();
    }
}
