/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fourgenius.www.public_access.registration;

import com.fourgenius.www.user_FrontEnd.Jf_UserMain;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.border.Border;
import public_access.MC_JavaDataBaseConnection;

/**
 *
 * @author Shadow®
 */
public class Jp_registration_student_c_layout extends javax.swing.JPanel {

    Border border = BorderFactory.createLineBorder(Color.white, 1);
    String path, newpath;
    boolean b;
    Jp_registration_student_information_table_active active_lecture = new Jp_registration_student_information_table_active();
    Jp_registration_student_information_table_deactive deactive_lecture = new Jp_registration_student_information_table_deactive();

    /**
     * Creates new form registration_student
     */
    public Jp_registration_student_c_layout() {

        initComponents();
        jtp_stu_table.add("Active Student", active_lecture);
        jtp_stu_table.add("Deactive Student", deactive_lecture);
        _li_registration_student_searchStudent.setVisible(false);
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student_mainPanel = new javax.swing.JPanel();
        jtp_stu_table = new javax.swing.JTabbedPane();
        sp_registration_student_searchStudent = new javax.swing.JScrollPane();
        _li_registration_student_searchStudent = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(66, 66, 66));
        setForeground(new java.awt.Color(66, 66, 66));
        setMinimumSize(new java.awt.Dimension(1360, 718));
        setPreferredSize(new java.awt.Dimension(1360, 718));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        student_mainPanel.setLayout(new java.awt.CardLayout());

        jtp_stu_table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        student_mainPanel.add(jtp_stu_table, "card2");
        jtp_stu_table.getAccessibleContext().setAccessibleName("");

        add(student_mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 620));

        sp_registration_student_searchStudent.setViewportView(_li_registration_student_searchStudent);

        add(sp_registration_student_searchStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 310, 570));

        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 50));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 310, 50));
    }// </editor-fold>//GEN-END:initComponents
    int i = 0;

    Jp_registration_student_informations rsi = new Jp_registration_student_informations();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList _li_registration_student_searchStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTabbedPane jtp_stu_table;
    private javax.swing.JScrollPane sp_registration_student_searchStudent;
    private javax.swing.JPanel student_mainPanel;
    // End of variables declaration//GEN-END:variables

    public void printReport() {

        //        
//                   try {
//            String report_path = "src/reports/student_reg.jrxml";
//                       System.out.println("oooo");
//            JasperReport compileReport=JasperCompileManager.compileReport(report_path);
//                       System.out.println("ok1");
//                       Map<String, Object> m = new HashMap<String, Object>();
//            System.out.println("ok2");
//            m.put("course", _lb_registration_student_preview_course.getText());
//            m.put("name",_lb_registration_student_preview_name.getText() );
//            m.put("address",_lb_registration_student_preview_address.getText() );
//            m.put("telePhone",_lb_registration_student_preview_homeNumber.getText() );
//            m.put("mobilePhone", _lb_registration_student_preview_mobileNumber.getText());
//            m.put("email", _lb_registration_student_preview_eMail.getText());
//            m.put("dob", _lb_registration_student_preview_dateOfBirth.getText());
//            m.put("age",_lb_registration_student_preview_age.getText());
//            m.put("nic", _lb_registration_student_preview_nic.getText());
//            m.put("sid", _lb_registration_student_preview_studentID.getText());
//                       System.out.println("ok3");
//                       JasperPrint jp=JasperFillManager.fillReport(compileReport, m);
//                       System.out.println("ok4");
//                       JasperViewer.viewReport(jp, false);
//                       System.out.println("ok5");
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//  
    }

}
