/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fourgenius.www.public_access.registration;

import com.fourgenius.www.private_access.admin.method.*;

/**
 *
 * @author Dineth Jayasekera
 */
public class Jp_registration_employee_informations_view extends javax.swing.JPanel {

    /*
     * Creates new form Jp_registration_employee_informations_view
     */
    public Jp_registration_employee_informations_view() {
        initComponents();
       
        Jp_registration_employee_informations_form_active_employee_table active_employee=new Jp_registration_employee_informations_form_active_employee_table();
        Jp_registration_employee_informations_form_deactive_employee_table deactive_employee=new Jp_registration_employee_informations_form_deactive_employee_table();
        jTabbedPane1.add("Active Employee", active_employee);
        jTabbedPane1.add("De-active Employee", deactive_employee);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        _tf_registration_employee_informations_view_searchStudent = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        _li_registration_employee_informations_view_searchStudent = new javax.swing.JList();
        _bt_registration_employee_informations_view_search = new javax.swing.JButton();

        setBackground(new java.awt.Color(66, 66, 66));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 970, 610));

        _tf_registration_employee_informations_view_searchStudent.setMaximumSize(new java.awt.Dimension(300, 50));
        _tf_registration_employee_informations_view_searchStudent.setMinimumSize(new java.awt.Dimension(300, 50));
        _tf_registration_employee_informations_view_searchStudent.setPreferredSize(new java.awt.Dimension(300, 50));
        _tf_registration_employee_informations_view_searchStudent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _tf_registration_employee_informations_view_searchStudentKeyReleased(evt);
            }
        });
        add(_tf_registration_employee_informations_view_searchStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(992, 38, -1, -1));

        _li_registration_employee_informations_view_searchStudent.setAlignmentX(1.0F);
        jScrollPane1.setViewportView(_li_registration_employee_informations_view_searchStudent);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(992, 88, 300, 540));

        _bt_registration_employee_informations_view_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _bt_registration_employee_informations_view_searchActionPerformed(evt);
            }
        });
        add(_bt_registration_employee_informations_view_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 38, 50, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void _tf_registration_employee_informations_view_searchStudentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_registration_employee_informations_view_searchStudentKeyReleased


    }//GEN-LAST:event__tf_registration_employee_informations_view_searchStudentKeyReleased

    private void _bt_registration_employee_informations_view_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__bt_registration_employee_informations_view_searchActionPerformed

        Md_check_id checkId = new Md_check_id();
        String idType = checkId.Md_check_id(_tf_registration_employee_informations_view_searchStudent.getText());
        switch (idType) {
            case "passport":
                
                break;

            case "nic":
                
                break;

            case "name":
                
                break;
        }
    }//GEN-LAST:event__bt_registration_employee_informations_view_searchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _bt_registration_employee_informations_view_search;
    private javax.swing.JList _li_registration_employee_informations_view_searchStudent;
    private javax.swing.JTextField _tf_registration_employee_informations_view_searchStudent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
