/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fourgenius.www.public_access.registration;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author Pamitha Gayashan
 */
public class Jp_registration_lecture_informations_qulifications_form extends javax.swing.JPanel {

    Jp_registration_lecture_informations_qulifications_form_qulifications_table qulification_table=new Jp_registration_lecture_informations_qulifications_form_qulifications_table();
    Jp_registration_lecture_informations_qulifications_form_ol_table ol_table=new Jp_registration_lecture_informations_qulifications_form_ol_table();
    Jp_registration_lecture_informations_qulifications_form_al_table al_table=new Jp_registration_lecture_informations_qulifications_form_al_table();
    
    Border border=BorderFactory.createLineBorder(Color.white, 1);
    /**
     * Creates new form Jp_registration_lecture_informations_qulifications_form
     */
    public Jp_registration_lecture_informations_qulifications_form() {
        initComponents();
        _bt_registration_lecture_personalInformation_qulification_preview_remove.setEnabled(false);
        _bt_registration_lecture_personalInformation_qulification_preview_update.setEnabled(false);
        
        _tp_registration_lecture_qulifications_tables.add("Qulification", qulification_table);
        _tp_registration_lecture_qulifications_tables.add("O/L Results", ol_table);
        _tp_registration_lecture_qulifications_tables.add("A/L Results", al_table);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _bg_lecture_qulification_ol_al = new javax.swing.ButtonGroup();
        _pl_registration_lecture_personalInformation_qulifications = new javax.swing.JPanel();
        _pl_registration_lecture_personalInformation_qulifications_details = new javax.swing.JPanel();
        _lb_registration_lecture_personalInformation_lectureName_sirName = new javax.swing.JLabel();
        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_fileNo = new javax.swing.JTextField();
        _lb_registration_lecture_personalInformation_lectureName_firstName = new javax.swing.JLabel();
        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_name = new javax.swing.JTextField();
        _lb_registration_lecture_personalInformation_lectureName_lastName = new javax.swing.JLabel();
        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_type = new javax.swing.JTextField();
        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_year = new javax.swing.JTextField();
        _lb_registration_lecture_personalInformation_idInformation_nicNumber = new javax.swing.JLabel();
        _bt_registration_lecture_personalInformation_qulification_details_add = new javax.swing.JButton();
        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_year1 = new javax.swing.JTextField();
        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_year2 = new javax.swing.JTextField();
        _bt_registration_lecture_personalInformation_qulification_details_add1 = new javax.swing.JButton();
        _lb_registration_lecture_personalInformation_lectureName_sirName1 = new javax.swing.JLabel();
        _lb_registration_lecture_personalInformation_lectureName_sirName2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        _pl_registration_lecture_personalInformation_qulifications_preview = new javax.swing.JPanel();
        _bt_registration_lecture_personalInformation_qulification_preview_remove = new javax.swing.JButton();
        _bt_registration_lecture_personalInformation_qulification_preview_update = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        _tp_registration_lecture_qulifications_tables = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(66, 66, 66));

        _pl_registration_lecture_personalInformation_qulifications.setBackground(new java.awt.Color(2, 119, 189));
        _pl_registration_lecture_personalInformation_qulifications.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        _pl_registration_lecture_personalInformation_qulifications_details.setBackground(new java.awt.Color(2, 119, 189));
        _pl_registration_lecture_personalInformation_qulifications_details.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Qulifications Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        _pl_registration_lecture_personalInformation_qulifications_details.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        _lb_registration_lecture_personalInformation_lectureName_sirName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_personalInformation_lectureName_sirName.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_personalInformation_lectureName_sirName.setText("Qulifications File No");
        _pl_registration_lecture_personalInformation_qulifications_details.add(_lb_registration_lecture_personalInformation_lectureName_sirName, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, 333, -1));

        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_fileNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_fileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_personalInformations_lectureDetails_qulifications_fileNoActionPerformed(evt);
            }
        });
        _pl_registration_lecture_personalInformation_qulifications_details.add(_tf_registration_lecture_personalInformations_lectureDetails_qulifications_fileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 53, 333, 40));

        _lb_registration_lecture_personalInformation_lectureName_firstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_personalInformation_lectureName_firstName.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_personalInformation_lectureName_firstName.setText("Qulification Name");
        _pl_registration_lecture_personalInformation_qulifications_details.add(_lb_registration_lecture_personalInformation_lectureName_firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 99, 333, -1));

        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_personalInformations_lectureDetails_qulifications_nameActionPerformed(evt);
            }
        });
        _pl_registration_lecture_personalInformation_qulifications_details.add(_tf_registration_lecture_personalInformations_lectureDetails_qulifications_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 122, 333, 40));

        _lb_registration_lecture_personalInformation_lectureName_lastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_personalInformation_lectureName_lastName.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_personalInformation_lectureName_lastName.setText("Qulifications Type");
        _pl_registration_lecture_personalInformation_qulifications_details.add(_lb_registration_lecture_personalInformation_lectureName_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 168, 333, -1));

        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_personalInformations_lectureDetails_qulifications_typeActionPerformed(evt);
            }
        });
        _pl_registration_lecture_personalInformation_qulifications_details.add(_tf_registration_lecture_personalInformations_lectureDetails_qulifications_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 191, 333, 40));

        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_year.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_personalInformations_lectureDetails_qulifications_yearActionPerformed(evt);
            }
        });
        _pl_registration_lecture_personalInformation_qulifications_details.add(_tf_registration_lecture_personalInformations_lectureDetails_qulifications_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 260, 333, 40));

        _lb_registration_lecture_personalInformation_idInformation_nicNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_personalInformation_idInformation_nicNumber.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_personalInformation_idInformation_nicNumber.setText("Qulification Year");
        _pl_registration_lecture_personalInformation_qulifications_details.add(_lb_registration_lecture_personalInformation_idInformation_nicNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 237, 333, -1));

        _bt_registration_lecture_personalInformation_qulification_details_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _bt_registration_lecture_personalInformation_qulification_details_add.setForeground(new java.awt.Color(255, 255, 255));
        _bt_registration_lecture_personalInformation_qulification_details_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/buton_blue_200x50.png"))); // NOI18N
        _bt_registration_lecture_personalInformation_qulification_details_add.setText("Add");
        _bt_registration_lecture_personalInformation_qulification_details_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _bt_registration_lecture_personalInformation_qulification_details_add.setFocusPainted(false);
        _bt_registration_lecture_personalInformation_qulification_details_add.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _bt_registration_lecture_personalInformation_qulification_details_add.setPreferredSize(new java.awt.Dimension(300, 50));
        _bt_registration_lecture_personalInformation_qulification_details_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _bt_registration_lecture_personalInformation_qulification_details_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _bt_registration_lecture_personalInformation_qulification_details_addMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _bt_registration_lecture_personalInformation_qulification_details_addMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                _bt_registration_lecture_personalInformation_qulification_details_addMouseReleased(evt);
            }
        });
        _pl_registration_lecture_personalInformation_qulifications_details.add(_bt_registration_lecture_personalInformation_qulification_details_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 482, 200, -1));

        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_year1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_year1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_personalInformations_lectureDetails_qulifications_year1ActionPerformed(evt);
            }
        });
        _pl_registration_lecture_personalInformation_qulifications_details.add(_tf_registration_lecture_personalInformations_lectureDetails_qulifications_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 431, 115, 40));

        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_year2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_personalInformations_lectureDetails_qulifications_year2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_personalInformations_lectureDetails_qulifications_year2ActionPerformed(evt);
            }
        });
        _pl_registration_lecture_personalInformation_qulifications_details.add(_tf_registration_lecture_personalInformations_lectureDetails_qulifications_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 431, 200, 40));

        _bt_registration_lecture_personalInformation_qulification_details_add1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _bt_registration_lecture_personalInformation_qulification_details_add1.setForeground(new java.awt.Color(255, 255, 255));
        _bt_registration_lecture_personalInformation_qulification_details_add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/buton_blue_200x50.png"))); // NOI18N
        _bt_registration_lecture_personalInformation_qulification_details_add1.setText("Add");
        _bt_registration_lecture_personalInformation_qulification_details_add1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _bt_registration_lecture_personalInformation_qulification_details_add1.setFocusPainted(false);
        _bt_registration_lecture_personalInformation_qulification_details_add1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _bt_registration_lecture_personalInformation_qulification_details_add1.setPreferredSize(new java.awt.Dimension(300, 50));
        _bt_registration_lecture_personalInformation_qulification_details_add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _bt_registration_lecture_personalInformation_qulification_details_add1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _bt_registration_lecture_personalInformation_qulification_details_add1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _bt_registration_lecture_personalInformation_qulification_details_add1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                _bt_registration_lecture_personalInformation_qulification_details_add1MouseReleased(evt);
            }
        });
        _pl_registration_lecture_personalInformation_qulifications_details.add(_bt_registration_lecture_personalInformation_qulification_details_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 311, 200, -1));

        _lb_registration_lecture_personalInformation_lectureName_sirName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_personalInformation_lectureName_sirName1.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_personalInformation_lectureName_sirName1.setText("Subject");
        _pl_registration_lecture_personalInformation_qulifications_details.add(_lb_registration_lecture_personalInformation_lectureName_sirName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 408, 123, -1));

        _lb_registration_lecture_personalInformation_lectureName_sirName2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_personalInformation_lectureName_sirName2.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_personalInformation_lectureName_sirName2.setText("Result");
        _pl_registration_lecture_personalInformation_qulifications_details.add(_lb_registration_lecture_personalInformation_lectureName_sirName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 408, 115, -1));

        jRadioButton1.setBackground(new java.awt.Color(2, 119, 189));
        _bg_lecture_qulification_ol_al.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("O/L Results");
        _pl_registration_lecture_personalInformation_qulifications_details.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 376, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(2, 119, 189));
        _bg_lecture_qulification_ol_al.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("A/L Results");
        _pl_registration_lecture_personalInformation_qulifications_details.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 376, -1, -1));

        _pl_registration_lecture_personalInformation_qulifications.add(_pl_registration_lecture_personalInformation_qulifications_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 365, 550));

        _pl_registration_lecture_personalInformation_qulifications_preview.setBackground(new java.awt.Color(2, 119, 189));
        _pl_registration_lecture_personalInformation_qulifications_preview.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Qulifications Preview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        _bt_registration_lecture_personalInformation_qulification_preview_remove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _bt_registration_lecture_personalInformation_qulification_preview_remove.setForeground(new java.awt.Color(255, 255, 255));
        _bt_registration_lecture_personalInformation_qulification_preview_remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/buton_blue_200x50.png"))); // NOI18N
        _bt_registration_lecture_personalInformation_qulification_preview_remove.setText("Remove");
        _bt_registration_lecture_personalInformation_qulification_preview_remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _bt_registration_lecture_personalInformation_qulification_preview_remove.setFocusPainted(false);
        _bt_registration_lecture_personalInformation_qulification_preview_remove.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _bt_registration_lecture_personalInformation_qulification_preview_remove.setPreferredSize(new java.awt.Dimension(300, 50));
        _bt_registration_lecture_personalInformation_qulification_preview_remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _bt_registration_lecture_personalInformation_qulification_preview_removeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _bt_registration_lecture_personalInformation_qulification_preview_removeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _bt_registration_lecture_personalInformation_qulification_preview_removeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                _bt_registration_lecture_personalInformation_qulification_preview_removeMouseReleased(evt);
            }
        });

        _bt_registration_lecture_personalInformation_qulification_preview_update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _bt_registration_lecture_personalInformation_qulification_preview_update.setForeground(new java.awt.Color(255, 255, 255));
        _bt_registration_lecture_personalInformation_qulification_preview_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/buton_blue_200x50.png"))); // NOI18N
        _bt_registration_lecture_personalInformation_qulification_preview_update.setText("Update");
        _bt_registration_lecture_personalInformation_qulification_preview_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _bt_registration_lecture_personalInformation_qulification_preview_update.setFocusPainted(false);
        _bt_registration_lecture_personalInformation_qulification_preview_update.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _bt_registration_lecture_personalInformation_qulification_preview_update.setPreferredSize(new java.awt.Dimension(300, 50));
        _bt_registration_lecture_personalInformation_qulification_preview_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _bt_registration_lecture_personalInformation_qulification_preview_updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _bt_registration_lecture_personalInformation_qulification_preview_updateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _bt_registration_lecture_personalInformation_qulification_preview_updateMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                _bt_registration_lecture_personalInformation_qulification_preview_updateMouseReleased(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());
        jPanel1.add(_tp_registration_lecture_qulifications_tables, "card2");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/button_blue_300x50.png"))); // NOI18N
        jButton1.setText("Finish");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout _pl_registration_lecture_personalInformation_qulifications_previewLayout = new javax.swing.GroupLayout(_pl_registration_lecture_personalInformation_qulifications_preview);
        _pl_registration_lecture_personalInformation_qulifications_preview.setLayout(_pl_registration_lecture_personalInformation_qulifications_previewLayout);
        _pl_registration_lecture_personalInformation_qulifications_previewLayout.setHorizontalGroup(
            _pl_registration_lecture_personalInformation_qulifications_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pl_registration_lecture_personalInformation_qulifications_previewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_bt_registration_lecture_personalInformation_qulification_preview_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(_bt_registration_lecture_personalInformation_qulification_preview_update, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(_pl_registration_lecture_personalInformation_qulifications_previewLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        _pl_registration_lecture_personalInformation_qulifications_previewLayout.setVerticalGroup(
            _pl_registration_lecture_personalInformation_qulifications_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _pl_registration_lecture_personalInformation_qulifications_previewLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(_pl_registration_lecture_personalInformation_qulifications_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_bt_registration_lecture_personalInformation_qulification_preview_remove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_bt_registration_lecture_personalInformation_qulification_preview_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        _pl_registration_lecture_personalInformation_qulifications.add(_pl_registration_lecture_personalInformation_qulifications_preview, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 450, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_pl_registration_lecture_personalInformation_qulifications, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_pl_registration_lecture_personalInformation_qulifications, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void _tf_registration_lecture_personalInformations_lectureDetails_qulifications_fileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_personalInformations_lectureDetails_qulifications_fileNoActionPerformed
        
    }//GEN-LAST:event__tf_registration_lecture_personalInformations_lectureDetails_qulifications_fileNoActionPerformed

    private void _tf_registration_lecture_personalInformations_lectureDetails_qulifications_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_personalInformations_lectureDetails_qulifications_nameActionPerformed
        
    }//GEN-LAST:event__tf_registration_lecture_personalInformations_lectureDetails_qulifications_nameActionPerformed

    private void _tf_registration_lecture_personalInformations_lectureDetails_qulifications_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_personalInformations_lectureDetails_qulifications_typeActionPerformed
        
    }//GEN-LAST:event__tf_registration_lecture_personalInformations_lectureDetails_qulifications_typeActionPerformed

    private void _tf_registration_lecture_personalInformations_lectureDetails_qulifications_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_personalInformations_lectureDetails_qulifications_yearActionPerformed
        
    }//GEN-LAST:event__tf_registration_lecture_personalInformations_lectureDetails_qulifications_yearActionPerformed

    private void _bt_registration_lecture_personalInformation_qulification_details_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_registration_lecture_personalInformation_qulification_details_addMouseEntered
        _bt_registration_lecture_personalInformation_qulification_details_add.setBorder(border);
    }//GEN-LAST:event__bt_registration_lecture_personalInformation_qulification_details_addMouseEntered

    private void _bt_registration_lecture_personalInformation_qulification_details_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_registration_lecture_personalInformation_qulification_details_addMouseExited
        _bt_registration_lecture_personalInformation_qulification_details_add.setBorder(null);
    }//GEN-LAST:event__bt_registration_lecture_personalInformation_qulification_details_addMouseExited

    private void _bt_registration_lecture_personalInformation_qulification_details_addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_registration_lecture_personalInformation_qulification_details_addMousePressed
        _bt_registration_lecture_personalInformation_qulification_details_add.setBorder(null);
    }//GEN-LAST:event__bt_registration_lecture_personalInformation_qulification_details_addMousePressed

    private void _bt_registration_lecture_personalInformation_qulification_details_addMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_registration_lecture_personalInformation_qulification_details_addMouseReleased
        _bt_registration_lecture_personalInformation_qulification_details_add.setBorder(border);
    }//GEN-LAST:event__bt_registration_lecture_personalInformation_qulification_details_addMouseReleased

    private void _bt_registration_lecture_personalInformation_qulification_preview_removeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_registration_lecture_personalInformation_qulification_preview_removeMouseEntered
        _bt_registration_lecture_personalInformation_qulification_preview_remove.setBorder(border);
    }//GEN-LAST:event__bt_registration_lecture_personalInformation_qulification_preview_removeMouseEntered

    private void _bt_registration_lecture_personalInformation_qulification_preview_removeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_registration_lecture_personalInformation_qulification_preview_removeMouseExited
        _bt_registration_lecture_personalInformation_qulification_preview_remove.setBorder(null);
    }//GEN-LAST:event__bt_registration_lecture_personalInformation_qulification_preview_removeMouseExited

    private void _bt_registration_lecture_personalInformation_qulification_preview_removeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_registration_lecture_personalInformation_qulification_preview_removeMousePressed
        _bt_registration_lecture_personalInformation_qulification_preview_remove.setBorder(null);
    }//GEN-LAST:event__bt_registration_lecture_personalInformation_qulification_preview_removeMousePressed

    private void _bt_registration_lecture_personalInformation_qulification_preview_removeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_registration_lecture_personalInformation_qulification_preview_removeMouseReleased
        _bt_registration_lecture_personalInformation_qulification_preview_remove.setBorder(border);
    }//GEN-LAST:event__bt_registration_lecture_personalInformation_qulification_preview_removeMouseReleased

    private void _bt_registration_lecture_personalInformation_qulification_preview_updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_registration_lecture_personalInformation_qulification_preview_updateMouseEntered
        _bt_registration_lecture_personalInformation_qulification_preview_update.setBorder(border);
    }//GEN-LAST:event__bt_registration_lecture_personalInformation_qulification_preview_updateMouseEntered

    private void _bt_registration_lecture_personalInformation_qulification_preview_updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_registration_lecture_personalInformation_qulification_preview_updateMouseExited
        _bt_registration_lecture_personalInformation_qulification_preview_update.setBorder(null);
    }//GEN-LAST:event__bt_registration_lecture_personalInformation_qulification_preview_updateMouseExited

    private void _bt_registration_lecture_personalInformation_qulification_preview_updateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_registration_lecture_personalInformation_qulification_preview_updateMousePressed
        _bt_registration_lecture_personalInformation_qulification_preview_update.setBorder(null);
    }//GEN-LAST:event__bt_registration_lecture_personalInformation_qulification_preview_updateMousePressed

    private void _bt_registration_lecture_personalInformation_qulification_preview_updateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_registration_lecture_personalInformation_qulification_preview_updateMouseReleased
        _bt_registration_lecture_personalInformation_qulification_preview_update.setBorder(border);
    }//GEN-LAST:event__bt_registration_lecture_personalInformation_qulification_preview_updateMouseReleased

    private void _tf_registration_lecture_personalInformations_lectureDetails_qulifications_year1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_personalInformations_lectureDetails_qulifications_year1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__tf_registration_lecture_personalInformations_lectureDetails_qulifications_year1ActionPerformed

    private void _tf_registration_lecture_personalInformations_lectureDetails_qulifications_year2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_personalInformations_lectureDetails_qulifications_year2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__tf_registration_lecture_personalInformations_lectureDetails_qulifications_year2ActionPerformed

    private void _bt_registration_lecture_personalInformation_qulification_details_add1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_registration_lecture_personalInformation_qulification_details_add1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event__bt_registration_lecture_personalInformation_qulification_details_add1MouseEntered

    private void _bt_registration_lecture_personalInformation_qulification_details_add1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_registration_lecture_personalInformation_qulification_details_add1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event__bt_registration_lecture_personalInformation_qulification_details_add1MouseExited

    private void _bt_registration_lecture_personalInformation_qulification_details_add1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_registration_lecture_personalInformation_qulification_details_add1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event__bt_registration_lecture_personalInformation_qulification_details_add1MousePressed

    private void _bt_registration_lecture_personalInformation_qulification_details_add1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_registration_lecture_personalInformation_qulification_details_add1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event__bt_registration_lecture_personalInformation_qulification_details_add1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup _bg_lecture_qulification_ol_al;
    private javax.swing.JButton _bt_registration_lecture_personalInformation_qulification_details_add;
    private javax.swing.JButton _bt_registration_lecture_personalInformation_qulification_details_add1;
    private javax.swing.JButton _bt_registration_lecture_personalInformation_qulification_preview_remove;
    private javax.swing.JButton _bt_registration_lecture_personalInformation_qulification_preview_update;
    private javax.swing.JLabel _lb_registration_lecture_personalInformation_idInformation_nicNumber;
    private javax.swing.JLabel _lb_registration_lecture_personalInformation_lectureName_firstName;
    private javax.swing.JLabel _lb_registration_lecture_personalInformation_lectureName_lastName;
    private javax.swing.JLabel _lb_registration_lecture_personalInformation_lectureName_sirName;
    private javax.swing.JLabel _lb_registration_lecture_personalInformation_lectureName_sirName1;
    private javax.swing.JLabel _lb_registration_lecture_personalInformation_lectureName_sirName2;
    private javax.swing.JPanel _pl_registration_lecture_personalInformation_qulifications;
    private javax.swing.JPanel _pl_registration_lecture_personalInformation_qulifications_details;
    private javax.swing.JPanel _pl_registration_lecture_personalInformation_qulifications_preview;
    private javax.swing.JTextField _tf_registration_lecture_personalInformations_lectureDetails_qulifications_fileNo;
    private javax.swing.JTextField _tf_registration_lecture_personalInformations_lectureDetails_qulifications_name;
    private javax.swing.JTextField _tf_registration_lecture_personalInformations_lectureDetails_qulifications_type;
    private javax.swing.JTextField _tf_registration_lecture_personalInformations_lectureDetails_qulifications_year;
    private javax.swing.JTextField _tf_registration_lecture_personalInformations_lectureDetails_qulifications_year1;
    private javax.swing.JTextField _tf_registration_lecture_personalInformations_lectureDetails_qulifications_year2;
    private javax.swing.JTabbedPane _tp_registration_lecture_qulifications_tables;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
