package hb_models;
// Generated Jan 21, 2018 10:14:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmployeeNonAcademicUserInfoAddress generated by hbm2java
 */
@Entity
@Table(name="employee_nonAcademic_user_info_address"
    ,catalog="safenets_ramani"
)
public class EmployeeNonAcademicUserInfoAddress  implements java.io.Serializable {


     private Integer idemployeeNonAcademicUserInfoAddress;
     private String employeeNonAcademicAdministrativeUserInfoId;
     private String employeeNonAcademicUserInfoAddressLane1;
     private String employeeNonAcademicUserInfoAddressCity;
     private String employeeNonAcademicUserInfoAddressCuntry;

    public EmployeeNonAcademicUserInfoAddress() {
    }

    public EmployeeNonAcademicUserInfoAddress(String employeeNonAcademicAdministrativeUserInfoId, String employeeNonAcademicUserInfoAddressLane1, String employeeNonAcademicUserInfoAddressCity, String employeeNonAcademicUserInfoAddressCuntry) {
       this.employeeNonAcademicAdministrativeUserInfoId = employeeNonAcademicAdministrativeUserInfoId;
       this.employeeNonAcademicUserInfoAddressLane1 = employeeNonAcademicUserInfoAddressLane1;
       this.employeeNonAcademicUserInfoAddressCity = employeeNonAcademicUserInfoAddressCity;
       this.employeeNonAcademicUserInfoAddressCuntry = employeeNonAcademicUserInfoAddressCuntry;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idemployee_nonAcademic_user_info_address", unique=true, nullable=false)
    public Integer getIdemployeeNonAcademicUserInfoAddress() {
        return this.idemployeeNonAcademicUserInfoAddress;
    }
    
    public void setIdemployeeNonAcademicUserInfoAddress(Integer idemployeeNonAcademicUserInfoAddress) {
        this.idemployeeNonAcademicUserInfoAddress = idemployeeNonAcademicUserInfoAddress;
    }

    
    @Column(name="employee_nonAcademic_administrative_user_info_id", length=50)
    public String getEmployeeNonAcademicAdministrativeUserInfoId() {
        return this.employeeNonAcademicAdministrativeUserInfoId;
    }
    
    public void setEmployeeNonAcademicAdministrativeUserInfoId(String employeeNonAcademicAdministrativeUserInfoId) {
        this.employeeNonAcademicAdministrativeUserInfoId = employeeNonAcademicAdministrativeUserInfoId;
    }

    
    @Column(name="employee_nonAcademic_user_info_address_lane1")
    public String getEmployeeNonAcademicUserInfoAddressLane1() {
        return this.employeeNonAcademicUserInfoAddressLane1;
    }
    
    public void setEmployeeNonAcademicUserInfoAddressLane1(String employeeNonAcademicUserInfoAddressLane1) {
        this.employeeNonAcademicUserInfoAddressLane1 = employeeNonAcademicUserInfoAddressLane1;
    }

    
    @Column(name="employee_nonAcademic_user_info_address_city", length=45)
    public String getEmployeeNonAcademicUserInfoAddressCity() {
        return this.employeeNonAcademicUserInfoAddressCity;
    }
    
    public void setEmployeeNonAcademicUserInfoAddressCity(String employeeNonAcademicUserInfoAddressCity) {
        this.employeeNonAcademicUserInfoAddressCity = employeeNonAcademicUserInfoAddressCity;
    }

    
    @Column(name="employee_nonAcademic_user_info_address_cuntry", length=45)
    public String getEmployeeNonAcademicUserInfoAddressCuntry() {
        return this.employeeNonAcademicUserInfoAddressCuntry;
    }
    
    public void setEmployeeNonAcademicUserInfoAddressCuntry(String employeeNonAcademicUserInfoAddressCuntry) {
        this.employeeNonAcademicUserInfoAddressCuntry = employeeNonAcademicUserInfoAddressCuntry;
    }




}


