package hb_models;
// Generated Jan 21, 2018 10:14:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmployeeNonAcademicUserInfoName generated by hbm2java
 */
@Entity
@Table(name="employee_nonAcademic_user_info_name"
    ,catalog="safenets_ramani"
)
public class EmployeeNonAcademicUserInfoName  implements java.io.Serializable {


     private Integer idemployeeNonAcademicUserInfoName;
     private String employeeNonAcademicAdministrativeUserInfoId;
     private String employeeNonAcademicUserInfoNameSirName;
     private String employeeNonAcademicUserInfoNameFirstName;
     private String employeeNonAcademicUserInfoNameLastName;

    public EmployeeNonAcademicUserInfoName() {
    }

    public EmployeeNonAcademicUserInfoName(String employeeNonAcademicAdministrativeUserInfoId, String employeeNonAcademicUserInfoNameSirName, String employeeNonAcademicUserInfoNameFirstName, String employeeNonAcademicUserInfoNameLastName) {
       this.employeeNonAcademicAdministrativeUserInfoId = employeeNonAcademicAdministrativeUserInfoId;
       this.employeeNonAcademicUserInfoNameSirName = employeeNonAcademicUserInfoNameSirName;
       this.employeeNonAcademicUserInfoNameFirstName = employeeNonAcademicUserInfoNameFirstName;
       this.employeeNonAcademicUserInfoNameLastName = employeeNonAcademicUserInfoNameLastName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idemployee_nonAcademic_user_info_name", unique=true, nullable=false)
    public Integer getIdemployeeNonAcademicUserInfoName() {
        return this.idemployeeNonAcademicUserInfoName;
    }
    
    public void setIdemployeeNonAcademicUserInfoName(Integer idemployeeNonAcademicUserInfoName) {
        this.idemployeeNonAcademicUserInfoName = idemployeeNonAcademicUserInfoName;
    }

    
    @Column(name="employee_nonAcademic_administrative_user_info_id", length=50)
    public String getEmployeeNonAcademicAdministrativeUserInfoId() {
        return this.employeeNonAcademicAdministrativeUserInfoId;
    }
    
    public void setEmployeeNonAcademicAdministrativeUserInfoId(String employeeNonAcademicAdministrativeUserInfoId) {
        this.employeeNonAcademicAdministrativeUserInfoId = employeeNonAcademicAdministrativeUserInfoId;
    }

    
    @Column(name="employee_nonAcademic_user_info_name_sirName")
    public String getEmployeeNonAcademicUserInfoNameSirName() {
        return this.employeeNonAcademicUserInfoNameSirName;
    }
    
    public void setEmployeeNonAcademicUserInfoNameSirName(String employeeNonAcademicUserInfoNameSirName) {
        this.employeeNonAcademicUserInfoNameSirName = employeeNonAcademicUserInfoNameSirName;
    }

    
    @Column(name="employee_nonAcademic_user_info_name_first_name")
    public String getEmployeeNonAcademicUserInfoNameFirstName() {
        return this.employeeNonAcademicUserInfoNameFirstName;
    }
    
    public void setEmployeeNonAcademicUserInfoNameFirstName(String employeeNonAcademicUserInfoNameFirstName) {
        this.employeeNonAcademicUserInfoNameFirstName = employeeNonAcademicUserInfoNameFirstName;
    }

    
    @Column(name="employee_nonAcademic_user_info_name_last_name")
    public String getEmployeeNonAcademicUserInfoNameLastName() {
        return this.employeeNonAcademicUserInfoNameLastName;
    }
    
    public void setEmployeeNonAcademicUserInfoNameLastName(String employeeNonAcademicUserInfoNameLastName) {
        this.employeeNonAcademicUserInfoNameLastName = employeeNonAcademicUserInfoNameLastName;
    }




}


