package hb_models;
// Generated Jan 21, 2018 10:14:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmployeeNonAcademicAdministrativeUserStatus generated by hbm2java
 */
@Entity
@Table(name="employee_nonAcademic_administrative_user_status"
    ,catalog="safenets_ramani"
)
public class EmployeeNonAcademicAdministrativeUserStatus  implements java.io.Serializable {


     private Integer idemployeeNonAcademicAdministrativeUserStatus;
     private Integer employeeNonAcademicAdministrativeUserStatusCode;
     private String employeeNonAcademicAdministrativeUserStatusName;
     private String employeeNonAcademicAdministrativeUserInfoId;

    public EmployeeNonAcademicAdministrativeUserStatus() {
    }

    public EmployeeNonAcademicAdministrativeUserStatus(Integer employeeNonAcademicAdministrativeUserStatusCode, String employeeNonAcademicAdministrativeUserStatusName, String employeeNonAcademicAdministrativeUserInfoId) {
       this.employeeNonAcademicAdministrativeUserStatusCode = employeeNonAcademicAdministrativeUserStatusCode;
       this.employeeNonAcademicAdministrativeUserStatusName = employeeNonAcademicAdministrativeUserStatusName;
       this.employeeNonAcademicAdministrativeUserInfoId = employeeNonAcademicAdministrativeUserInfoId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idemployee_nonAcademic_administrative_user_status", unique=true, nullable=false)
    public Integer getIdemployeeNonAcademicAdministrativeUserStatus() {
        return this.idemployeeNonAcademicAdministrativeUserStatus;
    }
    
    public void setIdemployeeNonAcademicAdministrativeUserStatus(Integer idemployeeNonAcademicAdministrativeUserStatus) {
        this.idemployeeNonAcademicAdministrativeUserStatus = idemployeeNonAcademicAdministrativeUserStatus;
    }

    
    @Column(name="employee_nonAcademic_administrative_user_status_code")
    public Integer getEmployeeNonAcademicAdministrativeUserStatusCode() {
        return this.employeeNonAcademicAdministrativeUserStatusCode;
    }
    
    public void setEmployeeNonAcademicAdministrativeUserStatusCode(Integer employeeNonAcademicAdministrativeUserStatusCode) {
        this.employeeNonAcademicAdministrativeUserStatusCode = employeeNonAcademicAdministrativeUserStatusCode;
    }

    
    @Column(name="employee_nonAcademic_administrative_user_status_name", length=50)
    public String getEmployeeNonAcademicAdministrativeUserStatusName() {
        return this.employeeNonAcademicAdministrativeUserStatusName;
    }
    
    public void setEmployeeNonAcademicAdministrativeUserStatusName(String employeeNonAcademicAdministrativeUserStatusName) {
        this.employeeNonAcademicAdministrativeUserStatusName = employeeNonAcademicAdministrativeUserStatusName;
    }

    
    @Column(name="employee_nonAcademic_administrative_user_info_id", length=50)
    public String getEmployeeNonAcademicAdministrativeUserInfoId() {
        return this.employeeNonAcademicAdministrativeUserInfoId;
    }
    
    public void setEmployeeNonAcademicAdministrativeUserInfoId(String employeeNonAcademicAdministrativeUserInfoId) {
        this.employeeNonAcademicAdministrativeUserInfoId = employeeNonAcademicAdministrativeUserInfoId;
    }




}


