package hb_models;
// Generated Jan 21, 2018 10:14:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeNonAcademicUserInfoPersonal generated by hbm2java
 */
@Entity
@Table(name="employee_nonAcademic_user_info_personal"
    ,catalog="safenets_ramani"
)
public class EmployeeNonAcademicUserInfoPersonal  implements java.io.Serializable {


     private Integer idemployeeNonAcademicUserInfoPersonal;
     private String employeeNonAcademicAdministrativeUserInfoId;
     private String employeeNonAcademicUserInfoPersonalProfileImage;
     private Date employeeNonAcademicUserInfoPersonalDob;
     private String employeeNonAcademicUserInfoPersonalGender;

    public EmployeeNonAcademicUserInfoPersonal() {
    }

    public EmployeeNonAcademicUserInfoPersonal(String employeeNonAcademicAdministrativeUserInfoId, String employeeNonAcademicUserInfoPersonalProfileImage, Date employeeNonAcademicUserInfoPersonalDob, String employeeNonAcademicUserInfoPersonalGender) {
       this.employeeNonAcademicAdministrativeUserInfoId = employeeNonAcademicAdministrativeUserInfoId;
       this.employeeNonAcademicUserInfoPersonalProfileImage = employeeNonAcademicUserInfoPersonalProfileImage;
       this.employeeNonAcademicUserInfoPersonalDob = employeeNonAcademicUserInfoPersonalDob;
       this.employeeNonAcademicUserInfoPersonalGender = employeeNonAcademicUserInfoPersonalGender;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idemployee_nonAcademic_user_info_personal", unique=true, nullable=false)
    public Integer getIdemployeeNonAcademicUserInfoPersonal() {
        return this.idemployeeNonAcademicUserInfoPersonal;
    }
    
    public void setIdemployeeNonAcademicUserInfoPersonal(Integer idemployeeNonAcademicUserInfoPersonal) {
        this.idemployeeNonAcademicUserInfoPersonal = idemployeeNonAcademicUserInfoPersonal;
    }

    
    @Column(name="employee_nonAcademic_administrative_user_info_id", length=50)
    public String getEmployeeNonAcademicAdministrativeUserInfoId() {
        return this.employeeNonAcademicAdministrativeUserInfoId;
    }
    
    public void setEmployeeNonAcademicAdministrativeUserInfoId(String employeeNonAcademicAdministrativeUserInfoId) {
        this.employeeNonAcademicAdministrativeUserInfoId = employeeNonAcademicAdministrativeUserInfoId;
    }

    
    @Column(name="employee_nonAcademic_user_info_personal_profile_image")
    public String getEmployeeNonAcademicUserInfoPersonalProfileImage() {
        return this.employeeNonAcademicUserInfoPersonalProfileImage;
    }
    
    public void setEmployeeNonAcademicUserInfoPersonalProfileImage(String employeeNonAcademicUserInfoPersonalProfileImage) {
        this.employeeNonAcademicUserInfoPersonalProfileImage = employeeNonAcademicUserInfoPersonalProfileImage;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="employee_nonAcademic_user_info_personal_dob", length=10)
    public Date getEmployeeNonAcademicUserInfoPersonalDob() {
        return this.employeeNonAcademicUserInfoPersonalDob;
    }
    
    public void setEmployeeNonAcademicUserInfoPersonalDob(Date employeeNonAcademicUserInfoPersonalDob) {
        this.employeeNonAcademicUserInfoPersonalDob = employeeNonAcademicUserInfoPersonalDob;
    }

    
    @Column(name="employee_nonAcademic_user_info_personal_gender", length=10)
    public String getEmployeeNonAcademicUserInfoPersonalGender() {
        return this.employeeNonAcademicUserInfoPersonalGender;
    }
    
    public void setEmployeeNonAcademicUserInfoPersonalGender(String employeeNonAcademicUserInfoPersonalGender) {
        this.employeeNonAcademicUserInfoPersonalGender = employeeNonAcademicUserInfoPersonalGender;
    }




}


