package hb_models;
// Generated Jan 21, 2018 10:14:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StuInfoPersonal generated by hbm2java
 */
@Entity
@Table(name="stu_info_personal"
    ,catalog="safenets_ramani"
)
public class StuInfoPersonal  implements java.io.Serializable {


     private Integer idstuInfoPersonal;
     private String stuUserInfoId;
     private String stuInfoPersonalProfileImage;
     private String stuInfoPersonalNic;
     private Date stuInfoPersonalDob;
     private String stuInfoPersonalBranch;
     private String stuInfoPersonalGender;
     private String stuInfoPersonalCourse;

    public StuInfoPersonal() {
    }

    public StuInfoPersonal(String stuUserInfoId, String stuInfoPersonalProfileImage, String stuInfoPersonalNic, Date stuInfoPersonalDob, String stuInfoPersonalBranch, String stuInfoPersonalGender, String stuInfoPersonalCourse) {
       this.stuUserInfoId = stuUserInfoId;
       this.stuInfoPersonalProfileImage = stuInfoPersonalProfileImage;
       this.stuInfoPersonalNic = stuInfoPersonalNic;
       this.stuInfoPersonalDob = stuInfoPersonalDob;
       this.stuInfoPersonalBranch = stuInfoPersonalBranch;
       this.stuInfoPersonalGender = stuInfoPersonalGender;
       this.stuInfoPersonalCourse = stuInfoPersonalCourse;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idstu_info_personal", unique=true, nullable=false)
    public Integer getIdstuInfoPersonal() {
        return this.idstuInfoPersonal;
    }
    
    public void setIdstuInfoPersonal(Integer idstuInfoPersonal) {
        this.idstuInfoPersonal = idstuInfoPersonal;
    }

    
    @Column(name="stu_user_info_id", length=50)
    public String getStuUserInfoId() {
        return this.stuUserInfoId;
    }
    
    public void setStuUserInfoId(String stuUserInfoId) {
        this.stuUserInfoId = stuUserInfoId;
    }

    
    @Column(name="stu_info_personal_profile_image")
    public String getStuInfoPersonalProfileImage() {
        return this.stuInfoPersonalProfileImage;
    }
    
    public void setStuInfoPersonalProfileImage(String stuInfoPersonalProfileImage) {
        this.stuInfoPersonalProfileImage = stuInfoPersonalProfileImage;
    }

    
    @Column(name="stu_info_personal_nic", length=10)
    public String getStuInfoPersonalNic() {
        return this.stuInfoPersonalNic;
    }
    
    public void setStuInfoPersonalNic(String stuInfoPersonalNic) {
        this.stuInfoPersonalNic = stuInfoPersonalNic;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="stu_info_personal_dob", length=10)
    public Date getStuInfoPersonalDob() {
        return this.stuInfoPersonalDob;
    }
    
    public void setStuInfoPersonalDob(Date stuInfoPersonalDob) {
        this.stuInfoPersonalDob = stuInfoPersonalDob;
    }

    
    @Column(name="stu_info_personal_branch", length=10)
    public String getStuInfoPersonalBranch() {
        return this.stuInfoPersonalBranch;
    }
    
    public void setStuInfoPersonalBranch(String stuInfoPersonalBranch) {
        this.stuInfoPersonalBranch = stuInfoPersonalBranch;
    }

    
    @Column(name="stu_info_personal_gender", length=10)
    public String getStuInfoPersonalGender() {
        return this.stuInfoPersonalGender;
    }
    
    public void setStuInfoPersonalGender(String stuInfoPersonalGender) {
        this.stuInfoPersonalGender = stuInfoPersonalGender;
    }

    
    @Column(name="stu_info_personal_course", length=100)
    public String getStuInfoPersonalCourse() {
        return this.stuInfoPersonalCourse;
    }
    
    public void setStuInfoPersonalCourse(String stuInfoPersonalCourse) {
        this.stuInfoPersonalCourse = stuInfoPersonalCourse;
    }




}


