package hb_models;
// Generated Jan 21, 2018 10:14:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StuInfoAditionalQulifications generated by hbm2java
 */
@Entity
@Table(name="stu_info_aditional_qulifications"
    ,catalog="safenets_ramani"
)
public class StuInfoAditionalQulifications  implements java.io.Serializable {


     private Integer idstuInfoAditionalQulifications;
     private String stuUserInfoId;
     private String stuInfoAditionalQulificationsFileId;
     private String stuInfoAditionalQulificationsName;
     private String stuInfoAditionalQulificationsType;
     private Date stuInfoAditionalQulificationsYear;

    public StuInfoAditionalQulifications() {
    }

    public StuInfoAditionalQulifications(String stuUserInfoId, String stuInfoAditionalQulificationsFileId, String stuInfoAditionalQulificationsName, String stuInfoAditionalQulificationsType, Date stuInfoAditionalQulificationsYear) {
       this.stuUserInfoId = stuUserInfoId;
       this.stuInfoAditionalQulificationsFileId = stuInfoAditionalQulificationsFileId;
       this.stuInfoAditionalQulificationsName = stuInfoAditionalQulificationsName;
       this.stuInfoAditionalQulificationsType = stuInfoAditionalQulificationsType;
       this.stuInfoAditionalQulificationsYear = stuInfoAditionalQulificationsYear;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idstu_info_aditional_qulifications", unique=true, nullable=false)
    public Integer getIdstuInfoAditionalQulifications() {
        return this.idstuInfoAditionalQulifications;
    }
    
    public void setIdstuInfoAditionalQulifications(Integer idstuInfoAditionalQulifications) {
        this.idstuInfoAditionalQulifications = idstuInfoAditionalQulifications;
    }

    
    @Column(name="stu_user_info_id", length=50)
    public String getStuUserInfoId() {
        return this.stuUserInfoId;
    }
    
    public void setStuUserInfoId(String stuUserInfoId) {
        this.stuUserInfoId = stuUserInfoId;
    }

    
    @Column(name="stu_info_aditional_qulifications_file_id", length=50)
    public String getStuInfoAditionalQulificationsFileId() {
        return this.stuInfoAditionalQulificationsFileId;
    }
    
    public void setStuInfoAditionalQulificationsFileId(String stuInfoAditionalQulificationsFileId) {
        this.stuInfoAditionalQulificationsFileId = stuInfoAditionalQulificationsFileId;
    }

    
    @Column(name="stu_info_aditional_qulifications_name", length=16777215)
    public String getStuInfoAditionalQulificationsName() {
        return this.stuInfoAditionalQulificationsName;
    }
    
    public void setStuInfoAditionalQulificationsName(String stuInfoAditionalQulificationsName) {
        this.stuInfoAditionalQulificationsName = stuInfoAditionalQulificationsName;
    }

    
    @Column(name="stu_info_aditional_qulifications_type", length=50)
    public String getStuInfoAditionalQulificationsType() {
        return this.stuInfoAditionalQulificationsType;
    }
    
    public void setStuInfoAditionalQulificationsType(String stuInfoAditionalQulificationsType) {
        this.stuInfoAditionalQulificationsType = stuInfoAditionalQulificationsType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="stu_info_aditional_qulifications_year", length=19)
    public Date getStuInfoAditionalQulificationsYear() {
        return this.stuInfoAditionalQulificationsYear;
    }
    
    public void setStuInfoAditionalQulificationsYear(Date stuInfoAditionalQulificationsYear) {
        this.stuInfoAditionalQulificationsYear = stuInfoAditionalQulificationsYear;
    }




}


