package hb_models;
// Generated Jan 21, 2018 10:14:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StuInfoName generated by hbm2java
 */
@Entity
@Table(name="stu_info_name"
    ,catalog="safenets_ramani"
)
public class StuInfoName  implements java.io.Serializable {


     private Integer idstuInfoName;
     private String stuUserInfoId;
     private String stuInfoNameSirName;
     private String stuInfoNameFirstName;
     private String stuInfoNameLastName;

    public StuInfoName() {
    }

    public StuInfoName(String stuUserInfoId, String stuInfoNameSirName, String stuInfoNameFirstName, String stuInfoNameLastName) {
       this.stuUserInfoId = stuUserInfoId;
       this.stuInfoNameSirName = stuInfoNameSirName;
       this.stuInfoNameFirstName = stuInfoNameFirstName;
       this.stuInfoNameLastName = stuInfoNameLastName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idstu_info_name", unique=true, nullable=false)
    public Integer getIdstuInfoName() {
        return this.idstuInfoName;
    }
    
    public void setIdstuInfoName(Integer idstuInfoName) {
        this.idstuInfoName = idstuInfoName;
    }

    
    @Column(name="stu_user_info_id", length=50)
    public String getStuUserInfoId() {
        return this.stuUserInfoId;
    }
    
    public void setStuUserInfoId(String stuUserInfoId) {
        this.stuUserInfoId = stuUserInfoId;
    }

    
    @Column(name="stu_info_name_sirName")
    public String getStuInfoNameSirName() {
        return this.stuInfoNameSirName;
    }
    
    public void setStuInfoNameSirName(String stuInfoNameSirName) {
        this.stuInfoNameSirName = stuInfoNameSirName;
    }

    
    @Column(name="stu_info_name_first_name")
    public String getStuInfoNameFirstName() {
        return this.stuInfoNameFirstName;
    }
    
    public void setStuInfoNameFirstName(String stuInfoNameFirstName) {
        this.stuInfoNameFirstName = stuInfoNameFirstName;
    }

    
    @Column(name="stu_info_name_last_name")
    public String getStuInfoNameLastName() {
        return this.stuInfoNameLastName;
    }
    
    public void setStuInfoNameLastName(String stuInfoNameLastName) {
        this.stuInfoNameLastName = stuInfoNameLastName;
    }




}


