/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fourgenius.www.user_FrontEnd;

import com.fourgenius.www.public_access.inventory.Suplier;
import com.fourgenius.www.public_access.inventory.customer;
import com.fourgenius.www.public_access.inventory.grn;
import com.fourgenius.www.public_access.inventory.invoice;
import com.fourgenius.www.public_access.user.login.Jf_user_login;
import com.fourgenius.www.user_FrontEnd.Jf_UserFront;
import java.awt.Color;
import javax.swing.*;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.GroupLayout;
import javax.swing.border.Border;

/**
 *
 * @author Dineth
 */
public class Inventory_home extends javax.swing.JFrame {

    private boolean cond = true;
    Border border=BorderFactory.createLineBorder(new Color(255,255,255), 1);
    public Inventory_home() {
         initComponents();
        Toolkit tool = Toolkit.getDefaultToolkit();
        Dimension dim = new Dimension(tool.getScreenSize());
        setSize(dim);

        loadtime();
        Dis.setVisible(false);
        addp.setVisible(false);
        Payments.setVisible(false);

      

 
    }

    Inventory_home(String type, String name) {
        this();
       
        if (type.equals("User")) {

            cond = false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        customer = new javax.swing.JButton();
        suplier = new javax.swing.JButton();
        grn = new javax.swing.JButton();
        invoice = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        base = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Dis = new javax.swing.JLabel();
        addp = new javax.swing.JLabel();
        Payments = new javax.swing.JLabel();
        removeSelectedItem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(2, 119, 189));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 80));

        time.setFont(new java.awt.Font("DS-Digital", 3, 30)); // NOI18N
        time.setForeground(new java.awt.Color(204, 204, 204));

        home.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/buton_blue_200x50.png"))); // NOI18N
        home.setText("Home");
        home.setBorderPainted(false);
        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.setFocusPainted(false);
        home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home.setMaximumSize(new java.awt.Dimension(200, 50));
        home.setMinimumSize(new java.awt.Dimension(200, 50));
        home.setPreferredSize(new java.awt.Dimension(200, 50));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        customer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customer.setForeground(new java.awt.Color(255, 255, 255));
        customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/buton_blue_200x50.png"))); // NOI18N
        customer.setText("Customer");
        customer.setBorderPainted(false);
        customer.setContentAreaFilled(false);
        customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customer.setFocusPainted(false);
        customer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        customer.setMaximumSize(new java.awt.Dimension(200, 50));
        customer.setMinimumSize(new java.awt.Dimension(200, 50));
        customer.setPreferredSize(new java.awt.Dimension(200, 50));
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });

        suplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        suplier.setForeground(new java.awt.Color(255, 255, 255));
        suplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/buton_blue_200x50.png"))); // NOI18N
        suplier.setText("Suplier");
        suplier.setBorderPainted(false);
        suplier.setContentAreaFilled(false);
        suplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        suplier.setFocusPainted(false);
        suplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        suplier.setMaximumSize(new java.awt.Dimension(200, 50));
        suplier.setMinimumSize(new java.awt.Dimension(200, 50));
        suplier.setPreferredSize(new java.awt.Dimension(200, 50));
        suplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suplierActionPerformed(evt);
            }
        });

        grn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        grn.setForeground(new java.awt.Color(255, 255, 255));
        grn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/buton_blue_200x50.png"))); // NOI18N
        grn.setText("GRN");
        grn.setBorderPainted(false);
        grn.setContentAreaFilled(false);
        grn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        grn.setFocusPainted(false);
        grn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        grn.setMaximumSize(new java.awt.Dimension(200, 50));
        grn.setMinimumSize(new java.awt.Dimension(200, 50));
        grn.setPreferredSize(new java.awt.Dimension(200, 50));
        grn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grnActionPerformed(evt);
            }
        });

        invoice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        invoice.setForeground(new java.awt.Color(255, 255, 255));
        invoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/buton_blue_200x50.png"))); // NOI18N
        invoice.setText("Invoice");
        invoice.setBorderPainted(false);
        invoice.setContentAreaFilled(false);
        invoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        invoice.setFocusPainted(false);
        invoice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        invoice.setMaximumSize(new java.awt.Dimension(200, 50));
        invoice.setMinimumSize(new java.awt.Dimension(200, 50));
        invoice.setPreferredSize(new java.awt.Dimension(200, 50));
        invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/power off.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        getContentPane().add(base, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1366, 650));

        jPanel2.setBackground(new java.awt.Color(2, 119, 189));

        Dis.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Dis.setForeground(new java.awt.Color(255, 255, 255));
        Dis.setText("     f5-Discount   ");

        addp.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        addp.setForeground(new java.awt.Color(255, 255, 255));
        addp.setText("f2-Add Another Product        ");

        Payments.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Payments.setForeground(new java.awt.Color(255, 255, 255));
        Payments.setText("f4-Payments");

        removeSelectedItem.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        removeSelectedItem.setForeground(new java.awt.Color(255, 255, 255));
        removeSelectedItem.setText("f3-Remove Selected Item      ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(403, Short.MAX_VALUE)
                .addComponent(addp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeSelectedItem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Payments, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Dis, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Payments, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dis, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeSelectedItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 1370, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
         customer.setSelected(true);
        suplier.setSelected(false);
        invoice.setSelected(false);
        grn.setSelected(false);
      
        
        Dis.setVisible(false);
        addp.setVisible(false);
        removeSelectedItem.setVisible(false);
        Payments.setVisible(false);

        base.removeAll();
        GroupLayout layout = new GroupLayout(base);
        base.setLayout(layout);

        customer cu = new customer();

        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(cu, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(cu, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        cu.id.grabFocus();
        System.gc();
    }//GEN-LAST:event_customerActionPerformed

    private void suplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suplierActionPerformed
       customer.setSelected(false);
        suplier.setSelected(true);
        invoice.setSelected(false);
        grn.setSelected(false);
        
        
        Dis.setVisible(false);
        addp.setVisible(false);
        removeSelectedItem.setVisible(false);
        Payments.setVisible(false);

        base.removeAll();

        base.removeAll();
        GroupLayout layout = new GroupLayout(base);

        base.setLayout(layout);

        Suplier su = new Suplier();

        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(su, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(su, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        su.id.grabFocus();
        System.gc();
    }//GEN-LAST:event_suplierActionPerformed

    private void invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceActionPerformed
        customer.setSelected(false);
        suplier.setSelected(false);
        invoice.setSelected(true);
        grn.setSelected(false);
      
        Dis.setVisible(true);
        addp.setVisible(true);
        removeSelectedItem.setVisible(true);
        Payments.setVisible(true);

        base.removeAll();

        base.removeAll();
        GroupLayout layout = new GroupLayout(base);

        base.setLayout(layout);

     invoice in=new invoice();

        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(in, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(in, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        in.customername.grabFocus();
        System.gc();
    }//GEN-LAST:event_invoiceActionPerformed

    private void grnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grnActionPerformed
         customer.setSelected(false);
        suplier.setSelected(false);
        invoice.setSelected(false);
        grn.setSelected(true);
      
        
        Dis.setVisible(true);
        addp.setVisible(true);
        removeSelectedItem.setVisible(true);
        Payments.setVisible(true);

        base.removeAll();
        GroupLayout layout = new GroupLayout(base);
        base.setLayout(layout);

        grn gr = new grn();

        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(gr, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(gr, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        gr.supliername.grabFocus();
        System.gc();
    }//GEN-LAST:event_grnActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        this.dispose();
        new Jf_UserFront().setVisible(true);
    }//GEN-LAST:event_homeActionPerformed
Jf_user_login jf_user_login = new Jf_user_login();
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if (jf_user_login == null) {
            jf_user_login = new Jf_user_login();
            jf_user_login.setVisible(true);
            this.dispose();
        } else {
            jf_user_login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
       home.setBorder(border);
    }//GEN-LAST:event_homeMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dis;
    private javax.swing.JLabel Payments;
    private javax.swing.JLabel addp;
    public static javax.swing.JPanel base;
    private javax.swing.JButton customer;
    private javax.swing.JButton grn;
    private javax.swing.JButton home;
    private javax.swing.JButton invoice;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel removeSelectedItem;
    private javax.swing.JButton suplier;
    public static javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables

    private void loadtime() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    DateFormat df = new SimpleDateFormat(" hh:mm:ss a");
                    Date date = new Date();
                    time.setText(df.format(date));
                }
            }
        }).start();
    }
}
