/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fourgenius.www.public_access.registration.lecture;

/**
 *
 * @author Pamitha Gayashan
 */
public class Jp_registration_lecture_informations_form extends javax.swing.JPanel {

    /**
     * Creates new form Jp_registration_lecture_informations_form
     */
    public Jp_registration_lecture_informations_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _bg_registration_lecture_information_form_gender = new javax.swing.ButtonGroup();
        _bg_registration_lecture_information_form_academy = new javax.swing.ButtonGroup();
        _bg_registration_lecture_information_form_branch = new javax.swing.ButtonGroup();
        _pl_registration_lecture_personalInformation = new javax.swing.JPanel();
        _pl_registration_lecture_personalInformation_contactDetails = new javax.swing.JPanel();
        _lb_registration_lecture_information_form_mobile_number = new javax.swing.JLabel();
        _tf_registration_lecture_information_form_mobile_number = new javax.swing.JTextField();
        _lb_registration_lecture_information_form_home_number = new javax.swing.JLabel();
        _tf_registration_lecture_information_form_home_number = new javax.swing.JTextField();
        _lb_registration_lecture_information_form_email = new javax.swing.JLabel();
        _tf_registration_lecture_information_form_email = new javax.swing.JTextField();
        _lb_registration_lecture_information_form_1stline = new javax.swing.JLabel();
        _tf_registration_lecture_information_form_1stline = new javax.swing.JTextField();
        _lb_registration_lecture_information_form_city = new javax.swing.JLabel();
        _tf_registration_lecture_information_form_city = new javax.swing.JTextField();
        _lb_registration_lecture_information_form_country = new javax.swing.JLabel();
        _tf_registration_lecture_information_form_country = new javax.swing.JTextField();
        _lb_registration_lecture_information_form_address = new javax.swing.JLabel();
        _pl_registration_lecture_personalInformation_lectureName = new javax.swing.JPanel();
        _lb_registration_lecture_information_form_sur_name = new javax.swing.JLabel();
        _tf_registration_lecture_information_form_sur_name = new javax.swing.JTextField();
        _lb_registration_lecture_information_form_first_name = new javax.swing.JLabel();
        _tf_registration_lecture_information_form_first_name = new javax.swing.JTextField();
        _lb_registration_lecture_information_form_last_name = new javax.swing.JLabel();
        _tf_registration_lecture_information_form_last_name = new javax.swing.JTextField();
        _lb_registration_lecture_information_form_dob = new javax.swing.JLabel();
        _tf_registration_lecture_information_form_nic = new javax.swing.JTextField();
        _lb_registration_lecture_information_form_nic = new javax.swing.JLabel();
        _rb_registration_lecture_information_form_male = new javax.swing.JRadioButton();
        _lb_registration_lecture_information_form_gender = new javax.swing.JLabel();
        _rb_registration_lecture_information_form_female = new javax.swing.JRadioButton();
        _lb_registration_lecture_information_form_academy = new javax.swing.JLabel();
        _rb_registration_lecture_information_form_academic = new javax.swing.JRadioButton();
        _rb_registration_lecture_information_form_non_academic = new javax.swing.JRadioButton();
        _dc_registration_lecture_information_form_dob = new com.toedter.calendar.JDateChooser();
        _lb_registration_lecture_information_form_branch = new javax.swing.JLabel();
        _rb_registration_lecture_information_form_colombo = new javax.swing.JRadioButton();
        _rb_registration_lecture_information_form_kandy = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(66, 66, 66));

        _pl_registration_lecture_personalInformation.setBackground(new java.awt.Color(2, 119, 189));
        _pl_registration_lecture_personalInformation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        _pl_registration_lecture_personalInformation_contactDetails.setBackground(new java.awt.Color(2, 119, 189));
        _pl_registration_lecture_personalInformation_contactDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        _lb_registration_lecture_information_form_mobile_number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_information_form_mobile_number.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_information_form_mobile_number.setText("Mobile Number");

        _tf_registration_lecture_information_form_mobile_number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_information_form_mobile_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_information_form_mobile_numberActionPerformed(evt);
            }
        });
        _tf_registration_lecture_information_form_mobile_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _tf_registration_lecture_information_form_mobile_numberKeyReleased(evt);
            }
        });

        _lb_registration_lecture_information_form_home_number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_information_form_home_number.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_information_form_home_number.setText("Home Number");

        _tf_registration_lecture_information_form_home_number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_information_form_home_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_information_form_home_numberActionPerformed(evt);
            }
        });
        _tf_registration_lecture_information_form_home_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _tf_registration_lecture_information_form_home_numberKeyReleased(evt);
            }
        });

        _lb_registration_lecture_information_form_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_information_form_email.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_information_form_email.setText("E-mail");

        _tf_registration_lecture_information_form_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_information_form_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_information_form_emailActionPerformed(evt);
            }
        });

        _lb_registration_lecture_information_form_1stline.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_information_form_1stline.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_information_form_1stline.setText("1st Line");

        _tf_registration_lecture_information_form_1stline.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_information_form_1stline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_information_form_1stlineActionPerformed(evt);
            }
        });

        _lb_registration_lecture_information_form_city.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_information_form_city.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_information_form_city.setText("City");

        _tf_registration_lecture_information_form_city.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_information_form_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_information_form_cityActionPerformed(evt);
            }
        });

        _lb_registration_lecture_information_form_country.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_information_form_country.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_information_form_country.setText("Country");

        _tf_registration_lecture_information_form_country.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_information_form_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_information_form_countryActionPerformed(evt);
            }
        });

        _lb_registration_lecture_information_form_address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_information_form_address.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_information_form_address.setText("Address___________________________________");

        javax.swing.GroupLayout _pl_registration_lecture_personalInformation_contactDetailsLayout = new javax.swing.GroupLayout(_pl_registration_lecture_personalInformation_contactDetails);
        _pl_registration_lecture_personalInformation_contactDetails.setLayout(_pl_registration_lecture_personalInformation_contactDetailsLayout);
        _pl_registration_lecture_personalInformation_contactDetailsLayout.setHorizontalGroup(
            _pl_registration_lecture_personalInformation_contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pl_registration_lecture_personalInformation_contactDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_pl_registration_lecture_personalInformation_contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(_pl_registration_lecture_personalInformation_contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(_tf_registration_lecture_information_form_city)
                        .addComponent(_tf_registration_lecture_information_form_1stline)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _pl_registration_lecture_personalInformation_contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(_pl_registration_lecture_personalInformation_contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(_lb_registration_lecture_information_form_mobile_number, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                .addComponent(_tf_registration_lecture_information_form_mobile_number)
                                .addComponent(_lb_registration_lecture_information_form_home_number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_tf_registration_lecture_information_form_home_number)
                                .addComponent(_lb_registration_lecture_information_form_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_tf_registration_lecture_information_form_email))
                            .addComponent(_lb_registration_lecture_information_form_city, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_lb_registration_lecture_information_form_country, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(_tf_registration_lecture_information_form_country))
                    .addComponent(_lb_registration_lecture_information_form_1stline, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_lb_registration_lecture_information_form_address))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        _pl_registration_lecture_personalInformation_contactDetailsLayout.setVerticalGroup(
            _pl_registration_lecture_personalInformation_contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pl_registration_lecture_personalInformation_contactDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_lb_registration_lecture_information_form_mobile_number)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_registration_lecture_information_form_mobile_number, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_information_form_home_number)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_registration_lecture_information_form_home_number, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_information_form_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_registration_lecture_information_form_email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_lb_registration_lecture_information_form_address)
                .addGap(11, 11, 11)
                .addComponent(_lb_registration_lecture_information_form_1stline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_registration_lecture_information_form_1stline, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(_lb_registration_lecture_information_form_city)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_registration_lecture_information_form_city, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_information_form_country)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_registration_lecture_information_form_country, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        _pl_registration_lecture_personalInformation.add(_pl_registration_lecture_personalInformation_contactDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, 550));

        _pl_registration_lecture_personalInformation_lectureName.setBackground(new java.awt.Color(2, 119, 189));
        _pl_registration_lecture_personalInformation_lectureName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lecture Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        _lb_registration_lecture_information_form_sur_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_information_form_sur_name.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_information_form_sur_name.setText("Sur Name");

        _tf_registration_lecture_information_form_sur_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_information_form_sur_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_information_form_sur_nameActionPerformed(evt);
            }
        });
        _tf_registration_lecture_information_form_sur_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _tf_registration_lecture_information_form_sur_nameKeyReleased(evt);
            }
        });

        _lb_registration_lecture_information_form_first_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_information_form_first_name.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_information_form_first_name.setText("First Name");

        _tf_registration_lecture_information_form_first_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_information_form_first_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_information_form_first_nameActionPerformed(evt);
            }
        });
        _tf_registration_lecture_information_form_first_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _tf_registration_lecture_information_form_first_nameKeyReleased(evt);
            }
        });

        _lb_registration_lecture_information_form_last_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_information_form_last_name.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_information_form_last_name.setText("Last Name");

        _tf_registration_lecture_information_form_last_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_information_form_last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_information_form_last_nameActionPerformed(evt);
            }
        });
        _tf_registration_lecture_information_form_last_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _tf_registration_lecture_information_form_last_nameKeyReleased(evt);
            }
        });

        _lb_registration_lecture_information_form_dob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_information_form_dob.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_information_form_dob.setText("Date Of Birth");

        _tf_registration_lecture_information_form_nic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_registration_lecture_information_form_nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_registration_lecture_information_form_nicActionPerformed(evt);
            }
        });
        _tf_registration_lecture_information_form_nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _tf_registration_lecture_information_form_nicKeyReleased(evt);
            }
        });

        _lb_registration_lecture_information_form_nic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_information_form_nic.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_information_form_nic.setText("NIC Number");

        _rb_registration_lecture_information_form_male.setBackground(new java.awt.Color(2, 119, 189));
        _bg_registration_lecture_information_form_gender.add(_rb_registration_lecture_information_form_male);
        _rb_registration_lecture_information_form_male.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _rb_registration_lecture_information_form_male.setForeground(new java.awt.Color(255, 255, 255));
        _rb_registration_lecture_information_form_male.setSelected(true);
        _rb_registration_lecture_information_form_male.setText("Male");
        _rb_registration_lecture_information_form_male.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _rb_registration_lecture_information_form_maleMouseClicked(evt);
            }
        });

        _lb_registration_lecture_information_form_gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_information_form_gender.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_information_form_gender.setText("Gender");

        _rb_registration_lecture_information_form_female.setBackground(new java.awt.Color(2, 119, 189));
        _bg_registration_lecture_information_form_gender.add(_rb_registration_lecture_information_form_female);
        _rb_registration_lecture_information_form_female.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _rb_registration_lecture_information_form_female.setForeground(new java.awt.Color(255, 255, 255));
        _rb_registration_lecture_information_form_female.setText("Female");
        _rb_registration_lecture_information_form_female.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _rb_registration_lecture_information_form_femaleMouseClicked(evt);
            }
        });

        _lb_registration_lecture_information_form_academy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_information_form_academy.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_information_form_academy.setText("Acadamy");

        _rb_registration_lecture_information_form_academic.setBackground(new java.awt.Color(2, 119, 189));
        _bg_registration_lecture_information_form_academy.add(_rb_registration_lecture_information_form_academic);
        _rb_registration_lecture_information_form_academic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _rb_registration_lecture_information_form_academic.setForeground(new java.awt.Color(255, 255, 255));
        _rb_registration_lecture_information_form_academic.setSelected(true);
        _rb_registration_lecture_information_form_academic.setText("Academic");
        _rb_registration_lecture_information_form_academic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _rb_registration_lecture_information_form_academicMouseClicked(evt);
            }
        });

        _rb_registration_lecture_information_form_non_academic.setBackground(new java.awt.Color(2, 119, 189));
        _bg_registration_lecture_information_form_academy.add(_rb_registration_lecture_information_form_non_academic);
        _rb_registration_lecture_information_form_non_academic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _rb_registration_lecture_information_form_non_academic.setForeground(new java.awt.Color(255, 255, 255));
        _rb_registration_lecture_information_form_non_academic.setText("Non Academic");
        _rb_registration_lecture_information_form_non_academic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _rb_registration_lecture_information_form_non_academicMouseClicked(evt);
            }
        });

        _dc_registration_lecture_information_form_dob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _dc_registration_lecture_information_form_dob.setPreferredSize(new java.awt.Dimension(91, 40));
        _dc_registration_lecture_information_form_dob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _dc_registration_lecture_information_form_dobMouseClicked(evt);
            }
        });

        _lb_registration_lecture_information_form_branch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_registration_lecture_information_form_branch.setForeground(new java.awt.Color(255, 255, 255));
        _lb_registration_lecture_information_form_branch.setText("Branch");

        _rb_registration_lecture_information_form_colombo.setBackground(new java.awt.Color(2, 119, 189));
        _bg_registration_lecture_information_form_branch.add(_rb_registration_lecture_information_form_colombo);
        _rb_registration_lecture_information_form_colombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _rb_registration_lecture_information_form_colombo.setForeground(new java.awt.Color(255, 255, 255));
        _rb_registration_lecture_information_form_colombo.setSelected(true);
        _rb_registration_lecture_information_form_colombo.setText("Colombo");

        _rb_registration_lecture_information_form_kandy.setBackground(new java.awt.Color(2, 119, 189));
        _bg_registration_lecture_information_form_branch.add(_rb_registration_lecture_information_form_kandy);
        _rb_registration_lecture_information_form_kandy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _rb_registration_lecture_information_form_kandy.setForeground(new java.awt.Color(255, 255, 255));
        _rb_registration_lecture_information_form_kandy.setText("Kandy");
        _rb_registration_lecture_information_form_kandy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _rb_registration_lecture_information_form_kandyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout _pl_registration_lecture_personalInformation_lectureNameLayout = new javax.swing.GroupLayout(_pl_registration_lecture_personalInformation_lectureName);
        _pl_registration_lecture_personalInformation_lectureName.setLayout(_pl_registration_lecture_personalInformation_lectureNameLayout);
        _pl_registration_lecture_personalInformation_lectureNameLayout.setHorizontalGroup(
            _pl_registration_lecture_personalInformation_lectureNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pl_registration_lecture_personalInformation_lectureNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_pl_registration_lecture_personalInformation_lectureNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_dc_registration_lecture_information_form_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_registration_lecture_information_form_gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_registration_lecture_information_form_academy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(_pl_registration_lecture_personalInformation_lectureNameLayout.createSequentialGroup()
                        .addGroup(_pl_registration_lecture_personalInformation_lectureNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(_pl_registration_lecture_personalInformation_lectureNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(_lb_registration_lecture_information_form_sur_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_lb_registration_lecture_information_form_first_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_tf_registration_lecture_information_form_first_name)
                                .addComponent(_lb_registration_lecture_information_form_last_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_lb_registration_lecture_information_form_nic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_lb_registration_lecture_information_form_dob, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                .addComponent(_tf_registration_lecture_information_form_nic)
                                .addComponent(_tf_registration_lecture_information_form_last_name)
                                .addComponent(_tf_registration_lecture_information_form_sur_name))
                            .addGroup(_pl_registration_lecture_personalInformation_lectureNameLayout.createSequentialGroup()
                                .addComponent(_rb_registration_lecture_information_form_male)
                                .addGap(53, 53, 53)
                                .addComponent(_rb_registration_lecture_information_form_female))
                            .addComponent(_lb_registration_lecture_information_form_branch)
                            .addGroup(_pl_registration_lecture_personalInformation_lectureNameLayout.createSequentialGroup()
                                .addGroup(_pl_registration_lecture_personalInformation_lectureNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_rb_registration_lecture_information_form_academic)
                                    .addComponent(_rb_registration_lecture_information_form_colombo))
                                .addGap(18, 18, 18)
                                .addGroup(_pl_registration_lecture_personalInformation_lectureNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_rb_registration_lecture_information_form_kandy)
                                    .addComponent(_rb_registration_lecture_information_form_non_academic))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        _pl_registration_lecture_personalInformation_lectureNameLayout.setVerticalGroup(
            _pl_registration_lecture_personalInformation_lectureNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pl_registration_lecture_personalInformation_lectureNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_lb_registration_lecture_information_form_sur_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_registration_lecture_information_form_sur_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_information_form_first_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_registration_lecture_information_form_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_information_form_last_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_registration_lecture_information_form_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_information_form_nic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tf_registration_lecture_information_form_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_information_form_dob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_dc_registration_lecture_information_form_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_information_form_gender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(_pl_registration_lecture_personalInformation_lectureNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_rb_registration_lecture_information_form_male)
                    .addComponent(_rb_registration_lecture_information_form_female))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_information_form_academy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(_pl_registration_lecture_personalInformation_lectureNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_rb_registration_lecture_information_form_non_academic)
                    .addComponent(_rb_registration_lecture_information_form_academic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_registration_lecture_information_form_branch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(_pl_registration_lecture_personalInformation_lectureNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_rb_registration_lecture_information_form_colombo)
                    .addComponent(_rb_registration_lecture_information_form_kandy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        _pl_registration_lecture_personalInformation.add(_pl_registration_lecture_personalInformation_lectureName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_pl_registration_lecture_personalInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_pl_registration_lecture_personalInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void _tf_registration_lecture_information_form_mobile_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_information_form_mobile_numberActionPerformed
        _tf_registration_lecture_information_form_home_number.grabFocus();
    }//GEN-LAST:event__tf_registration_lecture_information_form_mobile_numberActionPerformed

    private void _tf_registration_lecture_information_form_home_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_information_form_home_numberActionPerformed
        _tf_registration_lecture_information_form_email.grabFocus();
    }//GEN-LAST:event__tf_registration_lecture_information_form_home_numberActionPerformed

    private void _tf_registration_lecture_information_form_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_information_form_emailActionPerformed
        _tf_registration_lecture_information_form_1stline.grabFocus();
    }//GEN-LAST:event__tf_registration_lecture_information_form_emailActionPerformed

    private void _tf_registration_lecture_information_form_1stlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_information_form_1stlineActionPerformed
        _tf_registration_lecture_information_form_city.grabFocus();
    }//GEN-LAST:event__tf_registration_lecture_information_form_1stlineActionPerformed

    private void _tf_registration_lecture_information_form_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_information_form_cityActionPerformed
        _tf_registration_lecture_information_form_country.grabFocus();
    }//GEN-LAST:event__tf_registration_lecture_information_form_cityActionPerformed

    private void _tf_registration_lecture_information_form_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_information_form_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__tf_registration_lecture_information_form_countryActionPerformed

    private void _tf_registration_lecture_information_form_sur_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_information_form_sur_nameActionPerformed
        _tf_registration_lecture_information_form_first_name.grabFocus();
    }//GEN-LAST:event__tf_registration_lecture_information_form_sur_nameActionPerformed

    private void _tf_registration_lecture_information_form_first_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_information_form_first_nameActionPerformed
        _tf_registration_lecture_information_form_last_name.grabFocus();
    }//GEN-LAST:event__tf_registration_lecture_information_form_first_nameActionPerformed

    private void _tf_registration_lecture_information_form_last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_information_form_last_nameActionPerformed
        _tf_registration_lecture_information_form_nic.grabFocus();
    }//GEN-LAST:event__tf_registration_lecture_information_form_last_nameActionPerformed

    private void _tf_registration_lecture_information_form_nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_registration_lecture_information_form_nicActionPerformed
        _dc_registration_lecture_information_form_dob.grabFocus();
    }//GEN-LAST:event__tf_registration_lecture_information_form_nicActionPerformed

    private void _rb_registration_lecture_information_form_maleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__rb_registration_lecture_information_form_maleMouseClicked

    }//GEN-LAST:event__rb_registration_lecture_information_form_maleMouseClicked

    private void _rb_registration_lecture_information_form_femaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__rb_registration_lecture_information_form_femaleMouseClicked

    }//GEN-LAST:event__rb_registration_lecture_information_form_femaleMouseClicked

    private void _rb_registration_lecture_information_form_academicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__rb_registration_lecture_information_form_academicMouseClicked
        _tf_registration_lecture_information_form_mobile_number.grabFocus();
    }//GEN-LAST:event__rb_registration_lecture_information_form_academicMouseClicked

    private void _rb_registration_lecture_information_form_non_academicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__rb_registration_lecture_information_form_non_academicMouseClicked
        _tf_registration_lecture_information_form_mobile_number.grabFocus();
    }//GEN-LAST:event__rb_registration_lecture_information_form_non_academicMouseClicked

    private void _dc_registration_lecture_information_form_dobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__dc_registration_lecture_information_form_dobMouseClicked

    }//GEN-LAST:event__dc_registration_lecture_information_form_dobMouseClicked

    private void _rb_registration_lecture_information_form_kandyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__rb_registration_lecture_information_form_kandyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__rb_registration_lecture_information_form_kandyActionPerformed

    private void _tf_registration_lecture_information_form_nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_registration_lecture_information_form_nicKeyReleased
        char c=evt.getKeyChar();
        
        if (_tf_registration_lecture_information_form_nic.getText().length() == 9 ) {
            if (_tf_registration_lecture_information_form_nic.getText().length()==10 ) {
                evt.consume();
            }
            else if (Character.isDigit(c) | !((c=='v')||(c=='x')) ) {
                evt.consume();
            }
            
        }
        else{
            if (Character.isLetter(c)) {
                evt.consume();
            }
        }
    }//GEN-LAST:event__tf_registration_lecture_information_form_nicKeyReleased

    private void _tf_registration_lecture_information_form_sur_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_registration_lecture_information_form_sur_nameKeyReleased
        char c=evt.getKeyChar();
        if (!(Character.isLetter(c))) {
            evt.consume();
        }
    }//GEN-LAST:event__tf_registration_lecture_information_form_sur_nameKeyReleased

    private void _tf_registration_lecture_information_form_first_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_registration_lecture_information_form_first_nameKeyReleased
        char c=evt.getKeyChar();
        if (!(Character.isLetter(c))) {
            evt.consume();
        }
    }//GEN-LAST:event__tf_registration_lecture_information_form_first_nameKeyReleased

    private void _tf_registration_lecture_information_form_last_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_registration_lecture_information_form_last_nameKeyReleased
        char c=evt.getKeyChar();
        if (!(Character.isLetter(c))) {
            evt.consume();
        }
    }//GEN-LAST:event__tf_registration_lecture_information_form_last_nameKeyReleased

    private void _tf_registration_lecture_information_form_mobile_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_registration_lecture_information_form_mobile_numberKeyReleased
        char c=evt.getKeyChar();
        if (_tf_registration_lecture_information_form_mobile_number.getText().length()==10||Character.isLetter(c)) {
            evt.consume();
        }
    }//GEN-LAST:event__tf_registration_lecture_information_form_mobile_numberKeyReleased

    private void _tf_registration_lecture_information_form_home_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_registration_lecture_information_form_home_numberKeyReleased
        char c=evt.getKeyChar();
        if (_tf_registration_lecture_information_form_home_number.getText().length()==10||Character.isLetter(c)) {
            evt.consume();
        }
    }//GEN-LAST:event__tf_registration_lecture_information_form_home_numberKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup _bg_registration_lecture_information_form_academy;
    private javax.swing.ButtonGroup _bg_registration_lecture_information_form_branch;
    private javax.swing.ButtonGroup _bg_registration_lecture_information_form_gender;
    public com.toedter.calendar.JDateChooser _dc_registration_lecture_information_form_dob;
    private javax.swing.JLabel _lb_registration_lecture_information_form_1stline;
    private javax.swing.JLabel _lb_registration_lecture_information_form_academy;
    private javax.swing.JLabel _lb_registration_lecture_information_form_address;
    private javax.swing.JLabel _lb_registration_lecture_information_form_branch;
    private javax.swing.JLabel _lb_registration_lecture_information_form_city;
    private javax.swing.JLabel _lb_registration_lecture_information_form_country;
    private javax.swing.JLabel _lb_registration_lecture_information_form_dob;
    private javax.swing.JLabel _lb_registration_lecture_information_form_email;
    private javax.swing.JLabel _lb_registration_lecture_information_form_first_name;
    private javax.swing.JLabel _lb_registration_lecture_information_form_gender;
    private javax.swing.JLabel _lb_registration_lecture_information_form_home_number;
    private javax.swing.JLabel _lb_registration_lecture_information_form_last_name;
    private javax.swing.JLabel _lb_registration_lecture_information_form_mobile_number;
    private javax.swing.JLabel _lb_registration_lecture_information_form_nic;
    private javax.swing.JLabel _lb_registration_lecture_information_form_sur_name;
    private javax.swing.JPanel _pl_registration_lecture_personalInformation;
    private javax.swing.JPanel _pl_registration_lecture_personalInformation_contactDetails;
    private javax.swing.JPanel _pl_registration_lecture_personalInformation_lectureName;
    public javax.swing.JRadioButton _rb_registration_lecture_information_form_academic;
    public javax.swing.JRadioButton _rb_registration_lecture_information_form_colombo;
    public javax.swing.JRadioButton _rb_registration_lecture_information_form_female;
    public javax.swing.JRadioButton _rb_registration_lecture_information_form_kandy;
    public javax.swing.JRadioButton _rb_registration_lecture_information_form_male;
    public javax.swing.JRadioButton _rb_registration_lecture_information_form_non_academic;
    public javax.swing.JTextField _tf_registration_lecture_information_form_1stline;
    public javax.swing.JTextField _tf_registration_lecture_information_form_city;
    public javax.swing.JTextField _tf_registration_lecture_information_form_country;
    public javax.swing.JTextField _tf_registration_lecture_information_form_email;
    public javax.swing.JTextField _tf_registration_lecture_information_form_first_name;
    public javax.swing.JTextField _tf_registration_lecture_information_form_home_number;
    public javax.swing.JTextField _tf_registration_lecture_information_form_last_name;
    public javax.swing.JTextField _tf_registration_lecture_information_form_mobile_number;
    public javax.swing.JTextField _tf_registration_lecture_information_form_nic;
    public javax.swing.JTextField _tf_registration_lecture_information_form_sur_name;
    // End of variables declaration//GEN-END:variables
}
