/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fourgenius.www.public_access.exams;

import com.fourgenius.www.public_access.registration.lecture.*;
import com.fourgenius.www.public_access.model.academic_employee.employee_academic_user_info;
import com.fourgenius.www.public_access.model.academic_employee.employee_academic_user_info_address;
import com.fourgenius.www.public_access.model.academic_employee.employee_academic_user_info_contact;
import com.fourgenius.www.public_access.model.academic_employee.employee_academic_user_info_name;
import com.fourgenius.www.public_access.model.academic_employee.employee_academic_user_info_personal;
import com.fourgenius.www.public_access.registration.student.user_image_copy;
import com.googlecode.javacv.CanvasFrame;
import com.googlecode.javacv.OpenCVFrameGrabber;
import com.googlecode.javacv.cpp.opencv_core;
import com.googlecode.javacv.cpp.opencv_highgui;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;
import public_access.MC_JavaDataBaseConnection;

/**
 *
 * @author thilina
 */
public class Jp_add_exams_informations extends javax.swing.JPanel {
    
    
//  Set Button Border Collor

    Border border = BorderFactory.createLineBorder(Color.white, 1);

//  Crate variables for lecture image path
    public String path, newpath;

//  Create variables for get lecture full name
    public String sur_name, first_name, last_name;

//  Create variable for pass to qulification form
    public String lecture_id;
    public int id_no;
    public String branch_name;
    public String full_name;

    /**
     * d
     * Creates new form registration_lecture
     */
    public Jp_add_exams_informations() {
        initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
        set_data_to_Combo_box();
//      Set max selectable date for validate date of birth
        Date d = Calendar.getInstance().getTime();
        _dc_add_exam_examDate.setMaxSelectableDate(d);
        _bt_add_exam_preview_addExam.setEnabled(false);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _bg_registration_lecture_personalInformations_employeeDetails_acadamy = new javax.swing.ButtonGroup();
        _bg_registration_lecture_personalInformations_employeeDetails_gender = new javax.swing.ButtonGroup();
        _bg_registration_lecture_personalInformation_employeeDetails_branch = new javax.swing.ButtonGroup();
        _pl_add_exams_examInformation_main_panel = new javax.swing.JPanel();
        _pl_add_exam_examInformation = new javax.swing.JPanel();
        _lb_add_exam_name = new javax.swing.JLabel();
        _tf_add_exam_name = new javax.swing.JTextField();
        _lb_add_exam_course_name = new javax.swing.JLabel();
        _cb_add_exam_course = new javax.swing.JComboBox();
        _lb_add_exam_examDate = new javax.swing.JLabel();
        _dc_add_exam_examDate = new com.toedter.calendar.JDateChooser();
        _lb_add_exam_branch = new javax.swing.JLabel();
        _rb_add_exam_colombo = new javax.swing.JRadioButton();
        _rb_add_exam_kandy = new javax.swing.JRadioButton();
        _bt_add_exam_preview = new javax.swing.JButton();
        _pl_add_exam_examInformation_preview = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        _lb_add_exam_preview_examID = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        _lb_add_exam_preview_name = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        _lb_add_exam_preview_course = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        _lb_add_exam_preview_date = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        _lb_add_exam_preview_branch = new javax.swing.JLabel();
        _bt_add_exam_preview_addExam = new javax.swing.JButton();
        _pl_registration_lecture_personalInformation_browsePhoto1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(66, 66, 66));
        setMinimumSize(new java.awt.Dimension(1366, 718));
        setPreferredSize(new java.awt.Dimension(1366, 718));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        _pl_add_exams_examInformation_main_panel.setBackground(new java.awt.Color(2, 119, 189));
        _pl_add_exams_examInformation_main_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exam Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        _pl_add_exams_examInformation_main_panel.setMaximumSize(new java.awt.Dimension(32767, 695));
        _pl_add_exams_examInformation_main_panel.setMinimumSize(new java.awt.Dimension(0, 695));
        _pl_add_exams_examInformation_main_panel.setPreferredSize(new java.awt.Dimension(815, 695));
        _pl_add_exams_examInformation_main_panel.setLayout(new java.awt.CardLayout());

        _pl_add_exam_examInformation.setBackground(new java.awt.Color(2, 119, 189));
        _pl_add_exam_examInformation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        _lb_add_exam_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_add_exam_name.setForeground(new java.awt.Color(255, 255, 255));
        _lb_add_exam_name.setText("Exam Name");
        _pl_add_exam_examInformation.add(_lb_add_exam_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 333, -1));

        _tf_add_exam_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_add_exam_name.setMaximumSize(new java.awt.Dimension(300, 40));
        _tf_add_exam_name.setPreferredSize(new java.awt.Dimension(300, 40));
        _tf_add_exam_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_add_exam_nameActionPerformed(evt);
            }
        });
        _tf_add_exam_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _tf_add_exam_nameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                _tf_add_exam_nameKeyTyped(evt);
            }
        });
        _pl_add_exam_examInformation.add(_tf_add_exam_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 333, -1));

        _lb_add_exam_course_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_add_exam_course_name.setForeground(new java.awt.Color(255, 255, 255));
        _lb_add_exam_course_name.setText("Course");
        _pl_add_exam_examInformation.add(_lb_add_exam_course_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 333, -1));

        _cb_add_exam_course.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _pl_add_exam_examInformation.add(_cb_add_exam_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 333, 40));

        _lb_add_exam_examDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_add_exam_examDate.setForeground(new java.awt.Color(255, 255, 255));
        _lb_add_exam_examDate.setText("Exam Date");
        _pl_add_exam_examInformation.add(_lb_add_exam_examDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 333, -1));

        _dc_add_exam_examDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _dc_add_exam_examDate.setPreferredSize(new java.awt.Dimension(91, 40));
        _dc_add_exam_examDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _dc_add_exam_examDateMouseClicked(evt);
            }
        });
        _pl_add_exam_examInformation.add(_dc_add_exam_examDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 333, -1));

        _lb_add_exam_branch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_add_exam_branch.setForeground(new java.awt.Color(255, 255, 255));
        _lb_add_exam_branch.setText("Branch");
        _pl_add_exam_examInformation.add(_lb_add_exam_branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        _rb_add_exam_colombo.setBackground(new java.awt.Color(2, 119, 189));
        _bg_registration_lecture_personalInformation_employeeDetails_branch.add(_rb_add_exam_colombo);
        _rb_add_exam_colombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _rb_add_exam_colombo.setForeground(new java.awt.Color(255, 255, 255));
        _rb_add_exam_colombo.setSelected(true);
        _rb_add_exam_colombo.setText("Colombo");
        _pl_add_exam_examInformation.add(_rb_add_exam_colombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        _rb_add_exam_kandy.setBackground(new java.awt.Color(2, 119, 189));
        _bg_registration_lecture_personalInformation_employeeDetails_branch.add(_rb_add_exam_kandy);
        _rb_add_exam_kandy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _rb_add_exam_kandy.setForeground(new java.awt.Color(255, 255, 255));
        _rb_add_exam_kandy.setText("Kandy");
        _rb_add_exam_kandy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _rb_add_exam_kandyActionPerformed(evt);
            }
        });
        _pl_add_exam_examInformation.add(_rb_add_exam_kandy, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        _bt_add_exam_preview.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _bt_add_exam_preview.setForeground(new java.awt.Color(255, 255, 255));
        _bt_add_exam_preview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/buton_blue_250x50.png"))); // NOI18N
        _bt_add_exam_preview.setText("Preview");
        _bt_add_exam_preview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _bt_add_exam_preview.setFocusPainted(false);
        _bt_add_exam_preview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _bt_add_exam_preview.setPreferredSize(new java.awt.Dimension(300, 50));
        _bt_add_exam_preview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _bt_add_exam_previewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _bt_add_exam_previewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _bt_add_exam_previewMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _bt_add_exam_previewMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                _bt_add_exam_previewMouseReleased(evt);
            }
        });
        _bt_add_exam_preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _bt_add_exam_previewActionPerformed(evt);
            }
        });
        _pl_add_exam_examInformation.add(_bt_add_exam_preview, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 244, -1));

        _pl_add_exams_examInformation_main_panel.add(_pl_add_exam_examInformation, "card2");

        add(_pl_add_exams_examInformation_main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 810, 620));

        _pl_add_exam_examInformation_preview.setBackground(new java.awt.Color(117, 117, 117));
        _pl_add_exam_examInformation_preview.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Exam ID");

        _lb_add_exam_preview_examID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Exam Name");

        _lb_add_exam_preview_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Course");

        _lb_add_exam_preview_course.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Exam Date");

        _lb_add_exam_preview_date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Branch");

        _lb_add_exam_preview_branch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        _bt_add_exam_preview_addExam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _bt_add_exam_preview_addExam.setForeground(new java.awt.Color(255, 255, 255));
        _bt_add_exam_preview_addExam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/buton_DarkGreen_200x50.png"))); // NOI18N
        _bt_add_exam_preview_addExam.setText("Add Exam");
        _bt_add_exam_preview_addExam.setContentAreaFilled(false);
        _bt_add_exam_preview_addExam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _bt_add_exam_preview_addExam.setFocusPainted(false);
        _bt_add_exam_preview_addExam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _bt_add_exam_preview_addExam.setPreferredSize(new java.awt.Dimension(100, 50));
        _bt_add_exam_preview_addExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _bt_add_exam_preview_addExamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _bt_add_exam_preview_addExamMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _bt_add_exam_preview_addExamMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                _bt_add_exam_preview_addExamMouseReleased(evt);
            }
        });
        _bt_add_exam_preview_addExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _bt_add_exam_preview_addExamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout _pl_add_exam_examInformation_previewLayout = new javax.swing.GroupLayout(_pl_add_exam_examInformation_preview);
        _pl_add_exam_examInformation_preview.setLayout(_pl_add_exam_examInformation_previewLayout);
        _pl_add_exam_examInformation_previewLayout.setHorizontalGroup(
            _pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pl_add_exam_examInformation_previewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(_pl_add_exam_examInformation_previewLayout.createSequentialGroup()
                        .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_lb_add_exam_preview_examID, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                            .addComponent(_lb_add_exam_preview_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_lb_add_exam_preview_course, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_lb_add_exam_preview_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_lb_add_exam_preview_branch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _pl_add_exam_examInformation_previewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(_bt_add_exam_preview_addExam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        _pl_add_exam_examInformation_previewLayout.setVerticalGroup(
            _pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pl_add_exam_examInformation_previewLayout.createSequentialGroup()
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_add_exam_preview_examID, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_add_exam_preview_name, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_add_exam_preview_course, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_add_exam_preview_date, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_add_exam_preview_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(416, 416, 416)
                .addComponent(_bt_add_exam_preview_addExam, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(_pl_add_exam_examInformation_preview, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 526, 620));

        _pl_registration_lecture_personalInformation_browsePhoto1.setBackground(new java.awt.Color(2, 119, 189));
        _pl_registration_lecture_personalInformation_browsePhoto1.setPreferredSize(new java.awt.Dimension(766, 123));

        javax.swing.GroupLayout _pl_registration_lecture_personalInformation_browsePhoto1Layout = new javax.swing.GroupLayout(_pl_registration_lecture_personalInformation_browsePhoto1);
        _pl_registration_lecture_personalInformation_browsePhoto1.setLayout(_pl_registration_lecture_personalInformation_browsePhoto1Layout);
        _pl_registration_lecture_personalInformation_browsePhoto1Layout.setHorizontalGroup(
            _pl_registration_lecture_personalInformation_browsePhoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        _pl_registration_lecture_personalInformation_browsePhoto1Layout.setVerticalGroup(
            _pl_registration_lecture_personalInformation_browsePhoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        add(_pl_registration_lecture_personalInformation_browsePhoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 810, 60));
    }// </editor-fold>//GEN-END:initComponents


    private void _bt_add_exam_previewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_previewMouseEntered
        _bt_add_exam_preview.setBorder(border);
    }//GEN-LAST:event__bt_add_exam_previewMouseEntered

    private void _bt_add_exam_previewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_previewMouseExited
        _bt_add_exam_preview.setBorder(null);
    }//GEN-LAST:event__bt_add_exam_previewMouseExited

    private void _bt_add_exam_previewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_previewMousePressed
        _bt_add_exam_preview.setBorder(null);
    }//GEN-LAST:event__bt_add_exam_previewMousePressed

    private void _bt_add_exam_previewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_previewMouseReleased
        _bt_add_exam_preview.setBorder(border);
    }//GEN-LAST:event__bt_add_exam_previewMouseReleased

    private void _bt_add_exam_previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__bt_add_exam_previewActionPerformed
        if (_bt_add_exam_preview.getText().equals("Preview")) {

            check_empty_fields();
        } else {

            check_update_empty_fields();
        }
    }//GEN-LAST:event__bt_add_exam_previewActionPerformed

    private void _bt_add_exam_previewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_previewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event__bt_add_exam_previewMouseClicked

    private void _bt_add_exam_preview_addExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__bt_add_exam_preview_addExamActionPerformed

        try {
            if (_bt_add_exam_preview_addExam.getText().equals("Register Lecture")) {
                int option = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Confirm?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (option == JOptionPane.YES_OPTION) {
                    add_to_database();
                    clear_personal_information_form();
                    clear_preview_form();
                    load_information_qulifications_form();
                    _bt_add_exam_preview.setVisible(false);
                    _bt_add_exam_preview_addExam.setEnabled(false);

                }
            } else {
                int option = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Confirm?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (option == JOptionPane.YES_OPTION) {
                    add_to_database();
                    clear_personal_information_form();
                    clear_preview_form();

                    Connection c = MC_JavaDataBaseConnection.myConnection();
                    Statement s = c.createStatement();
                    ResultSet rs_fileid = s.executeQuery("SELECT employee_academic_user_info_qulifications_file_id FROM employee_academic_user_info_qulifications WHERE employee_academic_user_id='" + lecture_id + "'");
                    if (rs_fileid.next()) {
                        String fileid = rs_fileid.getString("employee_academic_user_info_qulifications_file_id");
                        load_information_qulifications_update_form(fileid);
                        _bt_add_exam_preview.setVisible(false);
                        _bt_add_exam_preview_addExam.setEnabled(false);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event__bt_add_exam_preview_addExamActionPerformed

    private void _bt_add_exam_preview_addExamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_preview_addExamMouseEntered
        _bt_add_exam_preview_addExam.setBorder(border);
    }//GEN-LAST:event__bt_add_exam_preview_addExamMouseEntered

    private void _bt_add_exam_preview_addExamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_preview_addExamMouseExited
        _bt_add_exam_preview_addExam.setBorder(null);
    }//GEN-LAST:event__bt_add_exam_preview_addExamMouseExited

    private void _bt_add_exam_preview_addExamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_preview_addExamMousePressed
        _bt_add_exam_preview_addExam.setBorder(null);
    }//GEN-LAST:event__bt_add_exam_preview_addExamMousePressed

    private void _bt_add_exam_preview_addExamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_preview_addExamMouseReleased
        _bt_add_exam_preview_addExam.setBorder(border);
    }//GEN-LAST:event__bt_add_exam_preview_addExamMouseReleased

    private void _rb_add_exam_kandyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__rb_add_exam_kandyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__rb_add_exam_kandyActionPerformed

    private void _dc_add_exam_examDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__dc_add_exam_examDateMouseClicked

    }//GEN-LAST:event__dc_add_exam_examDateMouseClicked

    private void _tf_add_exam_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_add_exam_nameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c)) && !(Character.isSpaceChar(c))) {
            evt.consume();
        }
        if (100 <= _tf_add_exam_name.getText().length()) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "You Exceed The Character Limit");
        }
    }//GEN-LAST:event__tf_add_exam_nameKeyTyped

    private void _tf_add_exam_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_add_exam_nameKeyReleased

    }//GEN-LAST:event__tf_add_exam_nameKeyReleased

    private void _tf_add_exam_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_add_exam_nameActionPerformed
//        _tf_add_exam_course_name.grabFocus();
    }//GEN-LAST:event__tf_add_exam_nameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup _bg_registration_lecture_personalInformation_employeeDetails_branch;
    private javax.swing.ButtonGroup _bg_registration_lecture_personalInformations_employeeDetails_acadamy;
    private javax.swing.ButtonGroup _bg_registration_lecture_personalInformations_employeeDetails_gender;
    private javax.swing.JButton _bt_add_exam_preview;
    private javax.swing.JButton _bt_add_exam_preview_addExam;
    private javax.swing.JComboBox _cb_add_exam_course;
    public com.toedter.calendar.JDateChooser _dc_add_exam_examDate;
    private javax.swing.JLabel _lb_add_exam_branch;
    private javax.swing.JLabel _lb_add_exam_course_name;
    private javax.swing.JLabel _lb_add_exam_examDate;
    private javax.swing.JLabel _lb_add_exam_name;
    private javax.swing.JLabel _lb_add_exam_preview_branch;
    private javax.swing.JLabel _lb_add_exam_preview_course;
    private javax.swing.JLabel _lb_add_exam_preview_date;
    private javax.swing.JLabel _lb_add_exam_preview_examID;
    public javax.swing.JLabel _lb_add_exam_preview_name;
    private javax.swing.JPanel _pl_add_exam_examInformation;
    private javax.swing.JPanel _pl_add_exam_examInformation_preview;
    private javax.swing.JPanel _pl_add_exams_examInformation_main_panel;
    private javax.swing.JPanel _pl_registration_lecture_personalInformation_browsePhoto1;
    public javax.swing.JRadioButton _rb_add_exam_colombo;
    public javax.swing.JRadioButton _rb_add_exam_kandy;
    public static javax.swing.JTextField _tf_add_exam_name;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    // End of variables declaration//GEN-END:variables

    private void load_information_qulifications_form() {
        try {
            Jp_registration_lecture_informations_qulifications_form view_lecture_information_qulification_form = new Jp_registration_lecture_informations_qulifications_form(lecture_id, id_no, branch_name, full_name);

            if (view_lecture_information_qulification_form == null) {
                view_lecture_information_qulification_form = new Jp_registration_lecture_informations_qulifications_form(lecture_id, id_no, branch_name, full_name);
                _pl_add_exams_examInformation_main_panel.removeAll();
                _pl_add_exams_examInformation_main_panel.repaint();
                _pl_add_exams_examInformation_main_panel.revalidate();
                _pl_add_exams_examInformation_main_panel.add(view_lecture_information_qulification_form);
                _pl_add_exams_examInformation_main_panel.repaint();
                _pl_add_exams_examInformation_main_panel.revalidate();
            } else {
                _pl_add_exams_examInformation_main_panel.removeAll();
                _pl_add_exams_examInformation_main_panel.repaint();
                _pl_add_exams_examInformation_main_panel.revalidate();
                _pl_add_exams_examInformation_main_panel.add(view_lecture_information_qulification_form);
                _pl_add_exams_examInformation_main_panel.repaint();
                _pl_add_exams_examInformation_main_panel.revalidate();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void button_enable(String button_name) {
        try {

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void add_to_preview_form() {
        generate_exam_id();
        _lb_add_exam_preview_name.setText(_tf_add_exam_name.getText());
        
    }

    private void generate_exam_id() {

        String id = "ID";
        String lc = "EXM";

        employee_academic_user_info user_info = new employee_academic_user_info();
        String countid = user_info.getIdemployee_academic_user();
        int idcount = Integer.parseInt(countid);
        id_no = ++idcount;

        String a = Integer.toString(id_no);
        int length = a.length();
        System.out.println(length);

        String idn = Integer.toString(id_no);
        String zeros;
        if (length == 1) {
            zeros = "00000";
        } else if (length == 2) {
            zeros = "0000";
        } else if (length == 3) {
            zeros = "000";
        } else if (length == 4) {
            zeros = "00";
        } else if (length == 5) {
            zeros = "0";
        } else {
            zeros = "";
        }

        if (_rb_add_exam_colombo.isSelected()) {
            branch_name = "COL";
        } else {
            branch_name = "KAN";
        }

        lecture_id = id + "-" + lc + "-" + branch_name + "-" + zeros + id_no;
        _lb_add_exam_preview_examID.setText(lecture_id);

    }

    private void add_to_database() {
//        employee_academic_user_info user_info = new employee_academic_user_info(_lb_add_exam_preview_examID.getText(), _lb_registration_lecture_preview_eMail.getText(), "1");
//
//        employee_academic_user_info_address user_info_address = new employee_academic_user_info_address(_lb_add_exam_preview_examID.getText(), _lb_registration_lecture_preview_address_address_line.getText(), _lb_registration_lecture_preview_address_city.getText(), _lb_registration_lecture_preview_address_country.getText());
//
//        employee_academic_user_info_contact user_info_contact = new employee_academic_user_info_contact(_lb_add_exam_preview_examID.getText(), _lb_registration_lecture_preview_mobileNumber.getText(), _lb_registration_lecture_preview_homeNumber.getText(), _lb_registration_lecture_preview_eMail.getText());
//
//        employee_academic_user_info_name user_info_name = new employee_academic_user_info_name(_lb_add_exam_preview_examID.getText(), sur_name, first_name, last_name);
//
//        employee_academic_user_info_personal user_info_personal = new employee_academic_user_info_personal(_lb_add_exam_preview_examID.getText(), newpath, _lb_registration_lecture_preview_dateOfBirth.getText(), _lb_registration_lecture_preview_gender.getText(), _lb_registration_lecture_preview_nic.getText(), _lb_registration_lecture_preview_branch.getText());
    }

    private void clear_personal_information_form() {
//        _tf_add_exam_name.setText(null);
//        _tf_add_exam_course_name.setText(null);
//        _tf_registration_lecture_information_form_last_name.setText(null);
//        _tf_registration_lecture_information_form_nic.setText(null);
//        _dc_registration_lecture_information_form_dob.setDate(null);
//        _rb_registration_lecture_information_form_male.setSelected(true);
//        _rb_registration_lecture_information_form_colombo.setSelected(true);
//        _tf_registration_lecture_information_form_mobile_number.setText(null);
//        _tf_registration_lecture_information_form_home_number.setText(null);
//        _tf_registration_lecture_information_form_email.setText(null);
//        _tf_registration_lecture_information_form_address_line.setText(null);
//        _tf_registration_lecture_information_form_city.setText(null);
//        _tf_registration_lecture_information_form_country.setText(null);
//        _tf_registration_lecture_personalInformation_browsePhoto_browseFile.setText("Browse Photo");

    }

    private void clear_preview_form() {
//        _lb_add_exam_preview_examID.setText(null);
//        _lb_registration_lecture_preview_name.setText(null);
//        _lb_registration_lecture_preview_nic.setText(null);
//        _lb_registration_lecture_preview_dateOfBirth.setText(null);
//        _lb_registration_lecture_preview_gender.setText(null);
//        _lb_registration_lecture_preview_branch.setText(null);
//        _lb_registration_lecture_preview_mobileNumber.setText(null);
//        _lb_registration_lecture_preview_homeNumber.setText(null);
//        _lb_registration_lecture_preview_eMail.setText(null);
//        _lb_registration_lecture_preview_address_address_line.setText(null);
//        _lb_registration_lecture_preview_address_city.setText(null);
//        _lb_registration_lecture_preview_address_country.setText(null);
//        _lb_registration_lecture_preview_image.setIcon(null);
    }

    private void load_form_data(String id) {
//        try {
//            Connection c = MC_JavaDataBaseConnection.myConnection();
//            Statement s = c.createStatement();
//
//            ResultSet rs_name = s.executeQuery("SELECT * FROM employee_academic_user_info_name WHERE employee_academic_user_id='" + id + "'");
//            if (rs_name.next()) {
//                _tf_add_exam_name.setText(rs_name.getString("employee_academic_user_info_name_surName"));
//                _tf_add_exam_course_name.setText(rs_name.getString("employee_academic_user_info_name_first_name"));
//                _tf_registration_lecture_information_form_last_name.setText(rs_name.getString("employee_academic_user_info_name_last_name"));
//            }
//
//            ResultSet rs_personal = s.executeQuery("SELECT * FROM employee_academic_user_info_personal WHERE employee_academic_user_id='" + id + "'");
//            if (rs_personal.next()) {
//                _tf_registration_lecture_information_form_nic.setText(rs_personal.getString("employee_academic_user_info_personal_nic"));
//                _dc_registration_lecture_information_form_dob.setDate(rs_personal.getDate("employee_academic_user_info_personal_dob"));
//
//                String gender = rs_personal.getString("employee_academic_user_info_personal_gender");
//                if (gender.equals("Male")) {
//                    _rb_registration_lecture_information_form_male.setSelected(true);
//                } else {
//                    _rb_registration_lecture_information_form_female.setSelected(true);
//                }
//
//                String branch = rs_personal.getString("employee_academic_user_info_personal_branch");
//                if (branch.equals("Colombo")) {
//                    _rb_registration_lecture_information_form_colombo.setSelected(true);
//                } else {
//                    _rb_registration_lecture_information_form_kandy.setSelected(true);
//                }
//
////                _tf_registration_lecture_personalInformation_browsePhoto_browseFile.setText(rs_personal.getString("employee_academic_user_info_personal_profile_image"));
//                String pic = rs_personal.getString("employee_academic_user_info_personal_profile_image");
//                String picpath = pic.replace("/", "\\");
//                _tf_registration_lecture_personalInformation_browsePhoto_browseFile.setText(picpath);
//
//            }
//
//            ResultSet rs_contact = s.executeQuery("SELECT * FROM employee_academic_user_info_contact WHERE employee_academic_user_id='" + id + "'");
//            if (rs_contact.next()) {
//                _tf_registration_lecture_information_form_mobile_number.setText(rs_contact.getString("employee_academic_user_info_contact_mobile"));
//                _tf_registration_lecture_information_form_home_number.setText(rs_contact.getString("employee_academic_user_info_contact_land"));
//                _tf_registration_lecture_information_form_email.setText(rs_contact.getString("employee_academic_user_info_contact_email"));
//            }
//
//            ResultSet rs_address = s.executeQuery("SELECT * FROM employee_academic_user_info_address WHERE employee_academic_user_id='" + id + "'");
//            if (rs_address.next()) {
//                _tf_registration_lecture_information_form_address_line.setText(rs_address.getString("employee_academic_user_info_address_lane1"));
//                _tf_registration_lecture_information_form_city.setText(rs_address.getString("employee_academic_user_info_address_city"));
//                _tf_registration_lecture_information_form_country.setText(rs_address.getString("employee_academic_user_info_address_cuntry"));
//            }
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }

    private void add_to_preview_form_update() {
//        try {
//            try {
//                Date d = _dc_registration_lecture_information_form_dob.getDate();
//                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//                String date = sdf.format(d);
//                _lb_registration_lecture_preview_dateOfBirth.setText(date);
//
//                _lb_registration_lecture_preview_lectureID.setText(lecture_id);
//
//                try {
//                    newpath = _tf_registration_lecture_personalInformation_browsePhoto_browseFile.getText().replace("\\", "/");
//                    File f = new File(newpath);
//                    Image img = ImageIO.read(f);
//                    img = img.getScaledInstance(_lb_registration_lecture_preview_image.getWidth(), _lb_registration_lecture_preview_image.getHeight(), Image.SCALE_SMOOTH);
//                    _lb_registration_lecture_preview_image.setIcon(new ImageIcon(img));
//                } catch (Exception e) {
//                    _lb_registration_lecture_preview_image.setIcon(null);
//                }
//
//                sur_name = _tf_add_exam_name.getText();
//                first_name = _tf_add_exam_course_name.getText();
//                last_name = _tf_registration_lecture_information_form_last_name.getText();
//
//                full_name = first_name + "_" + last_name;
//
//                _lb_registration_lecture_preview_name.setText(sur_name + " " + first_name + " " + last_name);
//
//                _lb_registration_lecture_preview_nic.setText(_tf_registration_lecture_information_form_nic.getText());
//
//                String gender;
//                if (_rb_registration_lecture_information_form_male.isSelected()) {
//                    gender = "Male";
//                } else {
//                    gender = "Female";
//                }
//                _lb_registration_lecture_preview_gender.setText(gender);
//
//                String branch;
//                if (_rb_registration_lecture_information_form_colombo.isSelected()) {
//                    branch = "Colombo";
//                } else {
//                    branch = "Kandy";
//                }
//                _lb_registration_lecture_preview_branch.setText(branch);
//
//                _lb_registration_lecture_preview_mobileNumber.setText(_tf_registration_lecture_information_form_mobile_number.getText());
//                _lb_registration_lecture_preview_homeNumber.setText(_tf_registration_lecture_information_form_home_number.getText());
//                _lb_registration_lecture_preview_eMail.setText(_tf_registration_lecture_information_form_email.getText());
//                _lb_registration_lecture_preview_address_address_line.setText(_tf_registration_lecture_information_form_address_line.getText());
//                _lb_registration_lecture_preview_address_city.setText(_tf_registration_lecture_information_form_city.getText());
//                _lb_registration_lecture_preview_address_country.setText(_tf_registration_lecture_information_form_country.getText());
//
//                _bt_registration_lecture_preview_register_lecture.setEnabled(true);
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(this, "Birthday is Empty");
//            }
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }

    private void load_information_qulifications_update_form(String file_id) {
        Jp_registration_lecture_informations_qulifications_form qform = new Jp_registration_lecture_informations_qulifications_form(file_id, lecture_id);

        if (qform == null) {
            qform = new Jp_registration_lecture_informations_qulifications_form(file_id, lecture_id);
            _pl_add_exams_examInformation_main_panel.removeAll();
            _pl_add_exams_examInformation_main_panel.repaint();
            _pl_add_exams_examInformation_main_panel.revalidate();
            _pl_add_exams_examInformation_main_panel.add(qform);
            _pl_add_exams_examInformation_main_panel.repaint();
            _pl_add_exams_examInformation_main_panel.revalidate();
        } else {
            _pl_add_exams_examInformation_main_panel.removeAll();
            _pl_add_exams_examInformation_main_panel.repaint();
            _pl_add_exams_examInformation_main_panel.revalidate();
            _pl_add_exams_examInformation_main_panel.add(qform);
            _pl_add_exams_examInformation_main_panel.repaint();
            _pl_add_exams_examInformation_main_panel.revalidate();
        }
    }

    private void set_data_to_Combo_box() {
        try {
            ResultSet rs;
            String sql = "SELECT * FROM `stu_exam_courses_info";
            rs = MC_JavaDataBaseConnection.myConnection().createStatement().executeQuery(sql);

            while (rs.next()) {
                String name = rs.getString("stu_exam_courses_info_name");
                _cb_add_exam_course.addItem(name);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void check_empty_fields() {
        if (_tf_add_exam_name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Exam Name is Empty!");
        }else{
            add_to_preview_form();
        }
    }

    private void check_update_empty_fields() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
