/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fourgenius.www.public_access.exams;

import static com.fourgenius.www.public_access.exams.Jf_Exams._bt_UserMain_home;
import static com.fourgenius.www.public_access.exams.Jp_add_exams.Jp_add_exams_main_panel;
import static com.fourgenius.www.public_access.exams.Jp_add_exams._bt_add_exam_AddExam;
import static com.fourgenius.www.public_access.exams.Jp_add_exams._bt_add_exam_ExamsDetails;
import com.fourgenius.www.public_access.registration.lecture.*;
import com.fourgenius.www.public_access.model.academic_employee.employee_academic_user_info;
import com.fourgenius.www.public_access.model.academic_employee.employee_academic_user_info_address;
import com.fourgenius.www.public_access.model.academic_employee.employee_academic_user_info_contact;
import com.fourgenius.www.public_access.model.academic_employee.employee_academic_user_info_name;
import com.fourgenius.www.public_access.model.academic_employee.employee_academic_user_info_personal;
import com.fourgenius.www.public_access.model.student.stu_exams_info;
import static com.fourgenius.www.public_access.registration.student.Jp_registration_student.Jp_registraion_stu_main_panel;
import static com.fourgenius.www.public_access.registration.student.Jp_registration_student._bt_add_student;
import static com.fourgenius.www.public_access.registration.student.Jp_registration_student._bt_student_details;
import com.fourgenius.www.public_access.registration.student.Jp_registration_student_c_layout;
import static com.fourgenius.www.public_access.registration.student.Jp_registration_student_informations._lb_registration_student_preview_course;
import static com.fourgenius.www.public_access.registration.student.Jp_registration_student_informations._lb_registration_student_preview_dateOfBirth;
import com.fourgenius.www.public_access.registration.student.user_image_copy;
import com.googlecode.javacv.CanvasFrame;
import com.googlecode.javacv.OpenCVFrameGrabber;
import com.googlecode.javacv.cpp.opencv_core;
import com.googlecode.javacv.cpp.opencv_highgui;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;
import public_access.MC_JavaDataBaseConnection;

/**
 *
 * @author thilina
 */
public class Jp_add_exams_informations extends javax.swing.JPanel {

//  Set Button Border Collor
    Border border = BorderFactory.createLineBorder(Color.white, 1);

//  Crate variables for lecture image path
    public String path, newpath;

//  Create variables for get lecture full name
    public String sur_name, first_name, last_name;

//  Create variable for pass to qulification form
    public String exam_id;
    public int id_no;
    public String branch_name;
    public String full_name;

    /**
     * d
     * Creates new form registration_lecture
     */
    public Jp_add_exams_informations() {
        initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
        set_data_to_Combo_box();
//      Set min selectable date for validate date of birth
        Date d = Calendar.getInstance().getTime();
        _dc_add_exam_examDate.setMinSelectableDate(d);
        _bt_add_exam_preview_addExam.setEnabled(false);
    }

    public Jp_add_exams_informations(String ex_id) {
        initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
        set_data_to_Combo_box();
        exam_id = ex_id;
        load_form_data(ex_id);
        Date d = Calendar.getInstance().getTime();
        _dc_add_exam_examDate.setMinSelectableDate(d);
        _bt_add_exam_preview_addExam.setText("Update Exam");
        _bt_add_exam_preview.setText("Preview Update");
        _bt_add_exam_preview_addExam.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _bg_registration_lecture_personalInformations_employeeDetails_acadamy = new javax.swing.ButtonGroup();
        _bg_registration_lecture_personalInformations_employeeDetails_gender = new javax.swing.ButtonGroup();
        _bg_registration_lecture_personalInformation_employeeDetails_branch = new javax.swing.ButtonGroup();
        _pl_add_exams_examInformation_main_panel = new javax.swing.JPanel();
        _pl_add_exam_examInformation = new javax.swing.JPanel();
        _lb_add_exam_name = new javax.swing.JLabel();
        _tf_add_exam_name = new javax.swing.JTextField();
        _lb_add_exam_course_name = new javax.swing.JLabel();
        _cb_add_exam_course = new javax.swing.JComboBox();
        _lb_add_exam_examDate = new javax.swing.JLabel();
        _dc_add_exam_examDate = new com.toedter.calendar.JDateChooser();
        _lb_add_exam_branch = new javax.swing.JLabel();
        _rb_add_exam_colombo = new javax.swing.JRadioButton();
        _rb_add_exam_kandy = new javax.swing.JRadioButton();
        _bt_add_exam_preview = new javax.swing.JButton();
        _lb_add_batch_number = new javax.swing.JLabel();
        _cb_add_exam_batch = new javax.swing.JComboBox();
        _pl_add_exam_examInformation_preview = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        _lb_add_exam_preview_examID = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        _lb_add_exam_preview_name = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        _lb_add_exam_preview_course = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        _lb_add_exam_preview_date = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        _lb_add_exam_preview_branch = new javax.swing.JLabel();
        _bt_add_exam_preview_addExam = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        _lb_add_exam_preview_btach_number = new javax.swing.JLabel();
        _pl_registration_lecture_personalInformation_browsePhoto1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(66, 66, 66));
        setMinimumSize(new java.awt.Dimension(1366, 718));
        setPreferredSize(new java.awt.Dimension(1366, 718));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        _pl_add_exams_examInformation_main_panel.setBackground(new java.awt.Color(2, 119, 189));
        _pl_add_exams_examInformation_main_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exam Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        _pl_add_exams_examInformation_main_panel.setMaximumSize(new java.awt.Dimension(32767, 695));
        _pl_add_exams_examInformation_main_panel.setMinimumSize(new java.awt.Dimension(0, 695));
        _pl_add_exams_examInformation_main_panel.setPreferredSize(new java.awt.Dimension(815, 695));
        _pl_add_exams_examInformation_main_panel.setLayout(new java.awt.CardLayout());

        _pl_add_exam_examInformation.setBackground(new java.awt.Color(2, 119, 189));
        _pl_add_exam_examInformation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        _lb_add_exam_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_add_exam_name.setForeground(new java.awt.Color(255, 255, 255));
        _lb_add_exam_name.setText("Exam Name");
        _pl_add_exam_examInformation.add(_lb_add_exam_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 333, -1));

        _tf_add_exam_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _tf_add_exam_name.setMaximumSize(new java.awt.Dimension(300, 40));
        _tf_add_exam_name.setPreferredSize(new java.awt.Dimension(300, 40));
        _tf_add_exam_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_add_exam_nameActionPerformed(evt);
            }
        });
        _tf_add_exam_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _tf_add_exam_nameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                _tf_add_exam_nameKeyTyped(evt);
            }
        });
        _pl_add_exam_examInformation.add(_tf_add_exam_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 333, -1));

        _lb_add_exam_course_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_add_exam_course_name.setForeground(new java.awt.Color(255, 255, 255));
        _lb_add_exam_course_name.setText("Course");
        _pl_add_exam_examInformation.add(_lb_add_exam_course_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 333, -1));

        _cb_add_exam_course.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _pl_add_exam_examInformation.add(_cb_add_exam_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 333, 40));

        _lb_add_exam_examDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_add_exam_examDate.setForeground(new java.awt.Color(255, 255, 255));
        _lb_add_exam_examDate.setText("Exam Date");
        _pl_add_exam_examInformation.add(_lb_add_exam_examDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 333, -1));

        _dc_add_exam_examDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _dc_add_exam_examDate.setPreferredSize(new java.awt.Dimension(91, 40));
        _dc_add_exam_examDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _dc_add_exam_examDateMouseClicked(evt);
            }
        });
        _pl_add_exam_examInformation.add(_dc_add_exam_examDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 333, -1));

        _lb_add_exam_branch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_add_exam_branch.setForeground(new java.awt.Color(255, 255, 255));
        _lb_add_exam_branch.setText("Branch");
        _pl_add_exam_examInformation.add(_lb_add_exam_branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        _rb_add_exam_colombo.setBackground(new java.awt.Color(2, 119, 189));
        _bg_registration_lecture_personalInformation_employeeDetails_branch.add(_rb_add_exam_colombo);
        _rb_add_exam_colombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _rb_add_exam_colombo.setForeground(new java.awt.Color(255, 255, 255));
        _rb_add_exam_colombo.setSelected(true);
        _rb_add_exam_colombo.setText("Colombo");
        _pl_add_exam_examInformation.add(_rb_add_exam_colombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        _rb_add_exam_kandy.setBackground(new java.awt.Color(2, 119, 189));
        _bg_registration_lecture_personalInformation_employeeDetails_branch.add(_rb_add_exam_kandy);
        _rb_add_exam_kandy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _rb_add_exam_kandy.setForeground(new java.awt.Color(255, 255, 255));
        _rb_add_exam_kandy.setText("Kandy");
        _rb_add_exam_kandy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _rb_add_exam_kandyActionPerformed(evt);
            }
        });
        _pl_add_exam_examInformation.add(_rb_add_exam_kandy, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        _bt_add_exam_preview.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _bt_add_exam_preview.setForeground(new java.awt.Color(255, 255, 255));
        _bt_add_exam_preview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/buton_blue_250x50.png"))); // NOI18N
        _bt_add_exam_preview.setText("Preview");
        _bt_add_exam_preview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _bt_add_exam_preview.setFocusPainted(false);
        _bt_add_exam_preview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _bt_add_exam_preview.setPreferredSize(new java.awt.Dimension(300, 50));
        _bt_add_exam_preview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _bt_add_exam_previewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _bt_add_exam_previewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _bt_add_exam_previewMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _bt_add_exam_previewMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                _bt_add_exam_previewMouseReleased(evt);
            }
        });
        _bt_add_exam_preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _bt_add_exam_previewActionPerformed(evt);
            }
        });
        _pl_add_exam_examInformation.add(_bt_add_exam_preview, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 244, -1));

        _lb_add_batch_number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_add_batch_number.setForeground(new java.awt.Color(255, 255, 255));
        _lb_add_batch_number.setText("Batch Number");
        _pl_add_exam_examInformation.add(_lb_add_batch_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 333, -1));

        _cb_add_exam_batch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02" }));
        _pl_add_exam_examInformation.add(_cb_add_exam_batch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 330, 40));

        _pl_add_exams_examInformation_main_panel.add(_pl_add_exam_examInformation, "card2");

        add(_pl_add_exams_examInformation_main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 810, 620));

        _pl_add_exam_examInformation_preview.setBackground(new java.awt.Color(117, 117, 117));
        _pl_add_exam_examInformation_preview.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Exam ID");

        _lb_add_exam_preview_examID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Exam Name");

        _lb_add_exam_preview_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Course");

        _lb_add_exam_preview_course.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Exam Date");

        _lb_add_exam_preview_date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Branch");

        _lb_add_exam_preview_branch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        _bt_add_exam_preview_addExam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _bt_add_exam_preview_addExam.setForeground(new java.awt.Color(255, 255, 255));
        _bt_add_exam_preview_addExam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/buton_DarkGreen_200x50.png"))); // NOI18N
        _bt_add_exam_preview_addExam.setText("Add Exam");
        _bt_add_exam_preview_addExam.setContentAreaFilled(false);
        _bt_add_exam_preview_addExam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _bt_add_exam_preview_addExam.setFocusPainted(false);
        _bt_add_exam_preview_addExam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _bt_add_exam_preview_addExam.setPreferredSize(new java.awt.Dimension(100, 50));
        _bt_add_exam_preview_addExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _bt_add_exam_preview_addExamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _bt_add_exam_preview_addExamMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _bt_add_exam_preview_addExamMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                _bt_add_exam_preview_addExamMouseReleased(evt);
            }
        });
        _bt_add_exam_preview_addExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _bt_add_exam_preview_addExamActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Batch Number");

        _lb_add_exam_preview_btach_number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout _pl_add_exam_examInformation_previewLayout = new javax.swing.GroupLayout(_pl_add_exam_examInformation_preview);
        _pl_add_exam_examInformation_preview.setLayout(_pl_add_exam_examInformation_previewLayout);
        _pl_add_exam_examInformation_previewLayout.setHorizontalGroup(
            _pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pl_add_exam_examInformation_previewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _pl_add_exam_examInformation_previewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(_bt_add_exam_preview_addExam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(_pl_add_exam_examInformation_previewLayout.createSequentialGroup()
                        .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_lb_add_exam_preview_examID, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                            .addComponent(_lb_add_exam_preview_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_lb_add_exam_preview_course, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_lb_add_exam_preview_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_lb_add_exam_preview_branch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_lb_add_exam_preview_btach_number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        _pl_add_exam_examInformation_previewLayout.setVerticalGroup(
            _pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pl_add_exam_examInformation_previewLayout.createSequentialGroup()
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_add_exam_preview_examID, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_add_exam_preview_name, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(_lb_add_exam_preview_btach_number, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_add_exam_preview_course, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_add_exam_preview_date, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_add_exam_preview_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(392, 392, 392)
                .addComponent(_bt_add_exam_preview_addExam, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(_pl_add_exam_examInformation_preview, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 526, 620));

        _pl_registration_lecture_personalInformation_browsePhoto1.setBackground(new java.awt.Color(2, 119, 189));
        _pl_registration_lecture_personalInformation_browsePhoto1.setPreferredSize(new java.awt.Dimension(766, 123));

        javax.swing.GroupLayout _pl_registration_lecture_personalInformation_browsePhoto1Layout = new javax.swing.GroupLayout(_pl_registration_lecture_personalInformation_browsePhoto1);
        _pl_registration_lecture_personalInformation_browsePhoto1.setLayout(_pl_registration_lecture_personalInformation_browsePhoto1Layout);
        _pl_registration_lecture_personalInformation_browsePhoto1Layout.setHorizontalGroup(
            _pl_registration_lecture_personalInformation_browsePhoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        _pl_registration_lecture_personalInformation_browsePhoto1Layout.setVerticalGroup(
            _pl_registration_lecture_personalInformation_browsePhoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        add(_pl_registration_lecture_personalInformation_browsePhoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 810, 60));
    }// </editor-fold>//GEN-END:initComponents


    private void _bt_add_exam_previewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_previewMouseEntered
        _bt_add_exam_preview.setBorder(border);
    }//GEN-LAST:event__bt_add_exam_previewMouseEntered

    private void _bt_add_exam_previewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_previewMouseExited
        _bt_add_exam_preview.setBorder(null);
    }//GEN-LAST:event__bt_add_exam_previewMouseExited

    private void _bt_add_exam_previewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_previewMousePressed
        _bt_add_exam_preview.setBorder(null);
    }//GEN-LAST:event__bt_add_exam_previewMousePressed

    private void _bt_add_exam_previewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_previewMouseReleased
        _bt_add_exam_preview.setBorder(border);
    }//GEN-LAST:event__bt_add_exam_previewMouseReleased

    private void _bt_add_exam_previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__bt_add_exam_previewActionPerformed
        if (_bt_add_exam_preview.getText().equals("Preview")) {

            check_empty_fields();
        } else {

            check_update_empty_fields();
        }
    }//GEN-LAST:event__bt_add_exam_previewActionPerformed

    private void _bt_add_exam_previewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_previewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event__bt_add_exam_previewMouseClicked

    private void _bt_add_exam_preview_addExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__bt_add_exam_preview_addExamActionPerformed

        try {
            if (_bt_add_exam_preview_addExam.getText().equals("Add Exam")) {
                int option = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Confirm?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (option == JOptionPane.YES_OPTION) {
                    add_to_database();
                    load_table_view();
                    _bt_add_exam_AddExam.setText("Add Exam");
                    _bt_add_exam_ExamsDetails.setEnabled(true);
                    _bt_UserMain_home.setEnabled(true);
                }
            } else {
                int option = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Confirm?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (option == JOptionPane.YES_OPTION) {
                    add_to_database();
                    load_table_view();
                    _bt_add_exam_AddExam.setText("Add Exam");
                    _bt_add_exam_ExamsDetails.setEnabled(true);
                    _bt_UserMain_home.setEnabled(true);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event__bt_add_exam_preview_addExamActionPerformed

    private void _bt_add_exam_preview_addExamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_preview_addExamMouseEntered
        _bt_add_exam_preview_addExam.setBorder(border);
    }//GEN-LAST:event__bt_add_exam_preview_addExamMouseEntered

    private void _bt_add_exam_preview_addExamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_preview_addExamMouseExited
        _bt_add_exam_preview_addExam.setBorder(null);
    }//GEN-LAST:event__bt_add_exam_preview_addExamMouseExited

    private void _bt_add_exam_preview_addExamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_preview_addExamMousePressed
        _bt_add_exam_preview_addExam.setBorder(null);
    }//GEN-LAST:event__bt_add_exam_preview_addExamMousePressed

    private void _bt_add_exam_preview_addExamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_preview_addExamMouseReleased
        _bt_add_exam_preview_addExam.setBorder(border);
    }//GEN-LAST:event__bt_add_exam_preview_addExamMouseReleased

    private void _rb_add_exam_kandyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__rb_add_exam_kandyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__rb_add_exam_kandyActionPerformed

    private void _dc_add_exam_examDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__dc_add_exam_examDateMouseClicked

    }//GEN-LAST:event__dc_add_exam_examDateMouseClicked

    private void _tf_add_exam_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_add_exam_nameKeyTyped

    }//GEN-LAST:event__tf_add_exam_nameKeyTyped

    private void _tf_add_exam_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_add_exam_nameKeyReleased

    }//GEN-LAST:event__tf_add_exam_nameKeyReleased

    private void _tf_add_exam_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_add_exam_nameActionPerformed

    }//GEN-LAST:event__tf_add_exam_nameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup _bg_registration_lecture_personalInformation_employeeDetails_branch;
    private javax.swing.ButtonGroup _bg_registration_lecture_personalInformations_employeeDetails_acadamy;
    private javax.swing.ButtonGroup _bg_registration_lecture_personalInformations_employeeDetails_gender;
    private javax.swing.JButton _bt_add_exam_preview;
    private javax.swing.JButton _bt_add_exam_preview_addExam;
    private javax.swing.JComboBox _cb_add_exam_batch;
    private javax.swing.JComboBox _cb_add_exam_course;
    public com.toedter.calendar.JDateChooser _dc_add_exam_examDate;
    private javax.swing.JLabel _lb_add_batch_number;
    private javax.swing.JLabel _lb_add_exam_branch;
    private javax.swing.JLabel _lb_add_exam_course_name;
    private javax.swing.JLabel _lb_add_exam_examDate;
    private javax.swing.JLabel _lb_add_exam_name;
    private javax.swing.JLabel _lb_add_exam_preview_branch;
    private javax.swing.JLabel _lb_add_exam_preview_btach_number;
    private javax.swing.JLabel _lb_add_exam_preview_course;
    private javax.swing.JLabel _lb_add_exam_preview_date;
    private javax.swing.JLabel _lb_add_exam_preview_examID;
    public javax.swing.JLabel _lb_add_exam_preview_name;
    private javax.swing.JPanel _pl_add_exam_examInformation;
    private javax.swing.JPanel _pl_add_exam_examInformation_preview;
    private javax.swing.JPanel _pl_add_exams_examInformation_main_panel;
    private javax.swing.JPanel _pl_registration_lecture_personalInformation_browsePhoto1;
    public javax.swing.JRadioButton _rb_add_exam_colombo;
    public javax.swing.JRadioButton _rb_add_exam_kandy;
    private static javax.swing.JTextField _tf_add_exam_name;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    // End of variables declaration//GEN-END:variables

    private void button_enable(String button_name) {
        try {

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void add_to_preview_form() {
        try {
            generate_exam_id();
            _lb_add_exam_preview_name.setText(_tf_add_exam_name.getText());
            _lb_add_exam_preview_btach_number.setText((String) _cb_add_exam_batch.getSelectedItem());
            _lb_add_exam_preview_course.setText((String) _cb_add_exam_course.getSelectedItem());
            Date d = _dc_add_exam_examDate.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(d);
            _lb_add_exam_preview_date.setText(date);

            String branch;
            if (_rb_add_exam_colombo.isSelected()) {
                branch = "Colombo";
            } else {
                branch = "Kandy";
            }
            _lb_add_exam_preview_branch.setText(branch);

            _bt_add_exam_preview_addExam.setEnabled(true);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void generate_exam_id() {

        String id = "ID";
        String ex = "EXM";

        stu_exams_info exam_info = new stu_exams_info();
        String countid = exam_info.getidstu_exams_info();
        int idcount = Integer.parseInt(countid);
        id_no = ++idcount;

        String a = Integer.toString(id_no);
        int length = a.length();
        System.out.println(length);

        String idn = Integer.toString(id_no);
        String zeros;
        if (length == 1) {
            zeros = "00000";
        } else if (length == 2) {
            zeros = "0000";
        } else if (length == 3) {
            zeros = "000";
        } else if (length == 4) {
            zeros = "00";
        } else if (length == 5) {
            zeros = "0";
        } else {
            zeros = "";
        }

        if (_rb_add_exam_colombo.isSelected()) {
            branch_name = "COL";
        } else {
            branch_name = "KAN";
        }

        exam_id = id + "-" + ex + "-" + branch_name + "-" + zeros + id_no;
        _lb_add_exam_preview_examID.setText(exam_id);

    }

    private void add_to_database() {
        stu_exams_info exam_info = new stu_exams_info(_lb_add_exam_preview_examID.getText(), _lb_add_exam_preview_name.getText(), _lb_add_exam_preview_date.getText(), "1", _lb_add_exam_preview_branch.getText(), _lb_add_exam_preview_btach_number.getText(), _lb_add_exam_preview_course.getText());
    }

    private void load_form_data(String id) {
        try {
            Connection c = MC_JavaDataBaseConnection.myConnection();
            Statement s = c.createStatement();

            ResultSet rs_info = s.executeQuery("SELECT * FROM stu_exams_info WHERE stu_exams_info_id='" + id + "'");
            if (rs_info.next()) {
                _tf_add_exam_name.setText(rs_info.getString("stu_exams_info_name"));
                _cb_add_exam_batch.setSelectedItem(rs_info.getString("stu_exams_info_batch"));

                String course = rs_info.getString("stu_exams_info_course");
                _cb_add_exam_course.setSelectedItem(course);

                _dc_add_exam_examDate.setDate(rs_info.getDate("stu_exams_info_date"));

                String branch = rs_info.getString("stu_exams_info_branch");
                if (branch.equals("Colombo")) {
                    _rb_add_exam_colombo.setSelected(true);
                } else {
                    _rb_add_exam_kandy.setSelected(true);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void set_data_to_Combo_box() {
        try {
            ResultSet rs;
            String sql = "SELECT * FROM `stu_exam_courses_info";
            rs = MC_JavaDataBaseConnection.myConnection().createStatement().executeQuery(sql);

            while (rs.next()) {
                String name = rs.getString("stu_exam_courses_info_name");
                _cb_add_exam_course.addItem(name);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void check_empty_fields() {
        if (!_tf_add_exam_name.getText().isEmpty()) {
            add_to_preview_form();
        } else {
            JOptionPane.showMessageDialog(this, "Exam Name is Empty!");
        }
    }

    private void check_update_empty_fields() {
        if (!_tf_add_exam_name.getText().isEmpty()) {
            add_to_update_preview_form();
        } else {
            JOptionPane.showMessageDialog(this, "Exam Name is Empty!");
        }
    }

    private void load_table_view() {
        Jp_add_exams_table_view table_preview = new Jp_add_exams_table_view();
        if (table_preview == null) {
            Jp_add_exams_main_panel.removeAll();
            revalidate();
            table_preview = new Jp_add_exams_table_view();
            table_preview.setVisible(true);
            Jp_add_exams_main_panel.add(table_preview);
            revalidate();
        } else {
            Jp_add_exams_main_panel.removeAll();
            revalidate();
            table_preview.setVisible(true);
            Jp_add_exams_main_panel.add(table_preview);
            revalidate();
        }
    }

    private void add_to_update_preview_form() {
        try {
            _lb_add_exam_preview_examID.setText(exam_id);
            _lb_add_exam_preview_name.setText(_tf_add_exam_name.getText());
            _lb_add_exam_preview_btach_number.setText((String) _cb_add_exam_batch.getSelectedItem());
            _lb_add_exam_preview_course.setText((String) _cb_add_exam_course.getSelectedItem());
            Date d = _dc_add_exam_examDate.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(d);
            _lb_add_exam_preview_date.setText(date);

            String branch;
            if (_rb_add_exam_colombo.isSelected()) {
                branch = "Colombo";
            } else {
                branch = "Kandy";
            }
            _lb_add_exam_preview_branch.setText(branch);

            _bt_add_exam_preview_addExam.setEnabled(true);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
