/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fourgenius.www.public_access.exams;

import static com.fourgenius.www.public_access.exams.Jp_add_exams.Jp_add_exams_main_panel;
import static com.fourgenius.www.public_access.exams.Jp_add_exams._bt_add_exam_AddExam;
import static com.fourgenius.www.public_access.exams.Jp_add_exams._bt_add_exam_ExamsDetails;
import com.fourgenius.www.public_access.registration.lecture.*;
import com.fourgenius.www.public_access.model.academic_employee.employee_academic_user_info;
import com.fourgenius.www.public_access.model.academic_employee.employee_academic_user_info_address;
import com.fourgenius.www.public_access.model.academic_employee.employee_academic_user_info_contact;
import com.fourgenius.www.public_access.model.academic_employee.employee_academic_user_info_name;
import com.fourgenius.www.public_access.model.academic_employee.employee_academic_user_info_personal;
import com.fourgenius.www.public_access.model.student.stu_exams_info;
import static com.fourgenius.www.public_access.registration.student.Jp_registration_student.Jp_registraion_stu_main_panel;
import static com.fourgenius.www.public_access.registration.student.Jp_registration_student._bt_add_student;
import static com.fourgenius.www.public_access.registration.student.Jp_registration_student._bt_student_details;
import com.fourgenius.www.public_access.registration.student.Jp_registration_student_c_layout;
import static com.fourgenius.www.public_access.registration.student.Jp_registration_student_informations._lb_registration_student_preview_course;
import static com.fourgenius.www.public_access.registration.student.Jp_registration_student_informations._lb_registration_student_preview_dateOfBirth;
import com.fourgenius.www.public_access.registration.student.user_image_copy;
import com.googlecode.javacv.CanvasFrame;
import com.googlecode.javacv.OpenCVFrameGrabber;
import com.googlecode.javacv.cpp.opencv_core;
import com.googlecode.javacv.cpp.opencv_highgui;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;
import public_access.MC_JavaDataBaseConnection;

/**
 *
 * @author thilina
 */
public class Jp_add_exams_student_marks extends javax.swing.JPanel {

//  Set Button Border Collor
    Border border = BorderFactory.createLineBorder(Color.white, 1);

    /**
     * d
     * Creates new form registration_lecture
     */
    public Jp_add_exams_student_marks() {
        initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
//      Set min selectable date for validate date of birth
        Date d = Calendar.getInstance().getTime();
        _bt_add_exam_preview_addExam.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _bg_registration_lecture_personalInformations_employeeDetails_acadamy = new javax.swing.ButtonGroup();
        _bg_registration_lecture_personalInformations_employeeDetails_gender = new javax.swing.ButtonGroup();
        _bg_registration_lecture_personalInformation_employeeDetails_branch = new javax.swing.ButtonGroup();
        _pl_add_exams_examInformation_main_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        _tb_add_marks_students = new javax.swing.JTable();
        _pl_add_exam_examInformation_preview = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        _lb_add_exam_preview_examID = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        _lb_add_exam_preview_name = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        _lb_add_exam_preview_course = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        _lb_add_exam_preview_date = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        _lb_add_exam_preview_branch = new javax.swing.JLabel();
        _bt_add_exam_preview_addExam = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        _lb_add_exam_preview_batach_number = new javax.swing.JLabel();

        setBackground(new java.awt.Color(66, 66, 66));
        setMinimumSize(new java.awt.Dimension(1366, 718));
        setPreferredSize(new java.awt.Dimension(1366, 718));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        _pl_add_exams_examInformation_main_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Students"));
        _pl_add_exams_examInformation_main_panel.setMaximumSize(new java.awt.Dimension(32767, 695));
        _pl_add_exams_examInformation_main_panel.setMinimumSize(new java.awt.Dimension(0, 695));
        _pl_add_exams_examInformation_main_panel.setPreferredSize(new java.awt.Dimension(815, 695));
        _pl_add_exams_examInformation_main_panel.setLayout(new java.awt.CardLayout());

        _tb_add_marks_students.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Batch", "Course", "Branch"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        _tb_add_marks_students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _tb_add_marks_studentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(_tb_add_marks_students);

        _pl_add_exams_examInformation_main_panel.add(jScrollPane1, "card2");

        add(_pl_add_exams_examInformation_main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 810, 610));

        _pl_add_exam_examInformation_preview.setBackground(new java.awt.Color(117, 117, 117));
        _pl_add_exam_examInformation_preview.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Student ID");

        _lb_add_exam_preview_examID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Student Name");

        _lb_add_exam_preview_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Result");

        _lb_add_exam_preview_course.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Exam Date");

        _lb_add_exam_preview_date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Branch");

        _lb_add_exam_preview_branch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        _bt_add_exam_preview_addExam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _bt_add_exam_preview_addExam.setForeground(new java.awt.Color(255, 255, 255));
        _bt_add_exam_preview_addExam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/buton_DarkGreen_200x50.png"))); // NOI18N
        _bt_add_exam_preview_addExam.setText("Add Exam");
        _bt_add_exam_preview_addExam.setContentAreaFilled(false);
        _bt_add_exam_preview_addExam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _bt_add_exam_preview_addExam.setFocusPainted(false);
        _bt_add_exam_preview_addExam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _bt_add_exam_preview_addExam.setPreferredSize(new java.awt.Dimension(100, 50));
        _bt_add_exam_preview_addExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _bt_add_exam_preview_addExamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _bt_add_exam_preview_addExamMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _bt_add_exam_preview_addExamMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                _bt_add_exam_preview_addExamMouseReleased(evt);
            }
        });
        _bt_add_exam_preview_addExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _bt_add_exam_preview_addExamActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Marks");

        _lb_add_exam_preview_batach_number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout _pl_add_exam_examInformation_previewLayout = new javax.swing.GroupLayout(_pl_add_exam_examInformation_preview);
        _pl_add_exam_examInformation_preview.setLayout(_pl_add_exam_examInformation_previewLayout);
        _pl_add_exam_examInformation_previewLayout.setHorizontalGroup(
            _pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pl_add_exam_examInformation_previewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _pl_add_exam_examInformation_previewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(_bt_add_exam_preview_addExam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(_pl_add_exam_examInformation_previewLayout.createSequentialGroup()
                        .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_lb_add_exam_preview_examID, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                            .addComponent(_lb_add_exam_preview_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_lb_add_exam_preview_course, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_lb_add_exam_preview_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_lb_add_exam_preview_branch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_lb_add_exam_preview_batach_number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        _pl_add_exam_examInformation_previewLayout.setVerticalGroup(
            _pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_pl_add_exam_examInformation_previewLayout.createSequentialGroup()
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_add_exam_preview_examID, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_add_exam_preview_name, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(_lb_add_exam_preview_batach_number, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_add_exam_preview_course, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_add_exam_preview_date, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(_pl_add_exam_examInformation_previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_lb_add_exam_preview_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                .addComponent(_bt_add_exam_preview_addExam, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(_pl_add_exam_examInformation_preview, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 526, 610));
    }// </editor-fold>//GEN-END:initComponents


    private void _bt_add_exam_preview_addExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__bt_add_exam_preview_addExamActionPerformed

        


    }//GEN-LAST:event__bt_add_exam_preview_addExamActionPerformed

    private void _bt_add_exam_preview_addExamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_preview_addExamMouseEntered
        _bt_add_exam_preview_addExam.setBorder(border);
    }//GEN-LAST:event__bt_add_exam_preview_addExamMouseEntered

    private void _bt_add_exam_preview_addExamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_preview_addExamMouseExited
        _bt_add_exam_preview_addExam.setBorder(null);
    }//GEN-LAST:event__bt_add_exam_preview_addExamMouseExited

    private void _bt_add_exam_preview_addExamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_preview_addExamMousePressed
        _bt_add_exam_preview_addExam.setBorder(null);
    }//GEN-LAST:event__bt_add_exam_preview_addExamMousePressed

    private void _bt_add_exam_preview_addExamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_add_exam_preview_addExamMouseReleased
        _bt_add_exam_preview_addExam.setBorder(border);
    }//GEN-LAST:event__bt_add_exam_preview_addExamMouseReleased

    private void _tb_add_marks_studentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__tb_add_marks_studentsMouseClicked

    }//GEN-LAST:event__tb_add_marks_studentsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup _bg_registration_lecture_personalInformation_employeeDetails_branch;
    private javax.swing.ButtonGroup _bg_registration_lecture_personalInformations_employeeDetails_acadamy;
    private javax.swing.ButtonGroup _bg_registration_lecture_personalInformations_employeeDetails_gender;
    private javax.swing.JButton _bt_add_exam_preview_addExam;
    private javax.swing.JLabel _lb_add_exam_preview_batach_number;
    private javax.swing.JLabel _lb_add_exam_preview_branch;
    private javax.swing.JLabel _lb_add_exam_preview_course;
    private javax.swing.JLabel _lb_add_exam_preview_date;
    private javax.swing.JLabel _lb_add_exam_preview_examID;
    private javax.swing.JLabel _lb_add_exam_preview_name;
    private javax.swing.JPanel _pl_add_exam_examInformation_preview;
    private javax.swing.JPanel _pl_add_exams_examInformation_main_panel;
    private javax.swing.JTable _tb_add_marks_students;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
