/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fourgenius.www.public_access.user.login;

import com.fourgenius.www.admin_BackEnd.Jf_admin_backend;
import com.fourgenius.www.private_access.admin.login.Jf_admin_login;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import com.fourgenius.www.qrGenerator.Md_QrCodeGenarater;
import com.fourgenius.www.private_access.admin.method.Md_move_text;
import com.fourgenius.www.user_FrontEnd.Jf_UserMain;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author deepal_suranga
 */
public class Jf_user_login extends javax.swing.JFrame {

    Border border=BorderFactory.createLineBorder(Color.white, 1);
    /**
     * Creates new form user_login
     */
    Md_move_text setLableValuesNullAndAdd = new Md_move_text();

    public Jf_user_login() {
        initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }

        Md_QrCodeGenarater code_Gen = new Md_QrCodeGenarater();
        code_Gen.load_qr(_lb_user_login_qrCode);

        setLableValuesNullAndAdd._md_setLableValuesNull(_lb_user_login_userName);
        setLableValuesNullAndAdd._md_setLableValuesNull(_lb_user_login_password);
        setLableValuesNullAndAdd._md_setLableValuesNull(_lb_user_login_pin);
        setLableValuesNullAndAdd._md_setTextFieldValues(_tf_user_loging_userName, "User Name");
        setLableValuesNullAndAdd._md_setPasswordFieldvalues(_pf_user_login_password, "Password");
        _pf_user_login_password.setEchoChar((char) 0);
        setLableValuesNullAndAdd._md_setTextFieldValues(_tf_user_login_pin, "Enter PIN Code");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Middle = new javax.swing.JPanel();
        Top = new javax.swing.JPanel();
        _lb_user_login_close = new javax.swing.JLabel();
        _lb_user_login_minimize = new javax.swing.JLabel();
        _lb_user_login_userName = new javax.swing.JLabel();
        _tf_user_loging_userName = new javax.swing.JTextField();
        _lb_user_login_password = new javax.swing.JLabel();
        _pf_user_login_password = new javax.swing.JPasswordField();
        _lb_user_login_qrCode = new javax.swing.JLabel();
        _lb_user_login_showPassword = new javax.swing.JLabel();
        _lb_user_login_pin = new javax.swing.JLabel();
        _tf_user_login_pin = new javax.swing.JTextField();
        _lb_user_login_seperator = new javax.swing.JLabel();
        _lb_user_login_logo = new javax.swing.JLabel();
        _lb_user_login_forgotPassword = new javax.swing.JLabel();
        _lb_user_login_showPassword1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        _bt_Jf_user_login_Login = new javax.swing.JButton();
        _bt_Jf_user_login_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Middle.setBackground(new java.awt.Color(2, 119, 189));
        Middle.setPreferredSize(new java.awt.Dimension(1370, 770));

        Top.setBackground(new java.awt.Color(18, 75, 163));
        Top.setPreferredSize(new java.awt.Dimension(1366, 60));

        _lb_user_login_close.setBackground(new java.awt.Color(18, 75, 163));
        _lb_user_login_close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _lb_user_login_close.setForeground(new java.awt.Color(255, 255, 255));
        _lb_user_login_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lb_user_login_close.setText("X");
        _lb_user_login_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _lb_user_login_close.setOpaque(true);
        _lb_user_login_close.setPreferredSize(new java.awt.Dimension(25, 25));
        _lb_user_login_close.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                _lb_user_login_closeMouseMoved(evt);
            }
        });
        _lb_user_login_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _lb_user_login_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _lb_user_login_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _lb_user_login_closeMouseExited(evt);
            }
        });

        _lb_user_login_minimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        _lb_user_login_minimize.setForeground(new java.awt.Color(255, 255, 255));
        _lb_user_login_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lb_user_login_minimize.setText("-");
        _lb_user_login_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _lb_user_login_minimize.setPreferredSize(new java.awt.Dimension(25, 25));
        _lb_user_login_minimize.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                _lb_user_login_minimizeMouseMoved(evt);
            }
        });
        _lb_user_login_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _lb_user_login_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _lb_user_login_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _lb_user_login_minimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_lb_user_login_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lb_user_login_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_lb_user_login_close, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_lb_user_login_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        _lb_user_login_userName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_user_login_userName.setForeground(new java.awt.Color(255, 255, 255));
        _lb_user_login_userName.setText("User Name");

        _tf_user_loging_userName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _tf_user_loging_userName.setPreferredSize(new java.awt.Dimension(300, 40));
        _tf_user_loging_userName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _tf_user_loging_userNameMouseClicked(evt);
            }
        });
        _tf_user_loging_userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tf_user_loging_userNameActionPerformed(evt);
            }
        });
        _tf_user_loging_userName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                _tf_user_loging_userNameKeyTyped(evt);
            }
        });

        _lb_user_login_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_user_login_password.setForeground(new java.awt.Color(240, 240, 240));
        _lb_user_login_password.setText("Password");

        _pf_user_login_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _pf_user_login_password.setPreferredSize(new java.awt.Dimension(300, 40));
        _pf_user_login_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _pf_user_login_passwordMouseClicked(evt);
            }
        });
        _pf_user_login_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _pf_user_login_passwordActionPerformed(evt);
            }
        });
        _pf_user_login_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                _pf_user_login_passwordKeyTyped(evt);
            }
        });

        _lb_user_login_qrCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        _lb_user_login_qrCode.setPreferredSize(new java.awt.Dimension(125, 125));

        _lb_user_login_showPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lb_user_login_showPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images/img_ShowPassword.png"))); // NOI18N
        _lb_user_login_showPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _lb_user_login_showPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _lb_user_login_showPasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                _lb_user_login_showPasswordMouseReleased(evt);
            }
        });

        _lb_user_login_pin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_user_login_pin.setForeground(new java.awt.Color(255, 255, 255));
        _lb_user_login_pin.setText("Enter PIN Code");

        _tf_user_login_pin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _tf_user_login_pin.setMinimumSize(new java.awt.Dimension(6, 40));
        _tf_user_login_pin.setPreferredSize(new java.awt.Dimension(59, 40));
        _tf_user_login_pin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _tf_user_login_pinMouseClicked(evt);
            }
        });
        _tf_user_login_pin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                _tf_user_login_pinKeyTyped(evt);
            }
        });

        _lb_user_login_seperator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images/img_SaperateBar.png"))); // NOI18N

        _lb_user_login_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images/img_RamaniAccademyLogo600x200_1.png"))); // NOI18N
        _lb_user_login_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _lb_user_login_logo.setPreferredSize(new java.awt.Dimension(200, 100));
        _lb_user_login_logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _lb_user_login_logoMouseClicked(evt);
            }
        });

        _lb_user_login_forgotPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lb_user_login_forgotPassword.setForeground(new java.awt.Color(255, 255, 255));
        _lb_user_login_forgotPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        _lb_user_login_forgotPassword.setText("Forgot Password?");
        _lb_user_login_forgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _lb_user_login_forgotPassword.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        _lb_user_login_forgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _lb_user_login_forgotPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _lb_user_login_forgotPasswordMouseExited(evt);
            }
        });

        _lb_user_login_showPassword1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _lb_user_login_showPassword1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images/img_UsernameInformation.png"))); // NOI18N
        _lb_user_login_showPassword1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _lb_user_login_showPassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _lb_user_login_showPassword1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                _lb_user_login_showPassword1MouseReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(18, 75, 163));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images/img_AccountCircleWhite192x192.png"))); // NOI18N

        _bt_Jf_user_login_Login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _bt_Jf_user_login_Login.setForeground(new java.awt.Color(255, 255, 255));
        _bt_Jf_user_login_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/button_blue_300x50.png"))); // NOI18N
        _bt_Jf_user_login_Login.setText("Login");
        _bt_Jf_user_login_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _bt_Jf_user_login_Login.setFocusPainted(false);
        _bt_Jf_user_login_Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _bt_Jf_user_login_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _bt_Jf_user_login_LoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _bt_Jf_user_login_LoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _bt_Jf_user_login_LoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _bt_Jf_user_login_LoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                _bt_Jf_user_login_LoginMouseReleased(evt);
            }
        });
        _bt_Jf_user_login_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _bt_Jf_user_login_LoginActionPerformed(evt);
            }
        });

        _bt_Jf_user_login_Cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _bt_Jf_user_login_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        _bt_Jf_user_login_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/button_blue_300x50.png"))); // NOI18N
        _bt_Jf_user_login_Cancel.setText("Cancel");
        _bt_Jf_user_login_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _bt_Jf_user_login_Cancel.setFocusPainted(false);
        _bt_Jf_user_login_Cancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _bt_Jf_user_login_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _bt_Jf_user_login_CancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _bt_Jf_user_login_CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _bt_Jf_user_login_CancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _bt_Jf_user_login_CancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                _bt_Jf_user_login_CancelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout MiddleLayout = new javax.swing.GroupLayout(Middle);
        Middle.setLayout(MiddleLayout);
        MiddleLayout.setHorizontalGroup(
            MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddleLayout.createSequentialGroup()
                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Top, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE)
                    .addGroup(MiddleLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(_lb_user_login_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(_lb_user_login_seperator)
                        .addGap(18, 18, 18)
                        .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_lb_user_login_forgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MiddleLayout.createSequentialGroup()
                                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MiddleLayout.createSequentialGroup()
                                        .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MiddleLayout.createSequentialGroup()
                                                .addComponent(_lb_user_login_qrCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(_tf_user_login_pin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(_lb_user_login_pin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(_pf_user_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(_lb_user_login_showPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(MiddleLayout.createSequentialGroup()
                                        .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(_lb_user_login_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(_lb_user_login_userName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(_tf_user_loging_userName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(_lb_user_login_showPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(_bt_Jf_user_login_Cancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(_bt_Jf_user_login_Login, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MiddleLayout.setVerticalGroup(
            MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddleLayout.createSequentialGroup()
                .addComponent(Top, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MiddleLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MiddleLayout.createSequentialGroup()
                                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MiddleLayout.createSequentialGroup()
                                        .addComponent(_lb_user_login_userName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(_tf_user_loging_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(_lb_user_login_showPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(_lb_user_login_password)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(_pf_user_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(_lb_user_login_showPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(MiddleLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(_lb_user_login_qrCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(MiddleLayout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(_lb_user_login_pin)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(_tf_user_login_pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_bt_Jf_user_login_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_bt_Jf_user_login_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_lb_user_login_forgotPassword))
                            .addComponent(_lb_user_login_seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MiddleLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(_lb_user_login_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(Middle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _lb_user_login_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_closeMouseClicked

        System.exit(0);

    }//GEN-LAST:event__lb_user_login_closeMouseClicked
    Border boder = BorderFactory.createLineBorder(Color.WHITE, 1);
    private void _lb_user_login_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_closeMouseEntered

        _lb_user_login_close.setBorder(boder);
        _lb_user_login_close.setBackground(Color.red);

        _lb_user_login_minimize.setToolTipText("Close");

    }//GEN-LAST:event__lb_user_login_closeMouseEntered

    private void _lb_user_login_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_closeMouseExited
        _lb_user_login_close.setBorder(null);
        _lb_user_login_close.setBackground(new Color(18,75,163));
    }//GEN-LAST:event__lb_user_login_closeMouseExited

    private void _lb_user_login_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_minimizeMouseEntered

        _lb_user_login_minimize.setToolTipText("Minimize");
        _lb_user_login_minimize.setBorder(boder);

    }//GEN-LAST:event__lb_user_login_minimizeMouseEntered

    private void _lb_user_login_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_minimizeMouseExited

        _lb_user_login_minimize.setBorder(null);

    }//GEN-LAST:event__lb_user_login_minimizeMouseExited

    private void _lb_user_login_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_minimizeMouseClicked

        this.setState(Jf_user_login.ICONIFIED);

    }//GEN-LAST:event__lb_user_login_minimizeMouseClicked

    private void _lb_user_login_showPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_showPasswordMousePressed

        _pf_user_login_password.setEchoChar((char) 0);

    }//GEN-LAST:event__lb_user_login_showPasswordMousePressed

    private void _lb_user_login_showPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_showPasswordMouseReleased

        _pf_user_login_password.setEchoChar('*');

    }//GEN-LAST:event__lb_user_login_showPasswordMouseReleased

    private void _lb_user_login_forgotPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_forgotPasswordMouseEntered

        _lb_user_login_forgotPassword.setText("<html><u>" + _lb_user_login_forgotPassword.getText() + "</u></html>");

    }//GEN-LAST:event__lb_user_login_forgotPasswordMouseEntered

    private void _lb_user_login_forgotPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_forgotPasswordMouseExited

        _lb_user_login_forgotPassword.setText("Forgot Password?");

    }//GEN-LAST:event__lb_user_login_forgotPasswordMouseExited

    private void _lb_user_login_showPassword1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_showPassword1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event__lb_user_login_showPassword1MousePressed

    private void _lb_user_login_showPassword1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_showPassword1MouseReleased

    }//GEN-LAST:event__lb_user_login_showPassword1MouseReleased

    private void _tf_user_loging_userNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__tf_user_loging_userNameMouseClicked

        setLableValuesNullAndAdd._md_textFiledToLabel(_tf_user_loging_userName, _lb_user_login_userName, "User Name");

    }//GEN-LAST:event__tf_user_loging_userNameMouseClicked

    int i = 0;
    private void _tf_user_loging_userNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_user_loging_userNameKeyTyped

        if (i < 1) {
            if (!(_tf_user_loging_userName.getText().isEmpty())) {
                setLableValuesNullAndAdd._md_textFiledToLabel(_tf_user_loging_userName, _lb_user_login_userName, "User Name");
                i++;
            }
        }

    }//GEN-LAST:event__tf_user_loging_userNameKeyTyped

    private void _tf_user_loging_userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tf_user_loging_userNameActionPerformed

        _pf_user_login_password.grabFocus();

    }//GEN-LAST:event__tf_user_loging_userNameActionPerformed

    private void _pf_user_login_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__pf_user_login_passwordMouseClicked

        setLableValuesNullAndAdd._md_passwordFiledToLabel(_pf_user_login_password, _lb_user_login_password, "Password");
        _pf_user_login_password.setEchoChar('*');

    }//GEN-LAST:event__pf_user_login_passwordMouseClicked
    int x = 0;
    private void _pf_user_login_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__pf_user_login_passwordKeyTyped

        if (x < 1) {

            if (!(_pf_user_login_password.getPassword().equals(""))) {

                setLableValuesNullAndAdd._md_passwordFiledToLabel(_pf_user_login_password, _lb_user_login_password, "Password");
                _pf_user_login_password.setEchoChar('*');
                x++;
            }

        }
    }//GEN-LAST:event__pf_user_login_passwordKeyTyped

    private void _tf_user_login_pinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__tf_user_login_pinMouseClicked

        setLableValuesNullAndAdd._md_textFiledToLabel(_tf_user_login_pin, _lb_user_login_pin, "Enter PIN Code");

    }//GEN-LAST:event__tf_user_login_pinMouseClicked

    int y = 0;
    private void _tf_user_login_pinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__tf_user_login_pinKeyTyped

        char c = evt.getKeyChar();
        if (_tf_user_login_pin.getText().length() == 4 || Character.isLetter(c)) {
            System.out.println("awa");
            evt.consume();
        }
        if (y < 1) {
            if (!(_tf_user_login_pin.getText().isEmpty())) {
                setLableValuesNullAndAdd._md_textFiledToLabel(_tf_user_login_pin, _lb_user_login_pin, "Enter PIN Code");
                y++;
            }
        }

    }//GEN-LAST:event__tf_user_login_pinKeyTyped

    private void _pf_user_login_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__pf_user_login_passwordActionPerformed

        _tf_user_login_pin.grabFocus();

    }//GEN-LAST:event__pf_user_login_passwordActionPerformed

    private void _lb_user_login_closeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_closeMouseMoved


    }//GEN-LAST:event__lb_user_login_closeMouseMoved

    private void _lb_user_login_minimizeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_minimizeMouseMoved


    }//GEN-LAST:event__lb_user_login_minimizeMouseMoved

    private void _lb_user_login_logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__lb_user_login_logoMouseClicked

        Jf_admin_login jf_admin_login = new Jf_admin_login();
        jf_admin_login.setVisible(true);
        this.dispose();

    }//GEN-LAST:event__lb_user_login_logoMouseClicked

    private void _bt_Jf_user_login_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_Jf_user_login_LoginMouseClicked
        
    }//GEN-LAST:event__bt_Jf_user_login_LoginMouseClicked

    private void _bt_Jf_user_login_LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_Jf_user_login_LoginMouseEntered
        _bt_Jf_user_login_Login.setBorder(border);
    }//GEN-LAST:event__bt_Jf_user_login_LoginMouseEntered

    private void _bt_Jf_user_login_LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_Jf_user_login_LoginMouseExited
        _bt_Jf_user_login_Login.setBorder(null);
    }//GEN-LAST:event__bt_Jf_user_login_LoginMouseExited

    private void _bt_Jf_user_login_LoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_Jf_user_login_LoginMousePressed
        _bt_Jf_user_login_Login.setBorder(null);
    }//GEN-LAST:event__bt_Jf_user_login_LoginMousePressed

    private void _bt_Jf_user_login_LoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_Jf_user_login_LoginMouseReleased
        _bt_Jf_user_login_Login.setBorder(border);
    }//GEN-LAST:event__bt_Jf_user_login_LoginMouseReleased

    private void _bt_Jf_user_login_CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_Jf_user_login_CancelMouseClicked
        System.exit(0);
    }//GEN-LAST:event__bt_Jf_user_login_CancelMouseClicked

    private void _bt_Jf_user_login_CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_Jf_user_login_CancelMouseEntered
        _bt_Jf_user_login_Cancel.setBorder(border);
    }//GEN-LAST:event__bt_Jf_user_login_CancelMouseEntered

    private void _bt_Jf_user_login_CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_Jf_user_login_CancelMouseExited
        _bt_Jf_user_login_Cancel.setBorder(null);
    }//GEN-LAST:event__bt_Jf_user_login_CancelMouseExited

    private void _bt_Jf_user_login_CancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_Jf_user_login_CancelMousePressed
        _bt_Jf_user_login_Cancel.setBorder(null);
    }//GEN-LAST:event__bt_Jf_user_login_CancelMousePressed

    private void _bt_Jf_user_login_CancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_Jf_user_login_CancelMouseReleased
        _bt_Jf_user_login_Cancel.setBorder(border);
    }//GEN-LAST:event__bt_Jf_user_login_CancelMouseReleased

    private void _bt_Jf_user_login_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__bt_Jf_user_login_LoginActionPerformed
        Jf_UserMain mainF = new Jf_UserMain();
        mainF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event__bt_Jf_user_login_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jf_user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jf_user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jf_user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jf_user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jf_user_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Middle;
    private javax.swing.JPanel Top;
    private javax.swing.JButton _bt_Jf_user_login_Cancel;
    private javax.swing.JButton _bt_Jf_user_login_Login;
    private javax.swing.JLabel _lb_user_login_close;
    private javax.swing.JLabel _lb_user_login_forgotPassword;
    private javax.swing.JLabel _lb_user_login_logo;
    private javax.swing.JLabel _lb_user_login_minimize;
    private javax.swing.JLabel _lb_user_login_password;
    private javax.swing.JLabel _lb_user_login_pin;
    private javax.swing.JLabel _lb_user_login_qrCode;
    private javax.swing.JLabel _lb_user_login_seperator;
    private javax.swing.JLabel _lb_user_login_showPassword;
    private javax.swing.JLabel _lb_user_login_showPassword1;
    private javax.swing.JLabel _lb_user_login_userName;
    private javax.swing.JPasswordField _pf_user_login_password;
    private javax.swing.JTextField _tf_user_login_pin;
    private javax.swing.JTextField _tf_user_loging_userName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
