/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fourgenius.www.public_access.practicals;

import com.fourgenius.www.public_access.exams.*;
import com.fourgenius.www.user_FrontEnd.*;
import com.fourgenius.www.public_access.registration.employee.Jp_registration_employee;
import com.fourgenius.www.public_access.registration.lecture.Jp_registration_lecture;
import com.fourgenius.www.public_access.registration.student.Jp_registration_student;
import com.fourgenius.www.public_access.registration.user.Jp_registration_user;
import com.fourgenius.www.public_access.registration.student.Jp_student_payment;
import com.fourgenius.www.public_access.user.login.Jf_user_login;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.border.Border;

/**
 *
 * @author thilina_deepal
 */
public class Jf_practicals extends javax.swing.JFrame {

    Border border = BorderFactory.createLineBorder(Color.white, 1);

    /**
     * Creates new form main_frame
     */
    public Jf_practicals() {
        initComponents();
        showTime();
        try {
            initComponents();
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {

        }
        loadFrame();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_time_date = new javax.swing.JLabel();
        _bt_UserMain_home = new javax.swing.JButton();
        Jp_userMain_main_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(66, 66, 66));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(18, 75, 163));
        jPanel3.setMinimumSize(new java.awt.Dimension(1368, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(1368, 50));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        lb_time_date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_time_date.setForeground(new java.awt.Color(255, 255, 255));
        lb_time_date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        _bt_UserMain_home.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _bt_UserMain_home.setForeground(new java.awt.Color(255, 255, 255));
        _bt_UserMain_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fourgenius/www/public_access/user/login/images_butons/button_LightBlue_200x50.png"))); // NOI18N
        _bt_UserMain_home.setText("Home");
        _bt_UserMain_home.setAutoscrolls(true);
        _bt_UserMain_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _bt_UserMain_home.setFocusPainted(false);
        _bt_UserMain_home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _bt_UserMain_home.setMaximumSize(new java.awt.Dimension(200, 50));
        _bt_UserMain_home.setMinimumSize(new java.awt.Dimension(200, 50));
        _bt_UserMain_home.setPreferredSize(new java.awt.Dimension(200, 50));
        _bt_UserMain_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _bt_UserMain_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                _bt_UserMain_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                _bt_UserMain_homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _bt_UserMain_homeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                _bt_UserMain_homeMouseReleased(evt);
            }
        });
        _bt_UserMain_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _bt_UserMain_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_bt_UserMain_home, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 918, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_time_date, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_bt_UserMain_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lb_time_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        Jp_userMain_main_panel.setBackground(new java.awt.Color(66, 66, 66));
        Jp_userMain_main_panel.setDoubleBuffered(false);
        Jp_userMain_main_panel.setMaximumSize(new java.awt.Dimension(1368, 718));
        Jp_userMain_main_panel.setMinimumSize(new java.awt.Dimension(1368, 718));
        Jp_userMain_main_panel.setPreferredSize(new java.awt.Dimension(1366, 718));
        Jp_userMain_main_panel.setLayout(new java.awt.CardLayout());
        jPanel1.add(Jp_userMain_main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1366, 718));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    
    
    
    Jf_user_login jf_user_login = new Jf_user_login();
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        

//        Jp_student_payment._tf_student_payment_paymentDatails_studentName.setText(Jp_registration_student._lb_registration_student_preview_name.getText());
//        Jp_student_payment._tf_student_payment_paymentDatails_course.setText(Jp_registration_student._lb_registration_student_preview_course.getText());
//        Jp_student_payment._tf_student_payment_paymentDatails_courseFee.setText("70000");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void _bt_UserMain_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_UserMain_homeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event__bt_UserMain_homeMouseClicked

    private void _bt_UserMain_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_UserMain_homeMouseEntered
        _bt_UserMain_home.setBorder(border);
    }//GEN-LAST:event__bt_UserMain_homeMouseEntered

    private void _bt_UserMain_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_UserMain_homeMouseExited
  _bt_UserMain_home.setBorder(null);
    }//GEN-LAST:event__bt_UserMain_homeMouseExited

    private void _bt_UserMain_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_UserMain_homeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event__bt_UserMain_homeMousePressed

    private void _bt_UserMain_homeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__bt_UserMain_homeMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event__bt_UserMain_homeMouseReleased

    private void _bt_UserMain_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__bt_UserMain_homeActionPerformed
        
        this.dispose();
        new Jf_UserFront().setVisible(true);
        
    }//GEN-LAST:event__bt_UserMain_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jf_practicals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jf_practicals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jf_practicals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jf_practicals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jf_practicals().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jp_userMain_main_panel;
    public static javax.swing.JButton _bt_UserMain_home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lb_time_date;
    // End of variables declaration//GEN-END:variables


    private void loadFrame() {
        Jp_add_practicals add_exams = new Jp_add_practicals();

        if (add_exams == null) {
            add_exams = new Jp_add_practicals();
            Jp_userMain_main_panel.removeAll();
            Jp_userMain_main_panel.repaint();
            Jp_userMain_main_panel.revalidate();
            Jp_userMain_main_panel.add(add_exams);
            Jp_userMain_main_panel.repaint();
            Jp_userMain_main_panel.revalidate();
        } else {
            Jp_userMain_main_panel.removeAll();
            Jp_userMain_main_panel.repaint();
            Jp_userMain_main_panel.revalidate();
            Jp_userMain_main_panel.add(add_exams);
            Jp_userMain_main_panel.repaint();
            Jp_userMain_main_panel.revalidate();
        }
    }

    void showTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {

                Date d = new Date();
                SimpleDateFormat stim = new SimpleDateFormat("hh:mm:ss a");
                String st = stim.format(d);
                lb_time_date.setText(st);

            }
        }).start();
    }
}
